### ISSUE TITLE
outdated package 'economic'

### ISSUE THREAD

**Issue by schreibe** [MiKTeX/miktex-packaging#10]
Hi, I can't believe I'm the first one to stumble upon this, but it's not among the open issues, so here goes: the package 'economic' in Miktex dates from 2008-12-29 according to its changelog, and packaged on 2009-01-02 according to the package manager. But on its CTAN page the latest package version is from 2009-11-18 (see https://www.ctan.org/pkg/economic). This makes a difference in some cases, for example jae.bst is missing.
Not sure whether it's a Miktex or a CTAN bug, though; because on the page above the latest update announcement is indeed from 2009-01-02. However, a file listing of the Debian/Ubuntu package texlive-bibtex-extra does include that jae.bst file.
thanks,
sven

**Comment by edocevoli** [comment]
Thank you, this has been fixed. You can run the updater now.
