### ISSUE TITLE
Outdated glyphtounicode.tex causes missing ToUnicode mappings for some glyphs

### ISSUE THREAD

**Issue by hynner** [MiKTeX/miktex-packaging#100]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

MiKTeX's version of pdftex includes outdated version of glyphtounicode.tex (the file says it is v 1.1 2007/02/04 19:23:07). This leads to missing ToUnicode mappings for some glyphs (which is a problem for creating valid PDF/A files and also for copying text from the pdf).

**How to reproduce:**
Here is an example with some of the glyphs without mapping.
```latex
\documentclass[12pt,a4paper]{report}
\usepackage[a-2u]{pdfx}
\usepackage[utf8]{inputenc}
\usepackage{amsfonts}

\begin{document}
$\sqsubset \sqsupset \ulcorner \urcorner \llcorner  \lrcorner \checkmark \maltese \yen \circledR \mho \rightleftharpoons \hbar \square \trianglerighteq \trianglelefteq \rightsquigarrow$
\end{document}
```
The issue can be resolved by placing the newest version of the glyphtounicode.tex file (which I extracted from texlive's source) to the same directory as the example file, thus overriding the one shipped by MiKTeX.

My MiKTeX report:

```
Date: 2019-05-23 18:24:25
MiKTeX: 2.9.6980
OS: Linux 5.1.3-arch1-1-ARCH #1 SMP PREEMPT Thu May 16 20:59:36 UTC 2019 x86_64
SharedSetup: no
PathOkay: yes
LastUpdateCheck: 2019-05-21 11:40:49
LastUpdate: 2019-05-21 11:41:08
SystemAdmin: no
RootPrivileges: no
AdminMode: no
Root0: /home/hynner/.miktex/texmfs/config
Root1: /home/hynner/.miktex/texmfs/data
Root2: /home/hynner/.miktex/texmfs/install
Root3: /opt/miktex/texmfs/config
Root4: /opt/miktex/texmfs/data
Root5: /opt/miktex/texmfs/install
UserInstall: /home/hynner/.miktex/texmfs/install
UserConfig: /home/hynner/.miktex/texmfs/config
UserData: /home/hynner/.miktex/texmfs/data
CommonInstall: /opt/miktex/texmfs/install
CommonConfig: /opt/miktex/texmfs/config
CommonData: /opt/miktex/texmfs/data
```
Zip archive containing the updated glyphtounicode.tex I used, as well as pdf and log files for both the default (bad) and fixed (good) configuration.
[miktex-submission.zip](https://github.com/MiKTeX/miktex-packaging/files/3213240/miktex-submission.zip)

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
