### ISSUE TITLE
acmart.cls is not installed

### ISSUE THREAD

**Issue by borisveytsman** [MiKTeX/miktex-packaging#101]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Looks like `acmart.cls` is not installed in 1.60, see `https://miktex.org/Package/Browse/acmart`

Moved from https://github.com/borisveytsman/acmart/issues/346

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
