### ISSUE TITLE
Need to rename convert for imagemagick to "magick convert"

### ISSUE THREAD

**Issue by lepete11** [MiKTeX/miktex-packaging#103]
There's a very egregious problem related to Windows installs and using tex4ht, since the tex4ht.env file lists "convert" as in convert.exe as the executable to convert .eps images in the converted_graphics folder into .png or .svg which are needed for htlatex.   

If you install imagemagick in Windows 10, there will be no convert.exe anywhere in the subfolders, since their developers know that convert.exe in DOS reformats FAT and FAT32 partitions!   The executable that actually converts images in a Windows 10 install is "magick.exe," but it requires the command line option "convert" thereafter followed by the input image filename and the output image filename with the new file extension.   

Therefore, you should re-design all the paths in tex4ht.env for image conversion by imagemagick, since it is quite convoluted and useless in its current form.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
