### ISSUE TITLE
Update actuarialangle

### ISSUE THREAD

**Issue by RuixiZhang42** [MiKTeX/miktex-packaging#104]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The `actuarialangle` package was updated to v2.1 about a week ago: https://www.ctan.org/pkg/actuarialangle which was soon followed by an update of `actuarialsymbol` to v1.1.

Current MiKTeX ships the new `actuarialsymbol` but not the new `actuarialangle`.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
