### ISSUE TITLE
luatexja is missing generated cls/clo files

### ISSUE THREAD

**Issue by moewew** [MiKTeX/miktex-packaging#105]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The `luatexja` packages seems to be missing all `.ins`-generated `.cls` and `.clo` files. Compare https://miktex.org/Package/Browse/luatexja with http://tug.org/svn/texlive/trunk/Master/texmf-dist/tex/luatex/luatexja/.

Hence,
```latex
\documentclass{ltjsarticle}


\begin{document}
〇〇について
\end{document}
```
when run with LuaLaTeX fails and complains about the missing class `ltjsarticle`.

I just ran `lualatex` on `ltjclasses.ins`, `ltjltxdoc.ins` and `ltjsclasses.ins` as described in http://mirrors.ctan.org/macros/luatex/generic/luatexja/README. This produced a few `.cls` and `.clo` files and the example compiles fine (if the font is installed).

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
