### ISSUE TITLE
Package "l3kernel" is broken on most recent release.

### ISSUE THREAD

**Issue by c3h899** [MiKTeX/miktex-packaging#107]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

### Step to reproduce:
* Attempt to compile tex source with pdflatex
* Returns error 'l3backend-pdfmode.def not found'

### Platforms Tested:
* basic-miktex-2.9.7100-x64.exe (multiple installs)
* Ubuntu 18.04 LTS (Bionic Beaver) (install from repository)
  * Fresh Windows Subsystem for Linux Install
  * Fresh Ubuntu 18.04 LTS Install (VirtualBox)

### Work-around
* Manually reinstalling l3kernel from the source manager resolves this issue.

**Comment by edocevoli** [comment]
Since you have not attached a test case, it is not possible to reproduce the bug.
