### ISSUE TITLE
Follow up to mac link being broken

### ISSUE THREAD

**Issue by maclatexdur** [MiKTeX/miktex-packaging#109]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Apologies if making a new post is the wrong approach but the old one is now locked. I have tried multiple PCs, multiple browsers in multiple locations (UK based) and they all lead to the same thing (see attached picture) so I am fairly confident something is wrong.

![Miktexbroken](https://user-images.githubusercontent.com/52918491/61222096-ee8cd380-a711-11e9-939e-e782f8487cb6.PNG)

**Comment by edocevoli** [comment]
Please fix your browser setup or use a download tool (say `wget`). This is nothing we can fix on the server side.
