### ISSUE TITLE
Possibly incomplete 'doclicense' package

### ISSUE THREAD

**Issue by amintos** [MiKTeX/miktex-packaging#11]
I am afraid that the `doclicense` package in the current (2017-11-14) repository is missing the two subdirectories `images` and `license-texts`.

For example, `doclicense-CC-by.pdf`, previously contained in the package's root directory, resides in a subfolder according to [CTAN](https://ctan.org/tex-archive/macros/latex/contrib/doclicense) and does not appear in the [current MiKTeX package](https://miktex.org/Package/Browse/doclicense) any more.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. You can run the updater now.
