### ISSUE TITLE
cjk package: Missing Files

### ISSUE THREAD

**Issue by manuel-kuehner** [MiKTeX/miktex-packaging#110]
Hi and thanks for MiKTeX! 

- I run into a problem related to the cjk package.
- **I documented my problem here: https://tex.stackexchange.com/questions/500093.**
- User Ulrike Fischer statet "[...] the miktex cjk support has a number of problems (including missing fonts)." in a comment to my question.

Maybe you can have a look :).

**Comment by edocevoli** [comment]
This is not complete and self-contained bug report.
