### ISSUE TITLE
Not all Ghostscript's free fonts are included in Basic Installer

### ISSUE THREAD

**Issue by ivankokan** [MiKTeX/miktex-packaging#112]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md)

Along with the Issue https://github.com/MiKTeX/miktex/issues/339, I took even more time to check all 35 commercial-quality Type 1 basic PostScript fonts mentioned at https://www.ghostscript.com/doc/current/Fonts.htm#Free_fonts, and listed in `Fontmap.aliases` and having mappings defined in `Fontmap.MiKTeX`:
```
% bookman
/URWBookmanL-DemiBold (type1/urw/bookman/ubkd8a.pfb) ;
/URWBookmanL-DemiBoldItal (type1/urw/bookman/ubkdi8a.pfb) ;
/URWBookmanL-Ligh (type1/urw/bookman/ubkl8a.pfb) ;
/URWBookmanL-LighItal (type1/urw/bookman/ubkli8a.pfb) ;
% courier
/NimbusMonL-Regu (type1/urw/courier/ucrr8a.pfb) ;
/NimbusMonL-ReguObli (type1/urw/courier/ucrro8a.pfb) ;
/NimbusMonL-Bold (type1/urw/courier/ucrb8a.pfb) ;
/NimbusMonL-BoldObli (type1/urw/courier/ucrbo8a.pfb) ;
% avantgar
/URWGothicL-Book (type1/urw/avantgar/uagk8a.pfb) ;
/URWGothicL-BookObli (type1/urw/avantgar/uagko8a.pfb) ;
/URWGothicL-Demi (type1/urw/avantgar/uagd8a.pfb) ;
/URWGothicL-DemiObli (type1/urw/avantgar/uagdo8a.pfb) ;
% helvetic
/NimbusSanL-Regu (type1/urw/helvetic/uhvr8a-105.pfb) ;
/NimbusSanL-Regu (type1/urw/helvetic/uhvr8a.pfb) ;
/NimbusSanL-ReguItal (type1/urw/helvetic/uhvro8a-105.pfb) ;
/NimbusSanL-ReguItal (type1/urw/helvetic/uhvro8a.pfb) ;
/NimbusSanL-Bold (type1/urw/helvetic/uhvb8a.pfb) ;
/NimbusSanL-BoldItal (type1/urw/helvetic/uhvbo8a.pfb) ;
/NimbusSanL-ReguCond (type1/urw/helvetic/uhvr8ac.pfb) ;
/NimbusSanL-ReguCond (type1/urw/helvetic/uhvrrc8a.pfb) ;
/NimbusSanL-ReguCondItal (type1/urw/helvetic/uhvro8ac.pfb) ;
/NimbusSanL-ReguCondItal (type1/urw/helvetic/uhvroc8a.pfb) ;
/NimbusSanL-BoldCond (type1/urw/helvetic/uhvb8ac.pfb) ;
/NimbusSanL-BoldCond (type1/urw/helvetic/uhvbrc8a.pfb) ;
/NimbusSanL-BoldCondItal (type1/urw/helvetic/uhvbo8ac.pfb) ;
/NimbusSanL-BoldCondItal (type1/urw/helvetic/uhvboc8a.pfb) ;
% palatino
/URWPalladioL-Roma (type1/urw/palatino/uplr8a.pfb) ;
/URWPalladioL-Ital (type1/urw/palatino/uplri8a.pfb) ;
/URWPalladioL-Bold (type1/urw/palatino/uplb8a.pfb) ;
/URWPalladioL-BoldItal (type1/urw/palatino/uplbi8a.pfb) ;
% ncntrsbk
/CenturySchL-Roma (type1/urw/ncntrsbk/uncr8a.pfb) ;
/CenturySchL-Ital (type1/urw/ncntrsbk/uncri8a.pfb) ;
/CenturySchL-Bold (type1/urw/ncntrsbk/uncb8a.pfb) ;
/CenturySchL-BoldItal (type1/urw/ncntrsbk/uncbi8a.pfb) ;
% times
/NimbusRomNo9L-Regu (type1/urw/times/utmr8a.pfb) ;
/NimbusRomNo9L-ReguItal (type1/urw/times/utmri8a.pfb) ;
/NimbusRomNo9L-Medi (type1/urw/times/utmb8a.pfb) ;
/NimbusRomNo9L-MediItal (type1/urw/times/utmbi8a.pfb) ;
% symbol
/StandardSymL (type1/urw/symbol/usyr.pfb) ;
% zapfchan
/URWChanceryL-MediItal (type1/urw/zapfchan/uzcmi8a.pfb) ;
% zapfding
/Dingbats (type1/urw/zapfding/uzdr.pfb) ;
```

Those fonts are available in packages `bookman`, `courier`, `avantgar`, `helvetic`, `palatino`, `ncntrsbk`, `times`, `symbol`, `zapfchan` and `zapfding`. All of them belong to the MiKTeX's Basic set of packages, except `symbol` which is declared as Advanced (and not installed by default as the others) - is there any special reason?

Considering that these Ghostscript's free fonts form an unique set of fonts 
> 35 commercial-quality Type 1 basic PostScript fonts -- Times, Helvetica, Courier, Symbol, etc. -- contributed by URW++ Design and Development Incorporated, of Hamburg, Germany (http://www.urwpp.de/). Fontmap names them all.

...and the size of `symbol` package is only 68,88 KiB, it would be convenient to declare `symbol` package to be Basic as well so it gets installed by default.

Kind regards, Ivan

**Comment by ivankokan** [comment]
Hi. Current status is such that only `courier` and `zapfding` are Basic, while the others are not. How did it change and who actually controls this?

**Comment by Visperad22** [comment]
Is this issue solved? how can I add other fonts manually?

**Comment by ivankokan** [comment]
> Is this issue solved? how can I add other fonts manually?

Not yet, neither we know why things have changed in Basic/Advanced context meanwhile.

For the above mentioned fonts, install these packages through MiKTeX Console Packages view:
> Those fonts are available in packages `bookman`, `courier`, `avantgar`, `helvetic`, `palatino`, `ncntrsbk`, `times`, `symbol`, `zapfchan` and `zapfding`.

**Comment by ivankokan** [comment]
> Is this issue solved? how can I add other fonts manually?

Other fonts in general: you must find out which packages contain them, and install those packages.

If you do not know, dig into your local `Fontmap.MiKTeX`, or the (very recent) one merged here: https://github.com/MiKTeX/miktex/pull/437/files. Once you detect all `*.pfb` resources you need, use MiKTeX Console Package view to filter the package list, and install the filtered packages.

Or, the ultimate approach: use MiKTeX Console Packages view to filter the package list with `*.pfb`, and install all filtered packages.

**Comment by mimigdal** [comment]
Please note that this issue affects the ability of "epstopdf" to transform "eps" images that are created by Matlab into "pdf". I suspect that this may affect many users. I currently solved this problem on my machine by installing the "helvetica" and "times" packages through the MiKTeX console.

**Comment by ivankokan** [comment]
> Please note that this issue affects the ability of "epstopdf" to transform "eps" images that are created by Matlab into "pdf". I suspect that this may affect many users. I currently solved this problem on my machine by installing the "helvetica" package (plus, any other font used by the Matlab code) through the MiKTeX console.

**Comment by ivankokan** [comment]
https://github.com/MiKTeX/miktex/issues/429#issuecomment-618307634

> Those fonts are available in packages `bookman`, `courier`, `avantgar`, `helvetic`, `palatino`, `ncntrsbk`, `times`, `symbol`, `zapfchan` and `zapfding`. All of them belong to the MiKTeX's Basic set of packages, except `symbol` which is declared as Advanced (and not installed by default as the others) - is there any special reason?
> 
> Considering that these Ghostscript's free fonts form an unique set of fonts
> 
> > 35 commercial-quality Type 1 basic PostScript fonts -- Times, Helvetica, Courier, Symbol, etc. -- contributed by URW++ Design and Development Incorporated, of Hamburg, Germany (http://www.urwpp.de/). Fontmap names them all.
> 
> ...and the size of `symbol` package is only 68,88 KiB, it would be convenient to declare `symbol` package to be Basic as well so it gets installed by default.

Please make sure all the mentioned packages are Basic (`M`).

**Comment by ivankokan** [comment]
Hi @edocevoli.

Hopefully, the current state is the outcome of intentional Basic (`M`) declarations:

```
[bookman]
CabMD5=a76ffdfbf662458804c701362bcac021
CabSize=329086
Level=M
MD5=488fdf0433647f163ad7442121b4dc85
TimePackaged=1159465592
Type=MSCab
```

```
[courier]
CabMD5=92238816e6c6f72ce057c9799e03fcd8
CabSize=508571
Level=M
MD5=d662dc38c0a2336c57ca2ad4f83a6272
TimePackaged=1303317872
Type=TarLzma
```

```
[avantgar]
CabMD5=e4352f7299ad7299cbef14f7c9c68c0a
CabSize=276931
Level=M
MD5=f375a9b4c7f30774adc3623aaf1c1704
TimePackaged=1159465592
Type=MSCab
```

```
[helvetic]
CabMD5=9af2da562ef951a723d574bfacefbd98
CabSize=745459
Level=M
MD5=0018d8f18232b2e59e1d45b2973addd0
TimePackaged=1159465592
Type=MSCab
```
```
[palatino]
CabMD5=11396d56694175de6bdc92c9e3f908ac
CabSize=379872
Level=M
MD5=162ddb07123e9cae4652b89fe1ca1afd
TimePackaged=1159465592
Type=MSCab
```

```
[ncntrsbk]
CabMD5=e3c3e67cc587fd99abeef9ec2d05b8b1
CabSize=325591
Level=M
MD5=c7b9e8046e4294b20dc49e35256794c9
TimePackaged=1159465592
Type=MSCab
```

```
[times]
CabMD5=ba640505d0db4f1687cccf88858bd08b
CabSize=391735
Level=M
MD5=6b4e605e9a579823d71f7313768db308
TimePackaged=1159465592
Type=MSCab
```

```
[symbol]
CabMD5=500e9a711f0f932541c366db3ed83d9e
CabSize=38166
Level=M
MD5=a7b914562244649aff7f4b536524042a
TimePackaged=1159465592
Type=MSCab
```

```
[zapfchan]
CabMD5=e4a5c233aa91e72c8e7796cf02ac3f19
CabSize=89149
Level=M
MD5=f026c10a0bc8127468d010911e56dcc4
TimePackaged=1159465592
Type=MSCab
```

```
[zapfding]
CabMD5=e0f413679291577ce6196907cb6a3db0
CabSize=47973
Level=M
MD5=78ec8ff1fb88c2befaa9906f4b7bb92c
TimePackaged=1159465592
Type=MSCab
```

Assuming so, I would say that this issue has been finally resolved. Thanks!
