### ISSUE TITLE
problem with esdin package

### ISSUE THREAD

**Issue by marcdpp** [MiKTeX/miktex-packaging#113]
Hi, I receive the following error message when my tex file includes the integral symbol:

!pdfTeX error: pdflatex (file esint10): Font esint10 at 600 not found
 ==> Fatal error occurred, no output PDF file produced!
Sorry, but "MiKTeX Compiler Driver" did not succeed.

The problem started after I downloaded the latest version of miktex and reinstalled the packages. Could there be a problem with the esdin package?
thanks.

**Comment by edocevoli** [comment]
I could not reproduce this with your test case.
