### ISSUE TITLE
lgrenc.dfu is missing in the greek-inputenc package

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#114]
This means that every file trying to use greek in utf8 fails:

~~~~
\documentclass{article}
\usepackage[LGR]{fontenc}
\begin{document}
Θέλω να ευχαριστήσω..
\end{document}
~~~~

~~~~
! Package inputenc Error: Unicode character Θ (U+0398)
(inputenc)                not set up for use with LaTeX.
~~~~

**Comment by moewew** [comment]
According to https://miktex.org/Package/Browse/greek-inputenc the file is still missing (consequently the MWE above still fails), but all other files including the documentation file `lgrenc.dfu.html` are present. TeX live has `lgrenc.dfu` in `texmf\tex\latex\greek-inputenc`, see https://www.tug.org/svn/texlive/trunk/Master/texmf-dist/tex/latex/greek-inputenc/ and https://tug.org/pipermail/tex-live-commits/2019-July/010336.html

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
