### ISSUE TITLE
esint package: missing files

### ISSUE THREAD

**Issue by rikidox** [MiKTeX/miktex-packaging#117]
esint package seems to be incomplete (after the last update, version 1.2b)
I get the following error message when I process my document with pdfLaTeX:

`!pdfTeX error: pdflatex.exe (file esint10): Font esint10 at 657 not found`
` ==> Fatal error occurred, no output PDF file produced!`

I fixed that problem by manually installing the esint-type1 package from
https://ctan.org/pkg/esint-type1

**Comment by edocevoli** [comment]
Thank you. `esint-type1` is now a MiKTeX package.
