### ISSUE TITLE
Titlesec package: Broken on MiKTeX since version 2.11

### ISSUE THREAD

**Issue by kevinvalk** [MiKTeX/miktex-packaging#120]
Initially I opened #119 as I thought it was a MiKTeX issue. This issue was closed and hence I opened an issue on the package itself https://github.com/jbezos/titlesec/issues/13. The author's conclusion is that it is an MiKTeX issue after all.

From what I understand is that `\InputIfFileExists` triggers a MiKTeX package update because block.tss is missing. However, this should not trigger MiKTeX package update mechanism as the file check is optional. Only if it exists it should use this file, else it has an internal fallback.

**Comment by edocevoli** [comment]
No. `block.tss` cannot trigger a file download because it isn't a part of any package. Maybe your local file name database is out-of-date.

**Comment by edocevoli** [comment]
If, after refreshing the package / file name database, the problem is still there: attach a minimal working example.

**Comment by kevinvalk** [comment]
Thanks! I think that indeed was a problem. Used another computer and everything just worked (even after updating package).

On the other machine I did clean file name database and update package list, will update this ticket when I have access to that machine.
