### ISSUE TITLE
Bug in Mac installation

### ISSUE THREAD

**Issue by pablobernabeu** [MiKTeX/miktex-packaging#121]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Hello,

I'm trying to download and install MiKTeX on a Mac OS Mojave 10.14.6 (18G87) that has plenty of free memory. When I access the appropriate [download page](https://anorien.csc.warwick.ac.uk/mirrors/CTAN/systems/win32/miktex/setup/darwin-x86_64/miktex-2.9.7050-1-darwin-x86_64.dmg), I just see a string of characters, the beginning of which is copied below. I would greatly appreciate any help.

> xÚc`Cüûÿÿ3™%,$k]�ä¿çxÚsuóTp
> a``dˆa``P>Ûm¤€<(é`ÓJP~0”ÿ÷H¹qcÚMçåÞÝ/‚6¼d‚Ê7@±ÂÆÇÏFÁ �‚á³xÚíÅ±	Â��À/\ l,Aˆ‚8€`+qÁYBÆH-Nàâ6
> 6©­ïšËr:Kš¢)2®«g{»¼&e·¨ÚÇj¾ï£üÌ¯ƒôm²Ë)‡”ßYg›:���������������À>lV=xÚíÚ1NBAà•©ECb°±ÐN=‚•
> ‡°“ÂÖÂÚƒ®à>áuÆB!äû’ÙÝ)v^Þn·™XW×Ý4‡)9ëö>óQûîfÔî÷gëþIR.ªåUÒª¦çÍdÿ-i6«-™FÊS•êrå»ï^Ï/ßo»³¬SGõžÆ\?±×™EÊQ5lÔó‚êm¿,¶^9ž»��üÒä]ÁO8Öeò0��€Uç!��à)Ó¾Ù¯ZÉVÝ·z˜º‹5óöë.¡+��`
> ìŽ3Î}vœ���������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������°ê>�û¬ˆxÚíÚlUõðÓåMy®
> % (8y2†&cŒGy*†RŠ)…¶(&Ž ÎŒð ¯ª¡ƒa JìÓ!YÐ±I……Æ
> 6uó1Y&8
> ;-—q¹©@Gµ›~>Íÿž{Î¹í½¿óû}sÓÜ��������������������������������������������������������������������������������������������������������������������������������������������������À—-.j\Ø”¯.ÞoÄÕ·+Ãµ<\MÛ^xxÂÿ{½EZ������ÀW@›ÓÁé`^Ðèâþù¸òÏüû—ïü°ü¶ed™A× 5˜þÌÒÃûiANx;0<35Üÿ~d‡Û´ 7<’<þ^ã¨§™ÿÙññeÛ >þÂ7
> ‚`F¸z†«ìxÙ‘ÖÍã.{i½çäCöÓcü¨Á·Î/ÙüÍ{ú¼3ù³1O¾4¡ïÈíÇ2vVTÑs¯OœÝxÉ/5¹»íG›3Ÿ‹ûóâ`PT=­¯¡žQášÌT•®Yae91Um
> «*{Í›"”}s¢yx¬ìÜŠÈ±„H…ña5Ad?1²myL½Û–^òiÚÔ„øKß§¸x>ˆ>×ð?çë_<—3wÊŒô´Ü®#Æ–ï—ÿ½¨Ë^¨ÚÛ\Gí]‚î1õçGºšÕÕGb»Ú6þJ]]µóIË>ž_³Uþƒ

**Comment by edocevoli** [comment]
It works for me. Don't know what the problem is.

**Comment by edocevoli** [comment]
Work-around: download the DMG from CTAN (ctan.org).
