### ISSUE TITLE
esint package : esint10.mf file is empty

### ISSUE THREAD

**Issue by T0T0R** [MiKTeX/miktex-packaging#123]
Metafont is unable to process the esint10.mf file from the 8/22/2019 esint package.
This file does not contain code, only comments.
I replaced it with an older version, and there was no problem anymore

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
Most likely this is not a MiKTeX-specific problem, i.e., it should be possible to reproduce the defect with other TeX implementations.

I would recommend that you report the issue to the developers of the software component.
