### ISSUE TITLE
filehook.sty and friends missing from filehook package

### ISSUE THREAD

**Issue by moewew** [MiKTeX/miktex-packaging#124]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

After the most recent update to the `filehook` package the `.sty` files
- `filehook.sty`
- `filehook-fink.sty`
- `filehook-listings.sty`
- `filehook-memoir.sty`
- `filehook-scrlfile.sty`
- `pgf-filehook.sty`

are all missing from the package. See also https://miktex.org/Package/Browse/filehook

Consequently running
```latex
\documentclass{article}
\usepackage{filehook}

\begin{document}
Lorem
\end{document}
```

errors with
```
! LaTeX Error: File `filehook.sty' not found.
```

The files are all installed by TeX live, cf. https://tug.org/pipermail/tex-live-commits/2019-August/010634.html. I have verified that they are generated when the `.ins` file is run with pdfTeX.

----

Also reported at https://github.com/MiKTeX/miktex/issues/357.

**Comment by edocevoli** [comment]
Thank you, I have updated the package.

Please check for updates tomorrow.
