### ISSUE TITLE
pdfcrop: The script engine could not be found.

### ISSUE THREAD

**Issue by jpstotz** [MiKTeX/miktex-packaging#129]
When I try to execute `pdfcrop` I get the following error message:
```
pdfcrop: The script engine could not be found.
pdfcrop: Data: scriptEngine="perl.exe", scriptName="pdfcrop"
```

I noticed that MiKTeX does not include a `perl.exe` - instead in contains a `runperl.exe`.

My MikTeX installation is about two years old, completely updated recently. 
I already tried to deinstall and re-install pdfcrop, but it had no effect.

**Comment by edocevoli** [comment]
Indeed, you need `perl.exe` in your executable search path.

**Comment by edocevoli** [comment]
That said: install Perl, if you want to execute Perl scripts.

**Comment by jpstotz** [comment]
Then please change the error message and add this vital information. Something like:

> pdfcrop: The script engine perl.exe could not be found.
> The program you want to execute requires an perl interpreter.
> MiKTeX does not include a perl interpreter. If you want to execute this program you have to download and install an Perl interpreter on your own.
