### ISSUE TITLE
adforn package: Missing file

### ISSUE THREAD

**Issue by dr-brown** [MiKTeX/miktex-packaging#130]
I updated MikTex and all packages to the current version. After that the
_adforn_ package stopped working.
pdflatex.exe shows the following error message:
> Sorry, but miktex-makemf did not succeed. The log file hopefully contains the information to get MiKTeX going again: [
\AppData\Local\MiKTeX\2.9\miktex\log\miktex-makemf.log
>
>
>Couldn't open `OrnementsA.cfg' hbf2gf (CJK ver. 4.8.4) 

Test.tex
`% !TEX TS-program = pdflatex`
`% !TEX encoding = UTF-8 Unicode`
`\listfiles`
`\documentclass[12pt]{article}`
`\title{Brief Article}`
`\author{The Author}`
`\makeatletter`
`\pdfmapfile{+ OrnementsADF.map}`
`\usepackage{adforn}`
`\begin{document}`
`\adforn{6}`
`\end{document}`

[cfgReport.txt](https://github.com/MiKTeX/miktex-packaging/files/3678534/cfgReport.txt)
[miktex-makemf.log](https://github.com/MiKTeX/miktex-packaging/files/3678536/miktex-makemf.log)
[test.log](https://github.com/MiKTeX/miktex-packaging/files/3678561/test.log)

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
This has been fixed with the latest package update.
