### ISSUE TITLE
Graphics: Version 1.3b on Windows10

### ISSUE THREAD

**Issue by urogers** [MiKTeX/miktex-packaging#132]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Updated to version 1.3b today (10/5) of the Graphics package and it will not compile on a Windows 10 system.

Minimum Working Example:
\documentclass{article}
\usepackage{graphics}
\begin{document}
\begin{figure}
   \includegraphics{MC_Antenna_Gain}
\end{figure}
\end{document}

Error Report
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7200)
entering extended mode
(C:/Users/nicrog/Dropbox/T_P_2/Scholar/Grants/Written/EWU_20/Test.tex
LaTeX2e <2018-12-01>
("C:\Program Files (x86)\MiKTeX 2.9\tex/latex/base\article.cls"
Document Class: article 2019/08/27 v1.4j Standard LaTeX document class
("C:\Program Files (x86)\MiKTeX 2.9\tex/latex/base\size10.clo"))
("C:\Program Files (x86)\MiKTeX 2.9\tex/latex/graphics\graphics.sty"
("C:\Program Files (x86)\MiKTeX 2.9\tex/latex/graphics\trig.sty")
("C:\Program Files (x86)\MiKTeX 2.9\tex/latex/graphics-cfg\graphics.cfg")
("C:\Program Files (x86)\MiKTeX 2.9\tex/latex/graphics-def\pdftex.def"))
No file Test.aux.
("C:\Program Files (x86)\MiKTeX 2.9\tex/context/base/mkii\supp-pdf.mkii"
[Loading MPS to PDF converter (version 2006.09.02).]
) ("C:\Program Files (x86)\MiKTeX 2.9\tex/latex/oberdiek\epstopdf-base.sty"
("C:\Program Files (x86)\MiKTeX 2.9\tex/generic/oberdiek\infwarerr.sty")
("C:\Program Files (x86)\MiKTeX 2.9\tex/latex/oberdiek\grfext.sty"
("C:\Program Files (x86)\MiKTeX 2.9\tex/generic/oberdiek\kvdefinekeys.sty"
("C:\Program Files (x86)\MiKTeX 2.9\tex/generic/oberdiek\ltxcmds.sty")))
("C:\Program Files (x86)\MiKTeX 2.9\tex/latex/oberdiek\kvoptions.sty"
("C:\Program Files (x86)\MiKTeX 2.9\tex/latex/graphics\keyval.sty")
("C:\Program Files (x86)\MiKTeX 2.9\tex/generic/oberdiek\kvsetkeys.sty"
("C:\Program Files (x86)\MiKTeX 2.9\tex/generic/oberdiek\etexcmds.sty"
("C:\Program Files (x86)\MiKTeX 2.9\tex/generic/oberdiek\ifluatex.sty"))))
("C:\Program Files (x86)\MiKTeX 2.9\tex/generic/oberdiek\pdftexcmds.sty"
("C:\Program Files (x86)\MiKTeX 2.9\tex/generic/oberdiek\ifpdf.sty")))
! Undefined control sequence.
\Ginclude@graphics ...\Ginput@path \set@curr@file 
                                                  {#1}\edef \uq@curr@file {\...
l.8    \includegraphics{MC_Antenna_Gain}
                                        
? 

FYI:  This was posted to stackexchange @ https://tex.stackexchange.com/questions/511138/miktex-graphics-version-1-3b-bug-on-windows-10

**Comment by moewew** [comment]
See also https://github.com/MiKTeX/miktex-packaging/issues/131. The issue should be resolved with today's update. If the update went through alright and all formats are correctly rebuilt, you should see
```
LaTeX2e <2019-10-01>
```
near the top of the `.log` file.

**Comment by urogers** [comment]
Thank you
