### ISSUE TITLE
Graphics Package Not Working

### ISSUE THREAD

**Issue by OLDerKiwi** [MiKTeX/miktex-packaging#133]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md) BUT am not sure that I understand them

1. Though I have used MiKTeX for a year I am not really sure what to do as I have never had a bug that I could not work out before. I am not at all sure what the correct thing to do is
2. Recently I updated MiKTeX 
3. The Graphics package did not work 
4. I found this Site #132 which says that the new updates should work _The issue should be resolved with today's update. If the update went through alright and all formats are correctly rebuilt, you should see LaTeX2e <2019-10-01> near the top of the .log file._
5. I ran a modified version of the test document and got <**LaTeX2e <2018-12-01>**> on the log file

I have 

- Updated MiKTeX on computer 1
- Ran the following tex file with the following log
- Uninstalled MiKTeX on Computer 2
- Reinstalled MiKTeX on Computer 2 
- I still get LaTeX2e <2018-12-01> 
- Obviously any ideas would be helpful as I am trying to get a 100 page document out as quickly as I can ( I need the graphics package working to do this)

%Minimum Working Example:
\documentclass{article}
\usepackage{graphics}
\begin{document}
\begin{figure}
% NOTE WELL I have a file GaslightMuseam.jpg in this folder
\includegraphics{GaslightMuseam.jpg}
\end{figure}
\end{document}

The Output is
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7200 64-bit)
entering extended mode
(C:/Ze_Sheared/MiKTeX/Test_Graphics/testGRAPHICS.tex
LaTeX2e <2018-12-01>
("C:\Program Files\MiKTeX 2.9\tex/latex/base\article.cls"
Document Class: article 2019/08/27 v1.4j Standard LaTeX document class
("C:\Program Files\MiKTeX 2.9\tex/latex/base\size10.clo"))
("C:\Program Files\MiKTeX 2.9\tex/latex/graphics\graphics.sty"
("C:\Program Files\MiKTeX 2.9\tex/latex/graphics\trig.sty")
("C:\Program Files\MiKTeX 2.9\tex/latex/graphics-cfg\graphics.cfg")
("C:\Program Files\MiKTeX 2.9\tex/latex/graphics-def\pdftex.def"))
No file testGRAPHICS.aux.
("C:\Program Files\MiKTeX 2.9\tex/context/base/mkii\supp-pdf.mkii"
[Loading MPS to PDF converter (version 2006.09.02).]
) ("C:\Program Files\MiKTeX 2.9\tex/latex/oberdiek\epstopdf-base.sty"
("C:\Program Files\MiKTeX 2.9\tex/generic/oberdiek\infwarerr.sty")
("C:\Program Files\MiKTeX 2.9\tex/latex/oberdiek\grfext.sty"
("C:\Program Files\MiKTeX 2.9\tex/generic/oberdiek\kvdefinekeys.sty"
("C:\Program Files\MiKTeX 2.9\tex/generic/oberdiek\ltxcmds.sty")))
("C:\Program Files\MiKTeX 2.9\tex/latex/oberdiek\kvoptions.sty"
("C:\Program Files\MiKTeX 2.9\tex/latex/graphics\keyval.sty")
("C:\Program Files\MiKTeX 2.9\tex/generic/oberdiek\kvsetkeys.sty"
("C:\Program Files\MiKTeX 2.9\tex/generic/oberdiek\etexcmds.sty"
("C:\Program Files\MiKTeX 2.9\tex/generic/oberdiek\ifluatex.sty"))))
("C:\Program Files\MiKTeX 2.9\tex/generic/oberdiek\pdftexcmds.sty"
("C:\Program Files\MiKTeX 2.9\tex/generic/oberdiek\ifpdf.sty")))
! Undefined control sequence.
\Ginclude@graphics ...\Ginput@path \set@curr@file 
                                                  {#1}\edef \uq@curr@file {\...
l.6 \includegraphics{GaslightMuseam.jpg}
                                        
? 
! Undefined control sequence.
\Ginclude@graphics ...e \expandafter {\@curr@file 
                                                  }}\expandafter \filename@p...
l.6 \includegraphics{GaslightMuseam.jpg}
                                        
? 
! Undefined control sequence.
<recently read> \unquote@name 
                              
l.6 \includegraphics{GaslightMuseam.jpg}
                                        
? 
! Undefined control sequence.
<recently read> \quote@name 
                            
l.6 \includegraphics{GaslightMuseam.jpg}
                                        
? 
! Undefined control sequence.
<recently read> \quote@name 
                            
l.6 \includegraphics{GaslightMuseam.jpg}
                                        
? 

! LaTeX Error: File `GaslightMuseam.jpg' not found.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.6 \includegraphics{GaslightMuseam.jpg}
                                        
? R
OK, entering \nonstopmode...
[1{C:/Users/Lrove/AppData/Local/MiKTeX/2.9/pdftex/config/pdftex.map}]
(testGRAPHICS.aux) )
(see the transcript file for additional information)<C:/Program Files/MiKTeX 2.
9/fonts/type1/public/amsfonts/cm/cmr10.pfb>
Output written on testGRAPHICS.pdf (1 page, 13913 bytes).
SyncTeX written on testGRAPHICS.synctex.gz.
Transcript written on testGRAPHICS.log.

Sorry, but "MiKTeX Compiler Driver" did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:\Users\Lrove\AppData\Local\MiKTeX\2.9\miktex\log\texify.log

**Comment by kiganev** [comment]
Same for me, I will be following here for the solution.

**Comment by nkarstens** [comment]
I am also having the same issue and #132 did not resolve it for me.

**Comment by edocevoli** [comment]
It works for me. At the moment I have not enough information (mwe, log files) to work on this issue effectively.

**Comment by edocevoli** [comment]
It seems that you are using an outdated LaTeX version:

```
LaTeX2e <2018-12-01>
```

I would recommend that you refresh format files.
