### ISSUE TITLE
microtype

### ISSUE THREAD

**Issue by petiard** [MiKTeX/miktex-packaging#134]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Hello!

Is it possible to update the package microtype?

The version in MiKTeX is 2.7b (2019/02/28) but the version on CTAN is 2.7c (2019-10-10).

It was not announced on ctan-ann@ctan.org :-(

Thank you.

François

**Comment by edocevoli** [comment]
Thank you, but please read the [contribution guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md) before submitting an issue ticket.
