### ISSUE TITLE
TrueType Font “droid” broken for PdfLaTex

### ISSUE THREAD

**Issue by raubv0gel** [MiKTeX/miktex-packaging#136]
Using latest MikTeX (clean install on Windows 10 x64) with latest `droid`-package (version 3.2) I am not able do get droid fonts to be embedded as TrueType font in PDF – now all fonts are bitmaps. There was a previous version of the `droid`-package where the issue did not occur. From one version to another version `\usepackage{droid}` did not work any more ("File droidmono.sty not found" in `droid.sty`). According to the doc we have to `\usepackage{droidsans}` now.

Please see further details at [https://tex.stackexchange.com/questions/514511/truetype-font-droid-broken-for-pdflatex-in-miktex](https://tex.stackexchange.com/questions/514511/truetype-font-droid-broken-for-pdflatex-in-miktex). Please see comments too.

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by raubv0gel** [comment]
@edocevoli, thank you very much!
