### ISSUE TITLE
iftex package: folder is empty sinc last update

### ISSUE THREAD

**Issue by AndreC75** [MiKTeX/miktex-packaging#138]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

It is therefore impossible to compile a document that uses it.

**Comment by edocevoli** [comment]
Works for me:

```
mpm --install iftex
cd MIKTEX_INSTALL_DIR
ls tex/generic/iftex
```

produces

```
ifetex.sty	ifpdf.sty	ifvtex.sty
ifluatex.sty	iftex.sty	ifxetex.sty
```

**Comment by AndreC75** [comment]
At home, the folder is empty.

**Comment by AndreC75** [comment]
I was wrong it is the file ifxetex.sty which is missing. I'm sorry. I'm sorry.
