### ISSUE TITLE
ifxetex folder empty since last update

### ISSUE THREAD

**Issue by AndreC75** [MiKTeX/miktex-packaging#139]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

During compilations, MikTeX proposes to install it and fails to compile because the folder is empty.

**Comment by edocevoli** [comment]
Cannot reproduce your issues. Please make sure that you have installed the latest packages. Also please note that package `ifxetex` is now obsolete. It has been removed from the MiKTeX package repository. The functionality is now implemented by package `iftex`.

**Comment by edocevoli** [comment]
So the workaround: make sure that `iftex` is installed.

**Comment by moewew** [comment]
Did you update MikTeX in both Admin and User mode? It may also help to update the package database to avoid MikTeX trying to install a now removed package (in the Console, go to *Tasks* > *Update package database* again do this in Admin and User mode).

**Comment by AndreC75** [comment]
The following code gives this error with the last update of MikTeX, but not with the second last one.
Maybe I should ask the question on tex.stackechange.com?
```
\documentclass{article}

\usepackage{tcolorbox}
\tcbuselibrary{poster}
\usepackage{tikz}

\usepackage{lipsum}

\begin{document}

\begin{tcbposter}[
  poster = {
    columns=2,
    rows=2,
    spacing=3mm,
    height=14cm,
    width=6cm,
  },
  ]
  \posterbox[
  colframe = red,
  width=5cm, height= 10cm
  ]{ }{\includegraphics[width=3cm]{example-image-a}}

\end{tcbposter}% <- delete blank ligne
\begin{tcbposter}[
  poster = {
    columns=1,
    rows=2,
    spacing=3mm,
    height=14cm,
    width=6cm,
  },
  ]
  \posterbox[
  colframe = blue,
  width=5cm, height= 10cm
  ]{ }{\includegraphics[width=3cm]{example-image-b}}

\end{tcbposter}

\end{document}
```

**Comment by AndreC75** [comment]
This is the beginning of the log file from compilation to its emergency stop.

> This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7200 64-bit) (preloaded format=pdflatex 2019.11.3)  3 NOV 2019 18:53
> entering extended mode
> **./test.tex
> (test.tex
> LaTeX2e <2019-10-01> patch level 1
> ("C:\Program Files\MiKTeX 2.9\tex/latex/base\article.cls"
> Document Class: article 2019/08/27 v1.4j Standard LaTeX document class
> ("C:\Program Files\MiKTeX 2.9\tex/latex/base\size12.clo"
> File: size12.clo 2019/08/27 v1.4j Standard LaTeX file (size option)
> )
> \c@part=\count80
> \c@section=\count81
> \c@subsection=\count82
> \c@subsubsection=\count83
> \c@paragraph=\count84
> \c@subparagraph=\count85
> \c@figure=\count86
> \c@table=\count87
> \abovecaptionskip=\skip41
> \belowcaptionskip=\skip42
> \bibindent=\dimen102
> )
> ("C:\Program Files\MiKTeX 2.9\tex/latex/geometry\geometry.sty"
> Package: geometry 2018/04/16 v5.8 Page Geometry
> 
> ("C:\Program Files\MiKTeX 2.9\tex/latex/graphics\keyval.sty"
> Package: keyval 2014/10/28 v1.15 key=value parser (DPC)
> \KV@toks@=\toks14
> )
> ("C:\Program Files\MiKTeX 2.9\tex/generic/iftex\ifpdf.sty"
> Package: ifpdf 2019/10/25 v3.4 ifpdf legacy package. Use iftex instead.
> 
> ("C:\Program Files\MiKTeX 2.9\tex/generic/iftex\iftex.sty"
> Package: iftex 2019/10/24 v1.0a TeX engine tests
> ))
> ("C:\Program Files\MiKTeX 2.9\tex/generic/iftex\ifvtex.sty"
> Package: ifvtex 2019/10/25 v1.7 ifvtex legacy package. Use iftex instead.
> )
> 
> ! LaTeX Error: File `ifxetex.sty' not found.

**Comment by AndreC75** [comment]
By adding the `iftex` folder in my `texmf` and then refreshing the database names, the compilation is done without any problem.
