### ISSUE TITLE
texdef package: script path is wrong

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#14]
The texdef package installs `texdef.pl`  (like texlive) in `scripts/texdef` but scripts.ini points to 

    texdef=scripts/texdef/perl/texdef.pl

There are a number of aliases, e.g.
 
    luatexdef=scripts/texdef/perl/texdef.pl

which are wrong too.

**Comment by edocevoli** [comment]
This has been fixed
