### ISSUE TITLE
Missing ifpdf.sty/ifvpdf.sty

### ISSUE THREAD

**Issue by joi28** [MiKTeX/miktex-packaging#141]
I try to compile the following file:

\documentclass{article}

\usepackage{hyperref}

\begin{document}

test
\end{document}

Miktex is up-to-date 12:22, 11/06/2019 MEZ.

Error message is:

This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7200 64-bit) (preloaded format=pdflatex 2019.11.6)  6 NOV 2019 12:19
entering extended mode
**./test.tex
(test.tex
LaTeX2e <2019-10-01> patch level 1
("C:\Program Files\MiKTeX 2.9\tex/latex/base\article.cls"
Document Class: article 2019/08/27 v1.4j Standard LaTeX document class
("C:\Program Files\MiKTeX 2.9\tex/latex/base\size10.clo"
File: size10.clo 2019/08/27 v1.4j Standard LaTeX file (size option)
)
\c@part=\count80
\c@section=\count81
\c@subsection=\count82
\c@subsubsection=\count83
\c@paragraph=\count84
\c@subparagraph=\count85
\c@figure=\count86
\c@table=\count87
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
) ("C:\Program Files\MiKTeX 2.9\tex/latex/hyperref\hyperref.sty"
Package: hyperref 2019/09/28 v7.00a Hypertext links for LaTeX
 ("C:\Program Files\MiKTeX 2.9\tex/generic/oberdiek\hobsub-hyperref.sty"
Package: hobsub-hyperref 2019/10/27
hobsub not currently supported, see hobsub.dtx to extract original code

("C:\Program Files\MiKTeX 2.9\tex/generic/oberdiek\ltxcmds.sty"
Package: ltxcmds 2016/05/16 v1.23 LaTeX kernel commands for general use (HO)
)

! LaTeX Error: File `ifvtex.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.7 \RequirePackage
                   {pdftexcmds}
*** (cannot \read from terminal in nonstop modes)

 
Here is how much of TeX's memory you used:
 375 strings out of 492453
 4855 string characters out of 3129826
 65247 words of memory out of 3000000
 4812 multiletter control sequences out of 15000+200000
 3640 words of font info for 14 fonts, out of 3000000 for 9000
 1141 hyphenation exceptions out of 8191
 28i,0n,19p,125b,36s stack positions out of 5000i,500n,10000p,200000b,50000s
!  ==> Fatal error occurred, no output PDF file produced!

Expected output:
No error output, produced file.

**Comment by edocevoli** [comment]
Works for me.
Please make sure that you have installed the latest `iftex` package.

Running

```
kpsewhich ifvtex.sty
```

should give you something like this:

```
C:/Program Files/MiKTeX 2.9/tex/generic/iftex/ifvtex.sty
```

**Comment by joi28** [comment]
If I do install that package (which was not installed before!), I receive this error message, with the same input as before. Note, I even reinstalled Miktex from scratch:

[test.log](https://github.com/MiKTeX/miktex-packaging/files/3814262/test.log)

I have no idea whether this should be the same bug, but the problems started yesterday after a simple upgrade/update.

**Comment by edocevoli** [comment]
Thank you. It seems that you have package conflicts because you have installed some packages as administrator, and some packages as user. See:

```
("C:\Program Files\MiKTeX 2.9\tex/generic/iftex\ifvtex.sty"
```

and

```
(C:\Users\kai\AppData\Roaming\MiKTeX\2.9\tex/latex/iftex\iftex.sty
```

You have to resolve these conflicts by running the updater in both scopes (admin/user).

**Comment by joi28** [comment]
That somehow worked; I needed to reinstall Miktex once more. Seems that somehow consistency was messed up. Thanks!
