### ISSUE TITLE
econometrica.bst not installed with 'economic' (but with 'beebe')

### ISSUE THREAD

**Issue by schreibe** [MiKTeX/miktex-packaging#149]
Hi,
the bibtex style econometrica.bst is supposed to come with the package 'economic', where it is indeed listed (as belonging under bibtex/bst/economic). However, even after re-installing the package that bst file does not appear in the filesystem. (Other bst files are installed alright there.)

A workaround is to install the beebe package which has that file, too. Yet another workaround is to use ecta.bst as a style instead, see also here: https://tex.stackexchange.com/questions/121253/bibtex-error-after-updating-to-texlive-2013-style-file-not-found, where some licensing issues are mentioned.

But in the end, is econometrica.bst missing in 'economic' on purpose, in which case it probably should be removed from the file listing, or is it simply an oversight?
thanks
sven

**Comment by edocevoli** [comment]
`econometrica.bst` is a symbolic link to `../../../../obsolete/biblio/bibtex/contrib/economic/econometrica.bst`. Which of course doesn't work. But it shows us that this file is considered obsolete. I will remove it from the package.

**Comment by schreibe** [comment]
Ok, good to have this clarified. Thanks!
