### ISSUE TITLE
auxhook no longer part of oberdiek package

### ISSUE THREAD

**Issue by cooch17** [MiKTeX/miktex-packaging#151]
As of 12.17.2019, the oberdiek package no longer contains auxhook.sty (such that .tex files that require it now throw an error about missing auxhook.sty, if oberdiek is updated from the MikTex repos). It has been forked into its own, standalone package, which does not, at present, show up on MikTeX repos. For the moment, it is easy enough to do a manual install, but for future updates -- how are new packages indexed in MikTeX repos?

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
