### ISSUE TITLE
Hypernat is gone away?

### ISSUE THREAD

**Issue by SASAWEN** [MiKTeX/miktex-packaging#154]
``LaTeX Error: File `hypernat.sty' not found.``
Some other package replaces it?

**Comment by SASAWEN** [comment]
1. download hypernat.zip and unzip, which contains 3 files: hypernat.sty, hypernat.pdf, hypernat.tex
2. put these 3 files to your tex file path
It really works!

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
