### ISSUE TITLE
British speller

### ISSUE THREAD

**Issue by marcoagpinto** [MiKTeX/miktex-packaging#155]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Hello!

I am the maintainer of the open-source British speller which I forked in 2013.

I did a search for "Dictionary" in the packages and it only displayed US, French and German.

I was wondering if I could "supply" a British package and, if so, where can I download the US file from and which name should I give to GB?

Yes, I couldn't download the US one since the site only displays its internal files.

I guess all I need to do is replace the US files with the GB ones and change the config or whatever file.

You can read more about my speller project on:
- GitHub:
https://github.com/marcoagpinto/aoo-mozilla-en-dict

- Proofing Tool GUI:
https://proofingtoolgui.org

If all goes well, I could release a version for this in the next update around the end of the month (GB V2.81).

Thank you for your time,

**Comment by marcoagpinto** [comment]
Hello!

Yesterday I have released a new version of the GB speller with major improvements.

Any news regarding my ticket?

Thanks!

**Comment by edocevoli** [comment]
Sorry for the delay. I will now take a look...

**Comment by marcoagpinto** [comment]
Thanks :-)

**Comment by marcoagpinto** [comment]
@edocevoli 

Hello!

Sorry to bother you again so soon, but I have released a major version of the British speller:
**Version: 2.83 — 1.Apr.2020
— 2 149 new words (1) 
(1) Added tons of plurals/possessives (WIP).
Added tons of COVID-19 related terms.
Removed hundreds of duplicates.**

All to say that I have added tons of COVID-19 terms not found on the other spellers.

Could you update the GB dictionary to this release?

Also, now that we are at it, could you also update the US dictionary? The one in my GitHub is Kevin Atkinson's version from 2019 while the one used in MiKTeX is from 2016?

Thanks!

Kind regards from,
    >Marco A.G.Pinto
      -----------------
