### ISSUE TITLE
TeX4ht updates

### ISSUE THREAD

**Issue by michal-h21** [MiKTeX/miktex-packaging#158]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

I think some TeX4ht updates are missing in Miktex, as they are installed directly to TL, without update to CTAN. In particular, it seems that graphics handling is broken after LaTeX core update.

I've packed the TeX4ht sources to a zip file and saved it on my web: 
https://www.kodymirus.cz/files/tex4ht-4ht-files.zip

The archive contains configuration files for LaTeX packages and also font definition files, which were substantially updated in the last months.

**Comment by edocevoli** [comment]
Thank you, Will take a look.

**Comment by edocevoli** [comment]
Thank you. I have updated packages `tex4ht` and `miktex-tex4ht`.
Please get the latest updates.
