### ISSUE TITLE
hycolor.sty is missing

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#159]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

After todays update the hycolor package is missing all content (which should be `hycolor.sty` and `xcolor-patch.sty`).

~~~~
\documentclass{article}
\usepackage{hycolor}

\begin{document}
Test
\end{document}
~~~~

gives

~~~~
! LaTeX Error: File `hycolor.sty' not found.
~~~~

**Comment by paulschuetz** [comment]
I can confirm this issue.

**Comment by Bobinshort** [comment]
I do have the same issue

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by kontiko** [comment]
I've wondered why my newly installed Miktex doesn't worked now i know thx

**Comment by IkeKap** [comment]
If anyone here needs an immediate solution, use this to get the package straight from CTAN : https://tex.stackexchange.com/questions/526260/file-hycolor-sty-not-found

**Comment by bladekp** [comment]
Already working, thanks for quick fix
