### ISSUE TITLE
Issues with Equations in Latex

### ISSUE THREAD

**Issue by tsrockon28** [MiKTeX/miktex-packaging#16]
`\documentclass{beamer}

\mode<presentation> {
	
	% The Beamer class comes with a number of default slide themes
	% which change the colors and layouts of slides. Below this is a list
	% of all the themes, uncomment each in turn to see what they look like.
	
	%\usetheme{default}
	%\usetheme{AnnArbor}
	%\usetheme{Antibes}
	%\usetheme{Bergen}
	%\usetheme{Berkeley}
	%\usetheme{Berlin}
	%\usetheme{Boadilla}
	%\usetheme{CambridgeUS}
	%\usetheme{Copenhagen}
	%\usetheme{Darmstadt}
	%\usetheme{Dresden}
	%\usetheme{Frankfurt}
	%\usetheme{Goettingen}
	%\usetheme{Hannover}
	%\usetheme{Ilmenau}
	%\usetheme{JuanLesPins}
	%\usetheme{Luebeck}
	\usetheme{Madrid}
	%\usetheme{Malmoe}
	%\usetheme{Marburg}
	%\usetheme{Montpellier}
	%\usetheme{PaloAlto}
	%\usetheme{Pittsburgh}
	%\usetheme{Rochester}
	%\usetheme{Singapore}
	%\usetheme{Szeged}
	%\usetheme{Warsaw}
	
	% As well as themes, the Beamer class has a number of color themes
	% for any slide theme. Uncomment each of these in turn to see how it
	% changes the colors of your current slide theme.
	
	%\usecolortheme{albatross}
	%\usecolortheme{beaver}
	%\usecolortheme{beetle}
	%\usecolortheme{crane}
	%\usecolortheme{dolphin}
	%\usecolortheme{dove}
	%\usecolortheme{fly}
	%\usecolortheme{lily}
	%\usecolortheme{orchid}
	%\usecolortheme{rose}
	%\usecolortheme{seagull}
	%\usecolortheme{seahorse}
	%\usecolortheme{whale}
	%\usecolortheme{wolverine}
	
	%\setbeamertemplate{footline} % To remove the footer line in all slides uncomment this line
	%\setbeamertemplate{footline}[page number] % To replace the footer line in all slides with a simple slide count uncomment this line
	
	%\setbeamertemplate{navigation symbols}{} % To remove the navigation symbols from the bottom of all slides uncomment this line
}

\usepackage{graphicx} % Allows including images
\usepackage{booktabs} % Allows the use of \toprule, \midrule and \bottomrule in tables

%----------------------------------------------------------------------------------------
%	TITLE PAGE
%----------------------------------------------------------------------------------------

\title[Presentation Practice]{Presentation Practice} % The short title appears at the bottom of every slide, the full title is only on the title page

\author{Tejendra Pratap Singh} % Your name
\institute[DSE] % Your institution as it will appear on the bottom of every slide, may be shorthand to save space
{
	Delhi School of Economics\\ % Your institution for the title page
	\medskip
	\textit{tsrockon28@gmail.com} % Your email address
}
\date{\today} % Date, can be changed to a custom date

\begin{document}
	
	\begin{frame}
	\titlepage % Print the title page as the first slide
\end{frame}

\begin{frame}
\frametitle{Overview} % Table of contents slide, comment this block out to remove it
\tableofcontents % Throughout your presentation, if you choose to use \section{} and \subsection{} commands, these will automatically be printed on this slide as an overview of your presentation
\end{frame}

%----------------------------------------------------------------------------------------
%	PRESENTATION SLIDES
%----------------------------------------------------------------------------------------

%------------------------------------------------
\section{Production Side Story} % Sections can be created in order to organize your presentation into discrete blocks, all sections and subsections are automatically printed in the table of contents as an overview of the talk
%------------------------------------------------

\subsection{Subsection Example} % A subsection can be created just before a set of slides with a common theme to further break down your presentation into chunks

\begin{frame}
\frametitle{Production Side Story}
Two Sectors
\end{frame}

\begin{frame}
\frametitle{Bullet Points}
\begin{itemize}
	\item Two Sector Economy
	\item Cottage Sector
	\item Modern Sector
	\item Modern Sector is more productive than cottage sector
	\item Vestibulum faucibus velit a augue condimentum quis convallis nulla gravida- This Line I donot understand.
\end{itemize}
\end{frame}

%------------------------------------------------

\begin{frame}
\frametitle{Blocks of Highlighted Text}
\begin{block}{Theorem 1}
	This can be used to place your theorems
\end{block}

\begin{block}{Theorem 2}
	Like Sum of two sides of a triangle is larger thanthe third Side.
\end{block}

\begin{block}{Theorem3}
	Suspendisse tincidunt sagittis gravida. Curabitur condimentum, enim sed venenatis rutrum, ipsum neque consectetur orci, sed blandit justo nisi ac lacus.
	\begin{itemize}
		\item I do not understand this
	\end{itemize}
\end{block}
\end{frame}

%------------------------------------------------
%------------------------------------------------

\begin{frame}
\frametitle{Multiple Columns}
\begin{columns}[c] % The "c" option specifies centered vertical alignment while the "t" option is used for top vertical alignment
	
	\column{.45\textwidth} % Left column and width
	\textbf{Heading}
	\begin{enumerate}
		\item Statement
		\item Explanation
		\item Example
	\end{enumerate}
	
	\column{.5\textwidth} % Right column and width
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer lectus nisl, ultricies in feugiat rutrum, porttitor sit amet augue. Aliquam ut tortor mauris. Sed volutpat ante purus, quis accumsan dolor.
	
\end{columns}
\end{frame}

%------------------------------------------------
\section{Second Section Tested}
%------------------------------------------------

\begin{frame}
\frametitle{Table}
\begin{table}
\begin{tabular}{l l l} %Three Columns depicted with three lines
	\toprule %for drawing the line in the table
	\textbf{Treatments} & \textbf{Response 1} & \textbf{Response 2}\\ %for giving headings to the columns
	\midrule %for drawing the line again
	Treatment 1 & 0.0003262 & 0.562 \\
	Treatment 2 & 0.0015681 & 0.910 \\
	Treatment 3 & 0.0009271 & 0.296 \\
	\bottomrule
\end{tabular}
\caption{Table caption} %Giving the table caption below
\end{table}
\end{frame}

%------------------------------------------------
%------------------------------------------------

\begin{frame}[fragile] % Need to use the fragile option when verbatim is used in the slide
\frametitle{Verbatim}
\begin{example}[Theorem Slide Code]
	\begin{verbatim}
	\begin{frame}
	\frametitle{Theorem}
	\begin{theorem}[Mass--energy equivalence]
	$E = mc^2$
	\end{theorem}
	\end{frame}\end{verbatim}
\end{example}
\end{frame}

%------------------------------------------------
\begin{frame}[allowframebreaks] {Framebreaking}
Hello World

\framebreak

Hello World2
\end{frame}

%------------------------------------------------
\begin{frame}[allowframebreaks] {Equations}
$U(x,y)= x+y$ 
\framebreak

$U(x,y)= xy$
\end{frame}
\end{document}

# **The Error:
**Process started: pdflatex.exe -synctex=1 -interaction=nonstopmode "newdoc1".tex

Sorry, but miktex-makemf did not succeed for the following reason: The mathkerncmssi source file could not be found. The log file hopefully contains the information to get MiKTeX going again: C:/Users/Tej/AppData/Local/MiKTeX/2.9/miktex/log/miktex-makemf.log You may want to visit the MiKTeX project pa

ge, if you need help.

Sorry, but miktex-makepk did not succeed for the following reason: PK font mathkerncmssi10 could not be created.

The log file hopefully contains the information to get MiKTeX going again: C:/Users/Tej/AppData/Local/MiKTeX/2.9/miktex/log/miktex-makepk.log You may want to visit the MiKTeX project page, if you need help.

Process exited with error(s)

Process started: pdflatex.exe -synctex=1 -interaction=nonstopmode "newdoc1".tex

Sorry, but miktex-makemf did not succeed for the following reason: The mathkerncmssi source file could not be found. The log file hopefully contains the information to get MiKTeX going again: C:/Users/Tej/AppData/Local/MiKTeX/2.9/miktex/log/miktex-makemf.log You may want to visit the MiKTeX project pa

ge, if you need help.

Sorry, but miktex-makepk did not succeed for the following reason: PK font mathkerncmssi10 could not be created. The log file hopefully contains the information to get MiKTeX going again: C:/Users/Tej/AppData/Local/MiKTeX/2.9/miktex/log/miktex-makepk.log You may want to visit the MiKTeX project page, if you need help.

Process exited with error(s)**

`**

**Comment by u-fischer** [comment]
This is not a packaging problem in miktex. Also you example is much too long. 

Run on a command line `updmap` to update the user map files.
