### ISSUE TITLE
latest METAFONT update breaks yap

### ISSUE THREAD

**Issue by cooch17** [MiKTeX/miktex-packaging#160]
Outlined in detail here - https://tex.stackexchange.com/questions/526478/sudden-issue-with-metafont-miktex

But, basically, after updating METAFONT, using the 1-29 build, yap breaks. When I try to use yap after the update to look at a .dvi file, yap throws the following error, suggesting that modes.mf is missing. [Using 64-bit MikTeX 2.9.7250 under Windows 10 Pro.]

      MiKTeX Problem Report
      Message: METAFONT modes cannot be initialized because 'modes.mf' is missing.
      Data:
      Source: Libraries\MiKTeX\Core\Session\mfmodes.cpp
      Line: 52
      MiKTeX: 2.9.7250
      OS: Windows 10 Pro, 64-bit, build 18363   

If I do a re-install, update everything *except* METAFONT, problem solved. So, there is definitely something 'broken' with the latest METAFONT update (or, yap no longer plays nicely with METAFONT since the update -- one or the other).

**Comment by edocevoli** [comment]
`modes.mf` is now in package `modes`. Refreshing the package database should fix this issue for you.

**Comment by cooch17** [comment]
Thanks very much.
