### ISSUE TITLE
l3kernel Needs Update

### ISSUE THREAD

**Issue by terry98004** [MiKTeX/miktex-packaging#161]
The need for an update to l3kernel is discussed here:
[https://tex.stackexchange.com/questions/526626/compile-failures-after-fontspec-update](url)

It appears to be a conflict between fontspec and expl3, with David Carlisle suggesting the solution is to update expl3.

In case this is a problem with my environment and not a MikTex package problem, I will provide more information regarding my environment, I am Windows 10 with a private user only install.  The MikTex Console says that fontspec was packaged on 2020-01-26 (installed 2020-02-01).  

Here is a mystery:  The Console says that l3kernel was packaged on 2020-01-24 and installed on 2019-12-19 (an apparent time machine).  When I go to the install directory:

c:\[stuff]\Programs\MikTex 2.9\tex\latex\l3kernel

all of the files are dated 2019-11-07.

**Comment by edocevoli** [comment]
`l3kernel` files should be at `2020-01-31`.

Please see if this fixes the problem:

https://miktex.org/kb/fix-user-admin-updates-out-of-sync

If this doesn't help, we can take a look at your log files.
