### ISSUE TITLE
sansmathaccent package is missing the tfm and vf files

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#162]
The tfm and vf files of sansmathaccent (https://ctan.org/tex-archive/fonts/sansmathaccent/tfm, https://ctan.org/tex-archive/fonts/sansmathaccent/vf) are missing in the miktex package. This means that every beamer document currently fails:

~~~~
\documentclass{beamer}

\begin{document}
\begin{frame}
$a=b$
\end{frame}
\end{document}
~~~~

~~~~
! Font OT1/mathkerncmss/m/sl/10.95=mathkerncmssi10 at 10.95pt not loadable: Metric (TFM) file not found.
~~~~

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
