### ISSUE TITLE
Issue using package acro: Control Sequence \acro_dot: already defined

### ISSUE THREAD

**Issue by nullpunktTUD** [MiKTeX/miktex-packaging#166]
I am trying to compile a document  on my Windows 10 home PC using the current MiKTeX version, that I can compile perfectly fine on my Windows 10 work PC (it's the exact same file in a cloud synced folder). 

On my home PC I get the following error message:

```

acro.definitions.tex
523
LaTeX3 Error: Control sequence \acro_dot: already defined.

For immediate help type H <return>.
 ...                                              
                                                  
l.523 \cs_new_protected:Npn \acro_dot:
```
I can reproduce it with the following minimum example: 

```latex
\documentclass{article}
\usepackage{acro}

\begin{document}
This is a minimal example.
\end{document}
```
The log is attached.
[untitled-2.log](https://github.com/MiKTeX/miktex-packaging/files/4232976/untitled-2.log)

**Comment by edocevoli** [comment]
# Contributing to MiKTeX

## Reporting a package bug

Please note: this issue tracker if for problems regarding the contents
of the MiKTeX package repository. So it is okay to report issues like
the following:

- `xyz` should be added to the repository
- `xyz` is incorrectly packaged

__This issue tracker is not for software bugs (defects in MiKTeX programs).__

__Please do not request a packages update unless the MiKTeX version
lacks behind the CTAN more then a month.__

__Please do not report functional package problems (e.g., `! Undefined control sequence.`).__

Thanks!

**Comment by edocevoli** [comment]
Your document compiles fine on my machine. Please make sure that you have the latest MiKTeX updates. If it still not works for you: please attach the MiKTeX log files.
