### ISSUE TITLE
No declaration for shape T1/pzc/mb/it

### ISSUE THREAD

**Issue by BeerStud** [MiKTeX/miktex-packaging#167]
Window 10 / amd 64

Until today, the following command worked fine in several documents I have created.

	{\usefont{T1}{pzc}{m}{it} \fontsize{22pt}{20pt}\selectfont %

Suddenly, actually after an update I did this morning of MikTex, the command fails and this is the error message:

LaTeX Font Info:    Trying to load font information for T1+pzc on input line 137.

("C:\Users\gerar\AppData\Local\Programs\MiKTeX 2.9\tex/latex/psnfss\t1pzc.fd"
File: t1pzc.fd 2001/06/04 font definitions for T1/pzc.)
! No declaration for shape T1/pzc/mb/it.
sub@sfcnt ...e forspace shapespace mandatory@arg }
                                                  error@fontshape else MiKTeX/miktex#1{Fo...
l.137 	{\usefont{T1}{pzc}{m}{it}
                                 \fontsize{22pt}{20pt}\selectfont %
This error message was generated by an \errmessage
command, so I can't give any explicit help.
Pretend that you're Hercule Poirot: Examine all clues,
and deduce the truth by order and method.

I have no idea why this suddenly started happening. This occurs even on existing documents that worked fine previously.

**Comment by edocevoli** [comment]
I don't think this is a MiKTeX specific issue.

**Comment by BeerStud** [comment]
I just contacted the 'TeXstudio' people, and they claim that if the only thing I did was update MikTeX, the problem is with MikTeX. I have not touched TexStudio (updating) in months. This problem did not occur until I updated MikTeX this morning.

Have you actually even tried this on a fully updated MikTeX system?

**Comment by edocevoli** [comment]
Tried what? (Take a close look at your bug report and guess what is missing.)

**Comment by BeerStud** [comment]
Thanks to a poster on the @'TeXstudio' forum, I received this bit of information.

This is a known bug of latex2e kernel (see latex3/latex2e#289), and has been fixed in latex2e-dev. If you have installed package latex-base-dev , you can run pdflatex-dev main.tex to verify it yourself (that the problem has been fixed in dev).

Anyway, this is a latex usage problem, hence has nothing to do with the editor, texstudio.

[](https://github.com/latex3/latex2e/issues/289)

Is this information sufficent to correct this problem?

**Comment by edocevoli** [comment]
Thank you for the info. This is not a MiKTeX-specific issue: nothing can be done here to correct the problem.

**Comment by BeerStud** [comment]
Fair enough, I guess. So what can I do to alleviate this problem?  It is causing me to have to rewrite several documents to work around this problem. What really disturbs me is that this worked fine on Monday. I am sorry now that I updated anything.

**Comment by edocevoli** [comment]
See the comment above for a workaround: run `pdflatex-dev main.tex` instead of `pdflatex main.tex`).

**Comment by BeerStud** [comment]
I just received the following notification.

Hi, the LaTeX2e 2020-02-02 Patch level 5 has been released 6 hours ago. This release contains the fix you need, hence you can use pdflatex directly and forget pdflatex-dev for a while. In one or two days, CTAN mirrors across the world will sync to this update and then you can use texlive (or miktex) package manager to install the release.
