### ISSUE TITLE
newtx missing nc and ncf option font files OMLzncmi.fd and OMLzncf.fd in 3/5/20 update

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#169]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)
The 3/5/20 update of newtx is missing the .fd files OMLzncmi.fd and OMLzncf.fd. The options ncf and nc of newtxmath produce the following logs, respectively:
<img width="490" alt="log" src="https://user-images.githubusercontent.com/61854785/76039616-3616d880-5f0a-11ea-9ad2-7b84c2fbdcc9.PNG">
<img width="490" alt="log2" src="https://user-images.githubusercontent.com/61854785/76039851-e1c02880-5f0a-11ea-93dc-5efd815f4668.PNG">

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket:

> Please do not report functional package problems (e.g., ! Undefined control sequence.).
