### ISSUE TITLE
pstricks out of date on MikTeX repos

### ISSUE THREAD

**Issue by cooch17** [MiKTeX/miktex-packaging#17]
With the release of 2.80a pstricks (31-Dec build date), a bug was introduced that was confirmed by Herbert Voss. He released a corrected version of pstricks several days ago, but it still isn't appearing in the MikTeX repos. According to Herbert (who just sent me this email):

"On CTAN is a fixed version since several days. And TeXLive already has it -- Herbert"

He requested that I 'inform MikTeX' that the problem is no longer with pstricks, but with the pstricks that is made available via the MikteX repos.

**Comment by edocevoli** [comment]
Thanks. I have updated the package.

Btw: there is usually no need to report such "out-of-date" issues. I can happen that the repository maintenance is interrupted for days or weeks due to vacation, illness, ... This is not a bug.
