### ISSUE TITLE
MikTex Problem in Downloading 

### ISSUE THREAD

**Issue by rizwangho** [MiKTeX/miktex-packaging#170]
MikTex is causing a problem in downloading from the Miktex website for the last two weeks. It stops various times during the download. Moreover, after installation, it does not run. If we install TexLive (which is quite heavy software) then it runs. I will be grateful if the problem can be resolved.

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
