### ISSUE TITLE
chickenize package is missing chickenize.tex

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#171]
The chickenize package https://ctan.org/tex-archive/macros/luatex/generic/chickenize contains a `chickenize.tex` which  is currently missing in the miktex package. 

~~~~
\documentclass{article}
\usepackage{chickenize}
\directlua{luatexbase.add_to_callback("post_linebreak_filter",randomchars,"chickenize")}

\begin{document}
abc
\end{document}
~~~~

gives 

~~~~
! LaTeX Error: File `chickenize.tex' not found.
~~~~

The texlive location is `tex/luatex/chickenize/chickenize.tex` (beside `chickenize.sty`).

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
