### ISSUE TITLE
MiKTeX Console fails to install boxedminipage2e

### ISSUE THREAD

**Issue by gjmcclure** [MiKTeX/miktex-packaging#174]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

I get this error when trying to install boxedminipage2e:

ERROR DETAILS
Program: C:\Program Files\MiKTeX 2.9\miktex\bin\x64\miktex-console_admin.exe
Source: Libraries\MiKTeX\PackageManager\RepositoryManifest.h:95
Error: Unknown archive file size.
Details: 
  package: boxedminipage2e

**Comment by edocevoli** [comment]
This package is now obsolete and it has been removed from the repository. Please update the package database.
