### ISSUE TITLE
xepersian package is empty 

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#177]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

After the update today xepersian.sty is missing. The package list of the package is completly empty.

**Comment by edocevoli** [comment]
Yes, my intention was to remove the package. But somehow this didn't work and now the package is empty.

It seems that the license issue has been solved, So I will bring `xepersian` with the next update.

**Comment by OHR64** [comment]
Hi edocevoli,
Could you tell when the next update to XePersian.sty will come?

**Comment by edocevoli** [comment]
It will be available tomorrow.

**Comment by OHR64** [comment]
Thank you so much for your prompt reply.

**Comment by OHR64** [comment]
Hi edocevoli,
I just installed the update to XePersian using MikTex. As soon as I compile the tex file (using XeLatex) that calls the package XePersian I get the Latex error : file xepersian.sty not found. Could you please tell what is going wrong.

**Comment by edocevoli** [comment]
Sorry that it does not work for you. For me it works:

```
C:\> kpsewhich xepersian.sty
/PATH/TO/INSTALLDIR/tex/xelatex/xepersian/xepersian.sty
```
