### ISSUE TITLE
docker MiKTeX package manager fails to install geometry package.

### ISSUE THREAD

**Issue by vincentb1** [MiKTeX/miktex-packaging#178]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

I am using the MiKTeX docker, and I came accord this example of failure 
[temp.zip](https://github.com/MiKTeX/miktex-packaging/files/4677737/temp.zip)

OK, I will just script a manual installation, but just for you to know…

I make the bug report here as I suspect that the issue is how the package is packaged for MiKTeX, and not the MiKTeX package manager itself.

**Comment by edocevoli** [comment]
Indeed, this not the right repository for Docker related MiKTeX issues.
