### ISSUE TITLE
Biblatex Package

### ISSUE THREAD

**Issue by platypusfeet** [MiKTeX/miktex-packaging#18]
I'm unable to install biblatex using MiKTeX. 

I use a local repository because I am working from a work computer and cannot connect to an online repository due to firewall settings. To install packages, I save the .lzma file from an online CTAN repository to my local repository, and have had no issues in the past.  

I updated MiKTeX on 1/3/18, but the biblatex package within the database says it was packaged on 2017-11-07, whereas the .lzma files available online were all packaged on 2017-12-31. When I try to install the package, I get a problem report that says: 

"The operation could not be completed because a required file failed verification."
...
"expectedMD5="5f163e479b721e0364c5e7a93c4f73e2",
actualMD5="f3514778f05f68171d82a18cf6a84c53" "

I've tried running the MiKTeX update multiple times, but it says everything is up to date. How can I install biblatex?

**Comment by u-fischer** [comment]
If you download an lzma you should also download miktex-zzdb1-2.9.tar.lzma and miktex-zzdb2-2.9.tar.lzma from the same source at the same time. They contain the package data and must fit.

**Comment by platypusfeet** [comment]
This fixed my problem. Thanks very much.
