### ISSUE TITLE
Thep package gbt7714 requires "tex -8bit" to unpack

### ISSUE THREAD

**Issue by zepinglee** [MiKTeX/miktex-packaging#181]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The `gbt7714.dtx` is encoded in UTF-8 and it contains some Chinese contents. Currently the install recipe is

https://github.com/MiKTeX/miktex-packaging/blob/58e948709954d8c61247baa8dc5dd73cca9191cb/tdsutil/recipes/gbt7714.ini#L1-L2

It converts the Chinese string `"等"` to `"^^e7^^ad^^89"` in `.bst` files. The correct command is `tex -8bit` or `xetex`.

Related issue: https://github.com/CTeX-org/gbt7714-bibtex-style/issues/57 (in Chinese)

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
