### ISSUE TITLE
tikzducks package is missing  a file

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#182]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The following document fails in miktex currently:

~~~~
\documentclass{article}
\usepackage{tikzducks}
\begin{document}
\tikz\duck;
\end{document}
~~~~

with the error

~~~~
! I can't find file `tikzducks-generic'.
l.50 \input tikzducks-generic
~~~~

In texlive the missing file and also the sty is (now) in tex/generic/tikzducks/ as the package works imho also with context now.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
