### ISSUE TITLE
Include expkv-opt

### ISSUE THREAD

**Issue by moewew** [MiKTeX/miktex-packaging#184]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The package `expkv-opt` (https://ctan.org/pkg/expkv-opt, current version 0.1a 2020-07-04) is present in TeX live (https://tug.org/pipermail/tex-live-commits/2020-July/014473.html), but appears to be missing in MikTeX.

Indeed, currently
```latex
\documentclass{article}
\usepackage{expkv-opt}

\begin{document}
Lorem
\end{document}
```
throws an error
```
! LaTeX Error: File `expkv-opt.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
```

Please include `expkv-opt` in the MikTeX package repository.

----

I'm not sure how requests to include a package are treated with regards to

> **Please do not request a packages update unless the MiKTeX version lacks behind the CTAN more then a month.**

in https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md (that's why I waited until today to report this even though I noticed it a few days ago), but in any case I'd like to respectfully ask you to reconsider the time span of one month.

I fully and completely understand that there needs to be a time limit to avoid being swamped by requests to include a package that would be included in an upcoming update anyway, but in my experience one month can be a bit too long. Would it be feasible to bring that time limit down a bit?

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
