### ISSUE TITLE
thmtools: incorrectly packaged caused by missing .ins 

### ISSUE THREAD

**Issue by muzimuzhi** [MiKTeX/miktex-packaging#186]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Hello, I'm the current maintainer of `thmtools`. When uploading `thmtools` v0.72 to CTAN on Aug 1, I made a mistake to not pack the required `.ins` file. This is fixed on CTAN on around Aug 3 (see [file list](https://ctan.org/tex-archive/macros/latex/contrib/thmtools/source) on CTAN), but without any announcement. 

I guess the missing `.ins` caused the problem reported on TeX-SX: [`thmtools.sty' not found - MikTex Console Issue?](https://tex.stackexchange.com/q/558698), in which a MiKTeX user found that

> When finally looking into my files, I found the thmtools file, which does not contain any sty files. (It only downloaded dtx files.)

So sorry for the inconvenience. I will be more careful in the future.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by muzimuzhi** [comment]
Many thanks. Now I can see the `.sty` files in https://miktex.org/packages/thmtools/files.
