### ISSUE TITLE
phonetic.sty

### ISSUE THREAD

**Issue by hvoss49** [MiKTeX/miktex-packaging#190]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The package phonetic installs only the fonts but not the LaTeX style files which are, of course, in a wrong subdirectory
on CTAN:  https://ctan.org/tex-archive/fonts/phonetic/Doc/2e

The files Uphon.fd and phonetic.sty  should also be installed.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
