### ISSUE TITLE
Distribution of tokcycle package

### ISSUE THREAD

**Issue by SSegletes** [MiKTeX/miktex-packaging#193]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

MikTeX does not seem to be distributing the tokcycle package properly.  It should install the file tokcycle.tex in the directory tex\generic\tokcycle (this is the primary package coding, employed with both LaTeX and TeX engines).  However, no such directory is created upon downloading the package.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
