### ISSUE TITLE
Missing *.def item

### ISSUE THREAD

**Issue by malcolmepa** [MiKTeX/miktex-packaging#196]
Since updating my MiKTeX package a few months ago and subsequently I routinely get the message that "l3backend-pdftex.def" is missing.  This appears to only be an issue with the 64 version but nor the 32 version (I have the 64 version on my work laptop and the 32 version on my personal laptop).  I would like to get this missing file installed on my work laptop.  Thank you.

**Comment by edocevoli** [comment]
Thank you for the report. I was not able to reproduce this issue.

**Comment by malcolmepa** [comment]
Hi Christian,

I appreciate your quick response to my problem (see the second to the last line).  Attached is the Log file for my error.  If I hit <Return> when the error occurs, the LaTeXing continues and a PDF is produced, which appears, as far, as I can tell correctly.  However, the LaTeXing process appears to have failed because the process ends with one error listed.

I don’t know if you will be able to discern anything from that attached Log file.  If not, then I guess I am faced with two options: (1) continue with my setup as it is and pretend that the problem isn’t occurring, or (2) reinstall MiKTeX.  Please let me know what you think that I should do.

Thank you for your assistance.

Cheers,

Malcolm

**Comment by malcolmepa** [comment]
Hi again,

Attached is the full Log file when I complete LaTeXing my document (the error is listed at Line 120).  As previously stated, I just press <RETURN> to continue.

Cheers,

Malcolm

**Comment by edocevoli** [comment]
Please note that `l3backend-pdftex.def` is a part of `l3backend` package. That said, installing `l3backend` might solve your issue.
