### ISSUE TITLE
AASTeX Update

### ISSUE THREAD

**Issue by mroute** [MiKTeX/miktex-packaging#20]
Dear MiKTeX staff,
Thanks for all of your hard work on this project that so many of us benefit from.

Would it be possible for you to update the AASTeX package with the latest classfile, v6.2?  It is now available from AAS here (http://journals.aas.org/authors/aastex.html).

Thanks,
Matt

**Comment by edocevoli** [comment]
The `aastex` will be updated as soon it is available on CTAN.
