### ISSUE TITLE
leaflet is incorrectly packaged

### ISSUE THREAD

**Issue by mstieben** [MiKTeX/miktex-packaging#200]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The package leaflet is incorrectly included into MiKTeX. 
The current leaflet package, that is downloadable via MiKTeX Console, claims to be version 2.0.b while during compilation the package identifies itself as version 1.1a:
```
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (MiKTeX 20.10) (preloaded format=pdflatex 2020.10.26)  26 OCT 2020 08:27
[...]
("C:\Program Files\MiKTeX 2.9\tex/latex/leaflet\leaflet.cls"
Document Class: leaflet 2015/12/27 v1.1a LaTeX document class (JS,WaS,RN,HjG)
[...]
```
This currently included version fails to compile any document as it seems to conflict with up-to-date dependency packages.
It gets stuck in an infinite loop of appending empty pages, hence, never yielding an intact document.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.
