### ISSUE TITLE
biber 2.15 has troubles with bib-files exceeding 1,3 MB

### ISSUE THREAD

**Issue by tsfg** [MiKTeX/miktex-packaging#201]
The actual version of biber  (2.15) has problems with long bib-Files. 
The actual development version (2.16dev) has solved that issue.

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
This is not a MiKTeX-specific bug and so cannot be fixed by me.

You should wait a few days until the broken package is fixed by the maintainers of the package (provided they are aware of the bug).
