### ISSUE TITLE
ltxtable.sty

### ISSUE THREAD

**Issue by quaatz** [MiKTeX/miktex-packaging#202]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Dear MiKTeX Team,
I just installed the recent MiKTeX version from your website and updated it via the console. Now, the ltxtable.sty is missing. Maybe you can add it again to the packages. It should be part of the carlisle package. But the file is missing. (Documentation ltxtable.pdf is still included.)

Best regards and thanks a lot,
Frederik

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
