### ISSUE TITLE
fltpoint.tex missing / not found by fltpoint.sty

### ISSUE THREAD

**Issue by AlexBadauer** [MiKTeX/miktex-packaging#203]
Hello,

i had to install the new miktex version 20.11 from 2020-11-02. My previous and on another pc with miktex 2.9 perfectly smooth running project now throws an error, that the _fltpoint.tex_  needed in _fltpoint.sty_ was not found. By comparing the two installations I recognized, that neither the file _fltpoint.tex_ nor the folder _C:\Program Files\MiKTeX\tex\generic\fltpoint_ is installed. So I assume it is missing in the package.

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
