### ISSUE TITLE
Update version of TikZlings package

### ISSUE THREAD

**Issue by samcarter** [MiKTeX/miktex-packaging#205]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

MiKTeX currently still has version 0.2 of the TikZlings package, while the current version on CTAN is `0.3 2020-04-22`. Could you please update?

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
