### ISSUE TITLE
Unproper functioning of the amsmath package

### ISSUE THREAD

**Issue by Konstantius** [MiKTeX/miktex-packaging#206]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)
I'm not sure that report now to the proper place, faced the following bug. 
I got a lot of bug and error during compilation of LaTeX which uses `amsmath` package.
After removing and reinstalling the package the pdflatex stopped working at all.
I enclosure here pdflatex.log file.
[pdflatex.log](https://github.com/MiKTeX/miktex-packaging/files/5591424/pdflatex.log)

**Comment by edocevoli** [comment]
Sorry, but this is not a support forum.
