### ISSUE TITLE
keyval missing....

### ISSUE THREAD

**Issue by cooch17** [MiKTeX/miktex-packaging#208]
Just updated to latest keyval package. Appears broken...throws following error message:

(C:\Users\egc\Desktop\egc\text\MikTeX\tex/latex/xkeyval\xkeyval.sty
! I can't find file `xkeyval'.
l.39 ...XKeyValLoaded\endinput\else\input xkeyval 
                                                  \fi
Please type another input file name:

**Comment by edocevoli** [comment]
Duplicate of #207
