### ISSUE TITLE
problem with newtx update

### ISSUE THREAD

**Issue by cooch17** [MiKTeX/miktex-packaging#209]
Applied the most recent update to newtx -- any file that I have that uses it now throws the following error:

Command Line:   dvips.exe "mwe-single-file.dvi"
Startup Folder: C:\Users\me\Desktop\me\text\TeX notes\mwe

This is dvips(k) 2020.1 Copyright 2020 Radical Eye Software (www.radicaleye.com)
' TeX output 2020.11.26:0827' -> mwe-single-file.ps
dvips.exe: ! Couldn't find header file: ntx-ec-tlf.enc

What is interesting is that this also affects any file that uses newpx (the 'Palatino-like' variant). 

If I roll back to the previous version, problem disappears.

**Comment by rafaariza** [comment]
I have fixed it as follows:

1. Download newtx.zip from CTAN [(link)](http://mirrors.ctan.org/fonts/newtx.zip)
2. The folder 'enc' is missing in the MiKTeX 'newtx' package.
3. Extract 'enc' folder from CTAN zip to texmf/fonts/enc/dvips/newtx
4. Refresh file name database and font map files with MiKTeX console.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
