### ISSUE TITLE
xcharter version 1.213

### ISSUE THREAD

**Issue by gerdji** [MiKTeX/miktex-packaging#212]
I installed the package today and it seems that the files in 

> MiKTeX\fonts\enc\dvips\xcharter

 are missing. 
The compiler did throw an error when using xcharter ("cannot open encoding file for reading”)

I manually installed the missing files from CTAN in the above mentioned folder (i had to create the xcharter folder), did a refresh (admin and user)  on the file name database and the font map files and now everything works fine.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
