### ISSUE TITLE
`tools` package has been renamed to `latex-tools`, now appears twice

### ISSUE THREAD

**Issue by DigNative** [MiKTeX/miktex-packaging#214]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The `tools` package has been renamed to `latex-tools` on CTAN around October 17, 2020 and also the paths in the TEXMF root directories for this package changed. In the current MiKTeX package repository, both the old `tools` and the new `latex-tools` packages exist:
* https://miktex.org/packages/tools
* https://miktex.org/packages/latex-tools

Both install the same files in different versions to the TEXMF root directories. As the old `tools` package [does not exist anymore on CTAN](https://ctan.org/pkg/tools), I think the `tools` package is a remnant in the MiKTeX package repository.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.
