### ISSUE TITLE
baskervaldx package is incomplete

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#215]
The baskervaldx package is missing most files needed to use it with pdflatex. According to the package information tfm, map, vf and pfb are all not there. This means that this document doesn't compile with pdflatex:

~~~~
\documentclass{article}
\usepackage{Baskervaldx}
\begin{document}
test
\end{document} 
~~~~

~~~~
! Font T1/Baskervaldx-TLF/m/n/10=Baskervaldx-Reg-tlf-t1 at 10.0pt not loadable:
 Metric (TFM) file not found.
~~~~

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
