### ISSUE TITLE
Problem with gost package

### ISSUE THREAD

**Issue by kia999** [MiKTeX/miktex-packaging#217]
- [+] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)
Recent MikTeX update of the GOST package came with corrupted *.bst files.  They are removed from the last update (2020-12-29) of the package at the CTAN repository (https://www.ctan.org/pkg/gost) due to request of CTAN maintainers. Note that bst files generated by me were included to previous releases of the GOST. This might mean that *.bst files in the recent MikTeX update were generated by MikTeX maintainer from the source file gost.dtx. All bst files distributed with MikTeX contain wrong \endinput command near EOF. Source file gost.dtx on CTAN does not contain this command, so it might be added by a script on MikTeX repository. 

[gost.zip](https://github.com/MiKTeX/miktex/files/5821156/gost.zip)

**Comment by edocevoli** [comment]
I have checked the `.bst` files and they look good. For example, here are the final lines of `gost2003.bst`:

```
EXECUTE {end.bib}

\endinput
%%
%% End of file `gost2003.bst'.
```

**Comment by kia999** [comment]
Christian,

macro \endinput is prohibited in bibtex. Please remove it.

Igor Kotelnikov

Principal Researcher
Budker Institute of Nuclear Physics SB RAS
Lavrentyev Av. 11, Novosibirsk, 630090, Russia
&
Professor of the Department of Plasma Physics
Novosibirsk State University
Pirogov Street 2, Novosibirsk, 630090, Russia

igor.kotelnikov@gmail.com

Tel: +7 383 3294268 (office)

Fax: +7 383 330 71 63
Mobile: +7 913 933 24 84 (WhatsApp, WeChat)


пт, 15 янв. 2021 г. в 23:06, Christian Schenk <notifications@github.com>:

**Comment by edocevoli** [comment]
> Please remove it.

The `.bst` files are generated automatically from the `.dtx` file. I am not quite sure what you want me to do with them. Please advise.

**Comment by edocevoli** [comment]
I don't think that this is a MiKTeX issue. Please fix this up the stream.

**Comment by kia999** [comment]
bst files on my side are generated by running tex on gost.ins or pdflatex on gost.dtx. Their end are quite different from what that came mot miktex update. Here is example of bst file end:

FUNCTION {end.bib}
{ newline$
  "\end{thebibliography}" write$ newline$
}

EXECUTE {end.bib}

%% -------------------------------------------------------------------
%% Copyright 2012-2021 Igor A. Kotelnikov.
%% Copyright 2017      Leonid Sinev.
%% Version 1.2l
%% 
%% Copyright 1996-2005 Maksym Polyakov.
%% Version 2005.08.12
%% 
%% Released under the LaTeX Project Public License v1.3c or later
%% See http://www.latex-project.org/lppl.txt
%% 
%% This work is "maintained" (as per LPPL maintenance status) by
%% Igor A. Kotelnikov.
%% 
%% Current version is 1.2l, 2021.01.16.
%% 
%% Please, send bug report via e-mail: kia999@mail.ru <Igor Kotelnikov>
%% -------------------------------------------------------------------
%% This work consists of the file  gost.dtx
%% and the derived files           gost.ins,
%%                                 gost.pdf,
%%                                 gost*.bst  (8 files),
%%                                 ugost*.bst (8 files),
%%                                 README.md.
%% It also contains a lot of examples (*.tex, *.pdf, *.bib files).
%% -------------------------------------------------------------------
%%
%% End of file `gost2008.bst'.

It is important that it has no \endintup command which rised an error when running bibtex.

**Comment by edocevoli** [comment]
There is an `.ins` file and the normal workflow is to run TeX on the `.ins` file. I would recommend that you fix this upstream by removing the `.ins` file. That should also fix TeX Live (in case the issue is relevant for TeX Live).

**Comment by edocevoli** [comment]
Unfortunately, the packaging factory cannot be easily adjusted for `gost`. For now, I will remove the `gost` package from the repo.
