### ISSUE TITLE
babel-ukrainian is not up-to-date

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#219]
The current version of babel-ukrainian on ctan is 1.4e 2020-10-14.

But miktex still has 

~~~~
XXX\MiKTeX\tex/latex/babel-ukrainian\ukraineb.ldf
Language: ukraineb 2018/04/11 1.4c Ukrainian support for the Babel system
~~~~

This older version clashes with the new babel-russian.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
