### ISSUE TITLE
Error in the installation of the package Stickstoo

### ISSUE THREAD

**Issue by uliken** [MiKTeX/miktex-packaging#223]
When  I compile the following example:
```
\documentclass[10pt,a4paper]{article}
\usepackage[T1]{fontenc}
\usepackage{stickstootext}
\begin{document}
    error
\end{document}
```
 I get the error:
`! LaTeX Error: File `stickstootext.sty' not found.`
The package Stickstoo is installed.
But I'm wondering there are only two files in the package manager of the MiKTeX console:
- Readme
- stickstoo.tpm
So I think that is an error in the update of MiKTeX.
My MiKTeX version is 21.1 from 20 JAN 2021.
[Stickstoo-error.log](https://github.com/MiKTeX/miktex-packaging/files/5843416/Stickstoo-error.log)
[miktex-report.txt](https://github.com/MiKTeX/miktex-packaging/files/5845049/miktex-report.txt)

Thanks for your work
uliken

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
