### ISSUE TITLE
firstaid-dev package is not installed correctly

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#230]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The `firstaid-dev` package is the accompaigning package to `firstaid` for the `latex-dev` formats. It should be handled like other latex-dev packages. 

The package contains three files, which should all got into `tex/latex-dev/firstaid`

Currently miktex installs two of them (`filehook-ltx.sty` and `everysel-ltx.sty`)  into `tex/latex/latex-firstaid-dev` and the central file `latex2e-first-aid-for-external-files.ltx` is missing completly. This means that when using pdflatex-dev the following currently errors as the fix is missing:

~~~~
\documentclass{scrartcl}
\begin{document}
aa
\end{document}
~~~~

gives 

~~~~
! LaTeX Error: Command \footref already defined.
~~~~

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
