### ISSUE TITLE
thuthesis is not up-to-date

### ISSUE THREAD

**Issue by gaotongsh** [MiKTeX/miktex-packaging#232]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The package `thuthesis` on CTAN was updated to 7.1.0 on 2020-10-14, but it's still on 7.0.0 on MikTeX.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
