### ISSUE TITLE
Troubles with package hyperref

### ISSUE THREAD

**Issue by AndreasF60** [MiKTeX/miktex-packaging#234]
I am working on a book using the class KOMA-Script. I have updated my distribution MikTex to version 21. And now I get troubles by compiling to a PDF: The error message is: "Cannot found **pd1enc.def**". I suggest that there is a trouble with the package **hyperref**. Can anybody help to fix my problem?

Greetings
Andreas
a.plihal@gmx.at

**Comment by edocevoli** [comment]
It works for me:

```
pdflatex test.tex
```

No errors. PDF looks okary.
