### ISSUE TITLE
ctex package installation looks wrong

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#236]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

ctex seems to have reorganized some files and the update errored. I deleted the folder `tex/generic/ctex` manually and then reinstalled and this worked, but the result looks wrong. In texlive `tex/generic/ctex` contains three files and folder `zhmap` with more files (but the dates are older so I'm not sure if this the new state):

![image](https://user-images.githubusercontent.com/4047173/111970755-e8144900-8afb-11eb-8b9a-dfa0aab7b82f.png)

~~~~
26.02.2021  09:50    <DIR>          ..
26.02.2021  09:50             4.229 ctex-zhmap-adobe.tex
26.02.2021  09:50             4.158 ctex-zhmap-fandol.tex
26.02.2021  09:50             5.515 ctex-zhmap-founder.tex
26.02.2021  09:50             4.607 ctex-zhmap-mac.tex
26.02.2021  09:50             4.112 ctex-zhmap-ubuntu.tex
26.02.2021  09:50             5.817 ctex-zhmap-windows.tex
~~~~

In miktex I have instead of the folder a *file*  `zhmap` (its content seems to be `ctex-zhmap-fandol.tex`)

![image](https://user-images.githubusercontent.com/4047173/111970679-d0d55b80-8afb-11eb-8293-189a002555f5.png)

The dtx seems to indicate that all files should be simply in `tex/generic/ctex`:

~~~~
    \usedir{tex/generic/ctex}
    \file{ctex-spa-make.tex}               {\from{\jobname.dtx}{spa,make}}
    \file{ctex-spa-macro.tex}              {\from{\jobname.dtx}{spa,macro}}
    \file{ctex-zhmap-adobe.tex}            {\from{\jobname.dtx}{zhmap,adobe}}
    \file{ctex-zhmap-fandol.tex}           {\from{\jobname.dtx}{zhmap,fandol}}
    \file{ctex-zhmap-founder.tex}          {\from{\jobname.dtx}{zhmap,founder}}
    \file{ctex-zhmap-mac.tex}              {\from{\jobname.dtx}{zhmap,mac}}
    \file{ctex-zhmap-ubuntu.tex}           {\from{\jobname.dtx}{zhmap,ubuntu}}
    \file{ctex-zhmap-windows.tex}          {\from{\jobname.dtx}{zhmap,windows}}
~~~~

**Comment by hotbbs** [comment]
It is a mistake in CTeX, now ,it has been corrected, see  https://github.com/CTeX-org/ctex-kit/issues/566

**Comment by muzimuzhi** [comment]
related: https://github.com/MiKTeX/miktex/issues/756

**Comment by stone-zeng** [comment]
I have uploaded the fixed tds to CTAN, and TeX Live has updated it ([58583](https://www.tug.org/svn/texlive?view=revision&revision=58583)).

**Comment by edocevoli** [comment]
Thank you, I have updated `ctex` by unpacking `ctex.tds.zip`.

Please check for updates tomorrow.
