### ISSUE TITLE
File incomplete

### ISSUE THREAD

**Issue by hakcat** [MiKTeX/miktex-packaging#237]
Both 32 and 64 bit Windows exe files' downloads are failing. File incomplete message shown by chrome.
Download page: https://miktex.org/download

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
