### ISSUE TITLE
Experimental patterns for ngerman and german don't work

### ISSUE THREAD

**Issue by erik-f** [MiKTeX/miktex-packaging#238]
Similar to #233, I get the error
```
oberdiek\hyphsubst.sty:227: Package hyphsubst Error: Unknown pattern `ngerman-x-latest'.
```
with the following MWE.
```latex
\documentclass{article}

\usepackage[T1]{fontenc}
\usepackage[ngerman]{babel}
\usepackage[ngerman=ngerman-x-latest]{hyphsubst}

\begin{document}
    Test
\end{document}
```
As opposed to #233, the patterns do show in my `languages.ini`:
```
[ngerman-x-2021-02-26]
loader=dehyphn-x-2021-02-26.tex
lefthyphenmin=2
righthyphenmin=2
synonyms=ngerman-x-latest
patterns=hyph-de-1996.pat.txt
hyphenation=hyph-de-1996.hyp.txt
```
The package `dehyph-exptl` is installed, but it didn't install automatically when I tried to compile the above code.

Again, with TeX Live everything works as expected.
This is a single user installation on Windows 10.

**Comment by edocevoli** [comment]
I was not able to reproduce it. Please make sure that you have the latest updates and that `dehyph-exptl` is installed. Also make sure that format files are up-to-date.

**Comment by erik-f** [comment]
I uninstalled my MiKTeX installation to try this again from scratch. These are the steps I took:

1. Install the latest MiKTeX with the installer for Windows 10.
2. Update packages (102 updates for me).
3. Update fndb and font map files.
4. Compile the above MWE with `pdflatex test.tex`.
5. Confirm automatic installation of the two packages `babel-german` and `infwarerr`. The compilation fails with the above error.
6. Install `dehyph-exptl` manually.
7. Update fndb and font map files to be sure.
8. Compile again with `pdflatex test.tex`. Again, the compilation failed with `! Package hyphsubst Error: Unknown pattern `ngerman-x-latest'.`.

Am I missing anything?

**Comment by efaulhaber** [comment]
I used TeX Live for the past year because of this, but I decided to give MiKTeX another try.
I installed MiKTeX today and encountered the exact same problem again.

**Comment by koppor** [comment]
@efaulhaber Same experience here. `MiKTeX-pdfTeX 4.19 (MiKTeX 24.4)`. I fired up a Windows 10 [Sandbox}(https://learn.microsoft.com/de-de/windows/security/application-security/application-isolation/windows-sandbox/windows-sandbox-overview) and did the steps there.

I tried following change:

```diff
-\usepackage[ngerman=ngerman-x-latest]{hyphsubst}
+\babelprovide[hyphenrules=ngerman-x-latest]{ngerman}
```

However, this results in following output:

```
Package babel Warning: Requested 'hyphenrules' for 'ngerman' not found:
(babel)                ngerman-x-latest.
(babel)                Using the default value. Reported on input line 5.
```

According to Settings > Languages, it should be available:

![image](https://github.com/user-attachments/assets/d8db1174-8aa1-45ee-8b23-dd9497692296)

(Idea of that configuration location stems from https://github.com/MiKTeX/miktex-packaging/issues/286).
