### ISSUE TITLE
Discrepancy between package "dtk" currently distributed in MiKTeX and version on CTAN 

### ISSUE THREAD

**Issue by vrws** [MiKTeX/miktex-packaging#239]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)
**dtk.cls**
  MiKTeX  \DTKversion{2.08d}  \DTKversiondate{2019/10/15}	
  CTAN    \DTKversion{2.08h}  \DTKversiondate{2019/12/04}

**dtk-extern.sty**
  MiKTeX  2019/10/11 v0.15
  CTAN    2020/02/07 v0.16

**dtk-full.clo**
  MiKTeX  2019/04/22 v0.1m
  CTAN    2019/10/25 v0.1n

**dtk-logos.sty**
  MiKTeX  2019/09/14 v. 1.08
  CTAN    2020/02/02 v. 1.10

**dtk-new-engines.clo**
  MiKTeX  2016/05/17 v0.1f
  CTAN    2016/05/17 v0.1f 
  _same version number but not documented change in_ 
  ```    \setmonofont{AnonymousPro}[…, Ligatures = ResetAll, …]```

**dtk-url.sty**
  MiKTeX  2019/07/29 v1.3
  CTAN    2019/12/04 v1.5

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
