### ISSUE TITLE
Updating miktex doesn't work due to "Failed sending data to peer"

### ISSUE THREAD

**Issue by ShramanJain** [MiKTeX/miktex-packaging#240]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

[New Text Document (2).txt](https://github.com/MiKTeX/miktex-packaging/files/6299745/New.Text.Document.2.txt)
[miktex-report.txt](https://github.com/MiKTeX/miktex-packaging/files/6299749/miktex-report.txt)
[miktex-console.log](https://github.com/MiKTeX/miktex-packaging/files/6299750/miktex-console.log)

Updating miktex failing on a new installation with error code 55 on one of the update files. Logs and error report attached

**Comment by edocevoli** [comment]
This seems to be an issue with your internet connection.
