### ISSUE TITLE
Ubuntu archive key expired

### ISSUE THREAD

**Issue by moskalenko** [MiKTeX/miktex-packaging#241]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

W: Failed to fetch http://miktex.org/download/ubuntu/dists/bionic/InRelease  The following signatures were invalid: EXPKEYSIG 277A7293F59E4889 MiKTeX Packager <packager@miktex.org>

apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
Executing: /tmp/apt-key-gpghome.S029L6xhlv/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
gpg: key 277A7293F59E4889: 1 signature not checked due to a missing key
gpg: key 277A7293F59E4889: "MiKTeX Packager <packager@miktex.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

**Comment by ArvidvdB** [comment]
I have a similar problem for the focal release.

W: Failed to fetch http://miktex.org/download/ubuntu/dists/focal/InRelease  The following signatures were invalid: EXPKEYSIG 277A7293F59E4889 MiKTeX Packager <packager@miktex.org>

Also tried the apt-key command, but no luck so far.

**Comment by yemeng77** [comment]
Looks like that key has expired on 2021-04-27.

**Comment by SvenMoenig** [comment]
I have the same problem on Debian 10

> W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://ctan.space-pro.be/tex-archive/systems/win32/miktex/setup/deb buster InRelease: The following signatures were invalid: EXPKEYSIG 277A7293F59E4889 MiKTeX Packager <packager@miktex.org>
> W: Failed to fetch http://miktex.org/download/debian/dists/buster/InRelease  The following signatures were invalid: EXPKEYSIG 277A7293F59E4889 MiKTeX Packager <packager@miktex.org>
> W: Some index files failed to download. They have been ignored, or old ones used instead.
>

**Comment by edocevoli** [comment]
Thank you for reporting the issue. The key has been renewed. Please run the following command to get it:

```sh
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
```
