### ISSUE TITLE
outdated geometry.cfg in the xetex package

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#243]
The xetex package contains a geometry.cfg which is installed in tex/xelatex/xetexconfig. 

This geometry.cfg (from 2006) is outdated and forces geometry to use the pdftex driver. It should be deleted, today geometry is able to detect xetex without problems.

~~~~
\documentclass{article}
\usepackage{geometry}

\makeatletter \show \Gm@driver %show pdftex because of the cfg, should be empty

\begin{document}
blub

\end{document}
~~~~

gives when compiled with xelatex

~~~~
(C:\Users\Nililand2020\AppData\Local\Programs\MiKTeX 2.9\tex/xelatex/xetexconfi
g\geometry.cfg))
> \Gm@driver=macro:
->pdftex.
l.18 \makeatletter \show \Gm@driver
                                    %show pdftex because of the cfg, should ...

...
*geometry* detected driver: pdftex
~~~~

**Comment by edocevoli** [comment]
Thank you, I have removed the file. Please check for updates tomorrow.
