### ISSUE TITLE
[pgf-spectra] two missing files

### ISSUE THREAD

**Issue by Mo-Gul** [MiKTeX/miktex-packaging#245]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

It seems that in the package [`pgf-spectra`](https://www.ctan.org/texarchive/graphics/pgf/contrib/pgf-spectra) v2.1 (at least) the files

- spectra.data.LSE.tex
- spectra.data.NIST.tex

are missing.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
