### ISSUE TITLE
[pgf] Missing pgfmanual.pdf

### ISSUE THREAD

**Issue by nignasi** [MiKTeX/miktex-packaging#246]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

I think that last package for `pgf` doesn't contain the `pgfmanual.pdf` file

**Comment by edocevoli** [comment]
Thank you. The documentation is now in `pgf__doc`. Also see:

- https://miktex.org/announcement/companion-packages
- https://github.com/MiKTeX/miktex/issues/844
