### ISSUE TITLE
Documents missing

### ISSUE THREAD

**Issue by elfsoft2000** [MiKTeX/miktex-packaging#247]
Many but not all of my document files have disappeared recently.  For example, C:\Program Files\MiKTeX 2.9\doc\bibtex is empty but C:\Program Files\MiKTeX 2.9\doc\asymptote still has contents (cncluding assymtote.pdf).

**Comment by elfsoft2000** [comment]
My last update for bibtex was dated 6/11/2021.

**Comment by edocevoli** [comment]
Thank you. The documentation is now in `PACKAGE__doc`. Also see:

- https://miktex.org/announcement/companion-packages
- https://github.com/MiKTeX/miktex/issues/844
