### ISSUE TITLE
Bad Pathing for BibLatex

### ISSUE THREAD

**Issue by eskemojoe007** [MiKTeX/miktex-packaging#25]
I recently installed MiKTeX 2.9.6637 and package `biblatex` version 3.11 (I am using bibtex 0.99d).  This installs many packages and files, but principally, the `.bst` file is installed to `texmf/bibtex/bst/biblatex/biblatex.bst` for me this ends up being `C:\Users\<USERNAME>\AppData\Local\Programs\MiKTeX 2.9\bibtex\bst\biblatex`.

To Recreate this...I created a single article file `article.tex`:
```latex 
\documentclass{article}
\usepackage[backend=bibtex]{biblatex}
\addbibresource{sources.bib}
\begin{document}
Lets try a citation \cite{IEEE}
\printbibliography
\end{document}
```

And a single `sources.bib` file:
```latex
@report{IEEE,
AUTHOR = {IEEE Power Engineering Society},
TITLE = {IEEE Standard Definitions for Use in Reporting Electric Generating Unit Reliability, Availability, and Productivity},
TYPE={IEEE},
NUMBER={IEEE Std 762-2006},
YEAR = {2006}
}
```

Running in the console:
`pdflatex article.tex`
`bibtex article.aux`

Results in 
```
This is BibTeX, Version 0.99d (TeX Live 2015/Cygwin)
The top-level auxiliary file: article.aux
I couldn't open style file biblatex.bst
---line 3 of file article.aux
 : \bibstyle{biblatex
 :                   }
I'm skipping whatever remains of this command
I found no style file---while reading file article.aux
(There were 2 error messages)
```

It is unable to locate the `biblatex.bst` even though it is installed and in the `texmf` path.  Copying the `biblatex.bst` to the local repository solves the issue with the new output

```
This is BibTeX, Version 0.99d (TeX Live 2015/Cygwin)
The top-level auxiliary file: article.aux
The style file: biblatex.bst
Database file #1: article-blx.bib
Database file #2: sources.bib
Biblatex version: 3.8
```

Running the standar pdflatex, bibtex, pdflatex, pdflatex works great when the `biblatex.bst` is copied into the local repository.

![image](https://user-images.githubusercontent.com/22135005/38630272-78ac91d4-3d84-11e8-99b1-6c2294ec9441.png)

Shouldn't it be able to find the `biblatex.bst` in the texmf path without any intervention?

**Comment by edocevoli** [comment]
Thank you for the complete test case. Anyway, running `pdflatex article.tex` works for my, i.e., I cannot reproduce your problem.

**Comment by eskemojoe007** [comment]
The `pdflatex article.tex` works, its the `bibitex article.aux` that doesn't work.

**Comment by eskemojoe007** [comment]
Figured out my issue just for the future.  I also had cygwin installed on my windows machine and added to the path.  Running `where bibtex` showed that I had two versions.  

'''
C:\Apps\cygwin\bin\bibtex.exe
C:\Users\<USERNAME>\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\bibtex.exe
'''

Removing the cygwin version, or putting first in the priority list solved everything.  Not a bug.  Sorry!
