### ISSUE TITLE
Issue with multiple tikz-swigs package entries in list

### ISSUE THREAD

**Issue by tsrichardson** [MiKTeX/miktex-packaging#250]
For some reason in the list of packages there are three entries associated with the tikz-swigs:
[tikz-swigs](https://miktex.org/packages/tikz-swigs)
[tikz-swigs__doc](https://miktex.org/packages/tikz-swigs__doc)
[tikz-swigs__source](https://miktex.org/packages/tikz-swigs__source)

but I think there really only needs to be one link as on [CTAN tikz-swigs](https://ctan.org/pkg/tikz-swigs).
Is there a way to have these combined?

**Comment by edocevoli** [comment]
Thank you, this is by design. See https://miktex.org/announcement/companion-packages

**Comment by tsrichardson** [comment]
Thank you for the clarification! (As the author of the package I was just concerned in case I had set something up the wrong way.)
