### ISSUE TITLE
Kernel Error Using Font Spec

### ISSUE THREAD

**Issue by mablume** [MiKTeX/miktex-packaging#253]
I am getting a kernel error using Fontspec package. 
expl3-code.tex
!Undefined Control Sequence. 
<argument> \msg_new:nnnn
{kernel}{no-elapsed-time}{ No clock detected. 

I have updated the packages multiple times and uninstalled and reinstalled Miktex. How do I fix the issue, I need to use font spec to change the font. 
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment]
I was not able to reproduce the bug with your mininal test case.
