### ISSUE TITLE
Problem with xeletax

### ISSUE THREAD

**Issue by BruceBurlton** [MiKTeX/miktex-packaging#255]
Recently (probably last major update) I have a problem compiling using xelatex when pstricks code is included.  The "image" is not drawn.  All that is produced is a collection of characters (which are in the image) superimposed on one another.
The enclosed .tex file will not compile properly under xelatex, but will compile using latex => dvips =>ps2pdf
Larger and more complicated files will not compile using the later process, but I think that issue is with the image format I used for some of my pictures
These files are used for a lecturer course at Carleton University

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
