### ISSUE TITLE
Package zlmtt not up to date

### ISSUE THREAD

**Issue by user227621** [MiKTeX/miktex-packaging#258]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The latest version of the `zlmtt` package is not available via MiKTeX:

MiKTeX: 2014/06/28 v1.01
CTAN: 2019/06/11 v1.02

**Comment by edocevoli** [comment]
Upgraded to v1.03
