### ISSUE TITLE
Package acrotex-js: missing acrotex-js.sty

### ISSUE THREAD

**Issue by tstone-1** [MiKTeX/miktex-packaging#259]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Calling the package `acrotex-js` and trying to compile will throw:

```
Package aeb_pro Warning: The acrotex-js package is required.
(aeb_pro)                Before continuing, install this package,
(aeb_pro)                read the documentation, and place
(aeb_pro)                aeb_pro.js in the expected folder .


! LaTeX Error: File `acrotex-js.sty' not found.
```

I do understand that installation of `aeb_pro.js` ([click](https://mirror.physik.tu-berlin.de/pub/CTAN/macros/latex/contrib/acrotex-js/js-files/aeb_pro.js)) according to `install_jsfiles.pdf` ([click](https://ftp.gwdg.de/pub/ctan/macros/latex/contrib/acrotex-js/docs/install_jsfiles.pdf)) is necessary. In my case, the .js file had to be copied to `C:\Users\<USERNAME>\AppData\Roaming\Adobe\Acrobat\Privileged\DC\JavaScripts`. However, in order to get the compilation work, I also had to create a folder `C:\Users\<USERNAME>\AppData\Local\Programs\MiKTeX\tex\latex\acrotex-js` and put a file `acrotex-js.sty` in it containing

```
\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{acrotex-js}
  [acrotex-js]
\RequirePackage{xkeyval}
\DeclareOptionX*{\PassOptionsToPackage{\CurrentOption}{aeb_pro}}
\ProcessOptionsX\relax
\endinput
```

I have next to no idea what I did here, but compilation succeeded afterwards. Shouldn't the second part of the installation as described not be done automatically?

**Comment by edocevoli** [comment]
Thank you, I have added the package which contains just the `acrotex-js.sty` file (generated from the `.dtx` file:

```tex
\NeedsTeXFormat{LaTeX2e}[1997/12/01]
\ProvidesPackage{acrotex-js}
 [2021/06/24 v1.2 acrotex-js: A library of JavaScript files (dps)]
\endinput
```

This will be available with the next MiKTeX update.
