### ISSUE TITLE
piccorr.sty exists twice, one version is faulty

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#26]
piccorr.sty exists twice in my miktex:

~~~~~
MiKTeX2.9/tex/generic/pictex/piccorr.sty
MiKTeX2.9/tex/latex/ltxmisc/piccorr.sty
~~~~~

The version in latex/ltxmisc is faulty: a brace is misplaced (I compared with the version in texlive) and gives errors if one use \! in math:

```
\documentclass{article}
\usepackage{pictexwd}
\begin{document}
$a\! b$
\end{document}
 ```

Imho the version in lxtmisc can be safely deleted.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.
