### ISSUE TITLE
SSL connect error                                                                            code="35", url="https://api2.miktex.org/hello"

### ISSUE THREAD

**Issue by VenancioB** [MiKTeX/miktex-packaging#263]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

**Comment by VenancioB** [comment]
When I try to update Miktex or download packages this image pops out.
![imagen](https://user-images.githubusercontent.com/65828405/143780291-bbaa0e30-4c42-4e42-9953-d2d7df962577.png)

**Comment by VenancioB** [comment]
I have no idea what to do.

**Comment by edocevoli** [comment]
Thank you. It seems that your Windows system setup and/or your network infrastructure is not supported by MiKTeX. I cannot solve this issue, sorry.

**Comment by VenancioB** [comment]
but it used to work, normally, many packages were installed by that way.
