### ISSUE TITLE
pdfendlink ended up in different level

### ISSUE THREAD

**Issue by aleks2709** [MiKTeX/miktex-packaging#264]
i started to work with large projects and very often I get error that pdfendlink ended up in different nesting level. if package babel is included in project, I do not see this error. When application gets this error it crashes According to description it happens when label in the border of two pages. Sometimes macro \newline may help. But small change in the code may resume error, the same code with package Babel never sees this error. the tracing shows that both startlink and endlink are on the same level and there is no clear reason for this error. Maybe it is mind to remove this analisys
![PdfLatex](https://user-images.githubusercontent.com/22059064/145131361-705128af-819e-4c23-9bef-0d97ffcbfa73.jpg)

**Comment by edocevoli** [comment]
Please note that this is the wrong repository.
