### ISSUE TITLE
Problem with eurosym.map

### ISSUE THREAD

**Issue by petiard** [MiKTeX/miktex-packaging#266]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

My config : Windows10 pro, MiKTeX updated.

It seems than eurosym.map is not in the right directory, or mkfntmap has changed:

eurosym.map is actually in MiKTeX/dvips/eurosym/ and that map is not included by mkfntmap, but if I put eurosym.map in  MiKTeX\fonts\map\dvips\eurosym (and refresh FNDB), then eurosym.map is included by mkfntmap.

I think it's a change in mkfntmap (?)

Best regards

François Pétiard

**Comment by edocevoli** [comment]
Yes, mkfntmap doesn't search in the dvips directory. The eurosym map file must be moved to `fonts/map/...`. This will be fixed with the next update.
