### ISSUE TITLE
Wrong file on https://ftp.eq.uc.pt/software/TeX/systems/win32/miktex/tm/packages/

### ISSUE THREAD

**Issue by rafaariza** [MiKTeX/miktex-packaging#267]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)
  
![image](https://user-images.githubusercontent.com/64159271/147622164-2c9e7d60-82ad-425b-b50d-d6394808fef9.png)
![image](https://user-images.githubusercontent.com/64159271/147622176-e16ce8c0-e1ec-43ec-8972-8284e009c6ef.png)

FiraMath package is outdated on MikTeX's packages directory but it's showed in MikTeX Console as up to date:
![image](https://user-images.githubusercontent.com/64159271/147622283-d2aedb3e-5c84-4a38-a79d-e0421e78be1d.png)

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
