### ISSUE TITLE
Move duckuments' example-image-duck to path searched by kpsewhich

### ISSUE THREAD

**Issue by moewew** [MiKTeX/miktex-packaging#27]
The example file **`example-image-duck.tex` and**  the compiled/derived file **`example-image-duck.pdf`  of the `duckuments` package** currently living in `\doc\latex\duckuments` **should be moved to** a path searched by `kpsewhich` - ideally **`\tex\latex\duckuments`**. The two files are similar in use to the example images of the `mwe` package that live in `\tex\latex\mwe`.

Ideally
```latex
\documentclass[a4paper]{article}

\usepackage{duckuments}

\begin{document}
\blindduck
\end{document}
```
would compile out of the box. On my system it complains about
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! duckuments error: "missing-file"
! 
! The file `example-image-duck.pdf` can't be found. Make sure to create it by
! compiling example-image-duck.tex at least once.
! 
! See the duckuments documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
```
That error goes away if I move `example-image-duck.pdf` from `\doc\latex\duckuments` to `\tex\latex\duckuments` and refresh the file name database.

**Comment by edocevoli** [comment]
Thank you, I will move `example-image-duck.pdf` into a directory searched by LaTeX.

**Comment by moewew** [comment]
Thank you very much. The MWE works as expected with the update from this morning.
