### ISSUE TITLE
Biber biber-darwin-x86_64 outdated

### ISSUE THREAD

**Issue by moewew** [MiKTeX/miktex-packaging#270]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

While all other Biber packages are at version 2.17 now, according to https://miktex.org/packages/biber-darwin-x86_64 the Darwin binary is still at 2.16. This causes errors like https://tex.stackexchange.com/q/634517/35864 for MikTeX users on Mac OS. There are Mac OS binaries on CTAN (https://ctan.org/tex-archive/biblio/biber/binaries).

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by AleksejsN** [comment]
> Thank you, this has been fixed. Please check for updates tomorrow.

Hi! Sorry if it's a lame question. I am new to all of this. When you say updates, will it be an update of the MikTex, or do I have to download some new software/packages?

**Comment by edocevoli** [comment]
It will be a MiKTeX package update. Tomorrow, MiKTeX Console will offer the new Biber binary package, if you "Check for updates".
