### ISSUE TITLE
Checking for Updates [Stuck]

### ISSUE THREAD

**Issue by humam2104** [MiKTeX/miktex-packaging#273]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)
The MikTex Console is stuck on: Checking for Updates
![image](https://user-images.githubusercontent.com/41898465/156702848-cde8c527-0afb-4f99-bf1f-4f1f3f36ea17.png)
I've tried a fresh install but it didn't work.

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.

**Comment by humam2104** [comment]
The thread is updated to contain the requirements. Thanks.

**Comment by edocevoli** [comment]
Thank you. It seems that MiKTeX Console cannot access downloaded files. Seems that a 3rd party component (e.g., malware) has taken control over the file system. I would recommend that you scan your system with a malware detection tool.
