### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by walbers** [MiKTeX/miktex-packaging#274]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

I tried the how to directions listed here https://miktex.org/howto/deploy-miktex but get an error:
```bash
.\miktexsetup_standalone --verbose --local-package-repository=C:\temp\miktex --package-set=complete download this is MiKTeX Setup Service 4.3 (MiKTeX 21.7)
starting downloader...
miktexsetup_standalone: The remote package repository is outdated. You have to choose another repository.
miktexsetup_standalone: Data: url="https://mirror.las.iastate.edu/tex-archive/systems/win32/miktex/tm/packages/"
```

**Comment by edocevoli** [comment]
> The remote package repository is outdated. You have to choose another repository

**Comment by walbers** [comment]
@edocevoli I just copied these directions from the site. You may want to update the documentation.

**Comment by edocevoli** [comment]
Ah yes, sorry. The chosen repository is outdated, so I would recommend that you wait until tomorrow.
