### ISSUE TITLE
Update GPL Ghostscript for Windows

### ISSUE THREAD

**Issue by gamma-2017** [MiKTeX/miktex-packaging#275]
It looks like https://miktex.org/packages/miktex-ghostscript-bin still uses a far outdated (more than 3 years old) GPL Ghostscript for Windows. This is tremendously annoying for certain functionalities.

It would be really, really nice if that could be updated.

**Comment by gamma-2017** [comment]
I tested as in [StackExchange note](https://tex.stackexchange.com/questions/588010/annoying-black-color-appears-on-beamer-block-after-some-edits/636363?noredirect=1#comment1585928_636363)  and also tried proposals from [Issue 218](https://github.com/MiKTeX/miktex-packaging/issues/218).  With cygwin gs, ps2pdf I obtained a PDF reporting "GPL Ghostscript 9.54.0", yet still with the same problem.

**Comment by edocevoli** [comment]
Thank you, so it seems that this is not a MiKTeX related issue? 

> with the same problem.

What is the problem?

**Comment by gamma-2017** [comment]
Check in [StackExchange answer](https://tex.stackexchange.com/a/593207/65377).  There is a minimal example that should produce shadows. Yet, it shows gray or black boxes instead. Actually, with my MiKTeX installation it shows black boxes for both overlays. So I think it is MiKTeX related. I'd see this as a test-case, but I cannot verify it in other installations than MiKTeX.

The out-of-date problematic is independently problematic, of course.

**Comment by u-fischer** [comment]
the example on tex.sx works for me if I use ps2pdf from a current texlive, but it fails in miktex. So it is quite certainly due to the outdated ghostscript. 

I can't get miktex to use an external ghostscript with ps2pdf.  gswin64c reports 9.55

~~~~
C:\Users\Nililand2020\Documents\Tests>gswin64c --help
GPL Ghostscript 9.55.0 (2021-09-27)
~~~~

but if I call ps2pdf after uninstalling the miktex package I get

~~~~
C:\Users\Nililand2020\Documents\Tests>ps2pdf test-utf8.ps
Der Befehl "mgs.exe" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
~~~~

**Comment by edocevoli** [comment]
It should be possible to "turn off" MiKTeX's Ghostscript via a configuration setting:

```
set MIKTEX_PREFERMIKTEXGHOSTSCRIPT=no
```

**Comment by gamma-2017** [comment]
Yes, I tried that (via github [Issue 218](https://github.com/MiKTeX/miktex-packaging/issues/218)) even if it would only circumvent the problem rather than solving it. It did not work for me, same as for [u-fischer above](https://github.com/MiKTeX/miktex-packaging/issues/275#issuecomment-1062869018). Instead, I called ps2pdf as delivered by cygwin which uses Ghostsrcipt 9.54 [this is noted in the PDF], as [reported above](https://github.com/MiKTeX/miktex-packaging/issues/275#issuecomment-1062838188). With no different effect, actually.

Maybe there is --apart from the outdated gs-- another problem hidden in the tex->dvi compilation? I cannot tell because I have no direct dvi viewer these days. Well, there is yap - it reports that it calls gswin64c now. Which also shows black boxes on both in the result.

**Comment by agrahn** [comment]
> Yes, I tried that (via github [Issue 218](https://github.com/MiKTeX/miktex-packaging/issues/218)) even if it would only circumvent the problem rather than solving it. It did not work for me, same as for [u-fischer above](https://github.com/MiKTeX/miktex-packaging/issues/275#issuecomment-1062869018). Instead, I called ps2pdf as delivered by cygwin which uses Ghostsrcipt 9.54 [this is noted in the PDF], as [reported above](https://github.com/MiKTeX/miktex-packaging/issues/275#issuecomment-1062838188). With no different effect, actually.

After changing or setting a new environment variable it may be necessary to reboot/re-login in order to take effect. Did you try this?

**Comment by gamma-2017** [comment]
No need to do that since I have called /usr/bin/ps2pdf directly, and verified that it was the correct version by checking in the produced PDF that it contained "Ghostscript 9.54".

**Comment by gamma-2017** [comment]
Any news on this?

**Comment by edocevoli** [comment]
This bug currently has a low priority because a workaround is available.

**Comment by gamma-2017** [comment]
Well, none that works for me.
Additionally, this may eventually be a security issue if you do not follow the updates of imported software.
After all this is on your list for a long time already.
I'd be pleased (in view of all these aspects) to see its priority increased.

**Comment by gamma-2017** [comment]
The problem persists.
