### ISSUE TITLE
IEEEtran package missing bst and bib files

### ISSUE THREAD

**Issue by moewew** [MiKTeX/miktex-packaging#278]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The MikTeX `ieeetran` package appears to only include `IEEEtran.cls` and is missing all the `.bst` files from https://www.ctan.org/tex-archive/macros/latex/contrib/IEEEtran/bibtex. AFAICS those files are not available in any MikTeX package.

Note that the `.bib` files `IEEEfull.bib` and `IEEEabrv.bib` should also be available in run-time, but aren't.

Consequently
```latex
\documentclass[british]{article}
\usepackage[T1]{fontenc}
\usepackage{babel}

\begin{filecontents}{\jobname.bib}
@book{elk,
  author    = {Anne Elk},
  title     = {A Theory on Brontosauruses},
  year      = {1972},
  publisher = {Monthy \& Co.},
  location  = {London},
}
@article{moore,
  author  = {Moore, Gordon E.},
  title   = {Cramming More Components Onto Integrated Circuits},
  journal = IEEE_J_PROC,
  year    = 1998,
  volume  = 86,
  number  = 1,
  pages   = {82-85},
}
\end{filecontents}


\begin{document}
Lorem \cite{elk,moore}

\bibliographystyle{IEEEtran}
\bibliography{IEEEabrv,\jobname}
\end{document}
```
won't compile with working citations in MikTeX.

In TeX Live the files are present in the `ieeetran` package (https://www.tug.org/svn/texlive?view=revision&revision=59672).

**Comment by paultjevdh** [comment]
Hi,
I experience the same issue: after updating miktex, IEEEtran.bst cannot be found any more.
For some reason ieeetran version 1.8b has been repackaged for miktex on March 29th. This is strange, since on CTAN it hasn't changed since 2015 (also version 1.8b)
Best regards,
Paul

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
