### ISSUE TITLE
hyperref -- Version Mismatch

### ISSUE THREAD

**Issue by kramerfan2fla2022** [MiKTeX/miktex-packaging#279]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Hi,

I keep getting the same error when I typeset any documents using hyperref.

! Package hyperref Error: Version mismatch!
(hyperref)                * 2012/11/06 v6.83m: hyperref.sty
(hyperref)                * 2022-02-21 v7.00n: hpdftex.def.

I have tried removing the hyperref package via the MiKTeX package manager and reinstalling it. I have also tried reinstalling it by running a file that calls for it but the error persists.

Is there any way to eliminate this error?

Thank you,

Denise L. Marks

**Comment by edocevoli** [comment]
Seems you have an outdated `hyperref.sty` on your disk. You can run `kpsewhich --all hyperref.sty` in order to find it.

**Comment by kramerfan2fla2022** [comment]
This issue should not be closed. I believe that the suggested command is for Linux, not Windows. I have tried uninstalling and reinstalling the hyperref package using the MiKTeX installer without success.
________________________________

**Comment by ivankokan** [comment]
@kramerfan2fla2022 Can you prepare a MWE and provide its full log?

**Comment by edocevoli** [comment]
@kramerfan2fla2022 please be so kind read my comment above. For your convenience:

> Seems you have an outdated `hyperref.sty` on your disk.

Your log file shows this:

```
C:/LocalTeXMF\tex/latex/misc/Krantz_EditedBook_v1.18\hyperref.sty
```

This should give you enough info to investigate. Unfortunately, this is an issue tracker and not a support forum, i.e., I can give you more assistance.
