### ISSUE TITLE
Failed to run "xelatex notebook.tex -quiet" command: Error: /undefined in GIF89a� Operand stack:

### ISSUE THREAD

**Issue by Muhammad-Kaleem-Ullah** [MiKTeX/miktex-packaging#283]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)
Hi everyone!
I'm trying to convert my Jupiter Notebook's code into a PDF file but I got the following error message and I got stuck here.
First it asks to change "attachment keyword" in inserting images script. After fixing that it ran into following error which I thought may be due to inserting GIF into markdown, but after removing the script of inserting it, it again triggered the same error. However, LaTex works perfectly that it doesn't generate any typo in my notebook, just getting error when trying to convert Jupyter Notebook's file into PDF.

Here is the error that occurs:

```
500 : Internal Server Error
The error was:

nbconvert failed: PDF creating failed, captured latex output:
Failed to run "xelatex notebook.tex -quiet" command:
Error: /undefined in GIF89a�
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   2015   1   3   %oparray_pop   2014   1   3   %oparray_pop   1998   1   3   %oparray_pop   1884   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--
Dictionary stack:
   --dict:975/1684(ro)(G)--   --dict:0/20(G)--   --dict:78/200(L)--
Current allocation mode is local
Current file position is 9
MiKTeX GPL Ghostscript 9.25: Unrecoverable error, exit code 1

dvipdfmx:fatal: pdf_link_obj(): passed invalid object.

No output PDF file written.

Sorry, but xelatex did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:\Users\www\AppData\Local\MiKTeX\miktex\log\xelatex.log
```

Please help me.
Thanks.

**Comment by edocevoli** [comment]
I cannot reproduce the issue with the given information and so I cannot say what goes wrong.
