### ISSUE TITLE
arabtex issues after recent MiKTeX update (6/12/2022)

### ISSUE THREAD

**Issue by ihesham** [MiKTeX/miktex-packaging#284]
Just today after the latest update of [MiKTeX][1] (6/12/2022) on WIN10/TeXstudio platform, the [arabtex][2] package (seemingly included in that update) stopped working altogether. 

Here's a MWE:

    \documentclass[a4paper,10pt]{article}
    \usepackage{arabtex}
    \usepackage{utf8}
    \begin{document}
    %
    \setcode{utf8}
    Here is the word ``Arabic'' written in Arabic:  \<العربية>. You can also use the command \verb|\RL{arabic text}| like this: \RL{العربية}.
    
    Here is a section in Arabic. Computer:
    %
    \begin{RLtext}
    يشير إلى أي أداة بشرية تقوم بعملية الحسابات. 
    \end{RLtext}
    %
    \end{document}

which gives the message ```Process exited with error(s)``` upon local compiling, with no more details or messages that I could find.

The same code compiles just fine on [Overleaf][3] with the output:

[![enter image description here][4]][4]

where I guess the website has been delayed on today's update.

Does the problem look specific to my installation (like being corrupted, etc.), or is it related to the update? And if so, where can the package maintainer be reached?

Thanks.

  [1]: https://miktex.org/pkg
  [2]: https://ctan.org/pkg/arabtex?lang=en
  [3]: https://www.overleaf.com/
  [4]: https://i.stack.imgur.com/AqydY.png

**Comment by u-fischer** [comment]
The error message is at the end of the log-file

~~~~
!pdfTeX error: pdflatex-dev.exe (file xnsh14.pfb): cannot open Type 1 font file
 for reading
 ==> Fatal error occurred, no output PDF file produced!
~~~~

The problem is that the type1 fonts from https://ctan.org/tex-archive/language/arabic/arabtex/psfonts are missing.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
