### ISSUE TITLE
rasterized fonts (missing `cm-super`)

### ISSUE THREAD

**Issue by JoKalliauer** [MiKTeX/miktex-packaging#285]
- [x] After read and acknowledging [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report) I ended up here and it a universal and known problem, therefore I do not need to provide any MiKTeX-Logs.

## Description

 Many people having rasterized fonts with MiKTeX, several of my PhD-coleages had this problem and is also often discussed in the internet
 - https://tex.stackexchange.com/questions/98708/miktex-for-ms-windows-seems-to-use-type3-raster-fonts-when-instructed-to-use-t
 - https://latex.org/forum/viewtopic.php?t=31798
 - https://www.reddit.com/r/LaTeX/comments/11d2h7/any_help_with_pixelated_font/
 to name a few.

## Solution
 
And the solution is just to install `cm-super`. It works without, but the antialising/text-smoothing is hard to read if you zoom out. And if you zoom it it looks not that nice having a pixalted font.

I know people that changed the font, that is also often recommended in the internet, however changing the font is not an option, because it is defined by most template (thesis or a scientific article).

## Examples

1. LaTeX-Code can be found at https://tex.stackexchange.com/questions/1291/why-are-bitmap-fonts-used-automatically 
2. Screenshot zoomed in: https://tex.stackexchange.com/questions/206735/math-font-pixellated-cmbright
3. PDF with pixalated font can be found at https://www.asc.tuwien.ac.at/eprog/download/EProg-Starterkit_Windows.zip /EProg-Starterkit_Windows\Installation\ReadMe.pdf

Zoomed out it is difficult to read, because anti-alising does not work that good
![grafik](https://user-images.githubusercontent.com/15687581/175645214-b2cb35e6-4cd9-4bd6-863a-a0bc9921a62a.png)

How the Text looks like zoom in:
![grafik](https://user-images.githubusercontent.com/15687581/175645260-59c3b553-4a56-4e3f-a481-0af24eb82dc5.png)
How it should look like:
![grafik](https://user-images.githubusercontent.com/15687581/175645372-20a3d10c-f4dc-4080-9eed-96c8affd77a3.png)

### Copyright of the embedded images 

source: https://www.asc.tuwien.ac.at/eprog/download/EProg-Starterkit_Windows.zip /EProg-Starterkit_Windows\Installation\ReadMe.pdf and https://www.asc.tuwien.ac.at/eprog/download/Anleitung_macOS_2020.pdf

license: no permission, fair-use, maybe below threshold of originality

Author:  Research Group of Dirk Praetorius at TU-Wien https://www.asc.tuwien.ac.at/eprog/

**Comment by edocevoli** [comment]
Thank you for the info. The solution for your issue was to install package `cm-super`.

**Comment by JoKalliauer** [comment]
> Thank you for the info. The solution for your issue was to install package `cm-super`.

Yes that was the solution. However it would be nice if this package would get installed by default, or "on the fly" if LaTeX would use a rasterized font otherwise.

**Comment by ivankokan** [comment]
@JoKalliauer The default (rasterized) Computer Modern font is Knuth's original, while the `cm-super` is an CM-upgrade in terms of the used font type and its definition.

That's why it makes sense to keep `cm-super` out of the default scope, although its quality and acceptability is non-questionable, i.e. there are many many pros to use it by default but at least one (and probably the most important) not to - historical aspects and legacy.

Document/template/class authors and maintainers should be aware of this, and can always (implicitly) force the usage of `cm-super`.

https://tex.stackexchange.com/questions/333092/forcing-cm-super-usage-installation

Regards, Ivan (the one who had the same thoughts as you years ago)

**Comment by JoKalliauer** [comment]
I knew that `cm-super` replaces rasterized fonts, see [MiKTeX](https://miktex.org/packages/cm-super) or [CTAN](https://ctan.org/pkg/cm-super)

But the large problem is that TeX Live has installed it by default, therefore you get different result based on your package-manager, and "nobody" knows why. Our LaTeX-Instructure at university said we should install all LaTeX-packages (~5GB) (with MiKTeX) to avoid problems, which might be because he wasn't aware of the cm-super-problem. (At that time I didn't had so much free disk-space.) 

I think LaTeX should look OS-independent (on Windows it is still common to use MiKTeX and on Linux&Mac it is still common to use TeX-Live).

I think using rasterized fonts on MiKTeX, differently to TeX-Live is a problem of MiKTeX and not of TeX-Live, since I never heard someone saying why is my font not rasterized. Vector-fonts need less PDF-diskspace, are better readable due to better font-smothing,...  . (Hardly) noone is saying I compiled it 25years ago, why is now the font not pixalated any more.

I don't think defaulting `cm-super` on installation would lead to any breaking changes and if it would that would imho be a LaTeX-Problem, since having a full installation (~5GB) should not break the system.

If you have any Hardliner really loving Knuth's original rasterized fonts, they will know well enough that removing `cm-super` brings back their outdated fonts. I think MiKTeX should be for User and not for Knuth-fans. I think even Knuth would use the vectorized fonts, otherwise LaTeX is not competitive with Libre-Office and co.

> Document/template/class authors and maintainers should be aware of this

They are not, and they (different to the users) don't care about it.

template-authors imho in most cases don't care about anything. E.g. a thesis-template is spread by the professor, but used by the student. I don't think that a normal template-autor does know the cm-super-problem. Why nobody fixing those?

1) Elserviers latex template, which might be most used template in the world since Elservier is the largest publisher for scientific articles, using elsarticle has several warnings and [one overfull box](https://tex.stackexchange.com/questions/514218/elsarticle-frontmatter-overfull-hbox-has-occurred-while-output-is-active).

2) If you submit to an conference-article, the template itself is often  inconsistent (In the text it is written you must provide DOI, but in the example no citation has a DOI, or a article with 3 authors has et al. but an article with 4 authors has written explicitly all authors,...). It is the problem of the author selling their paper not of the template-maker.

3) The two Thesistemplates I used for my Mastertheis or my PhD-theis had been developed imho before `cm-super` was developed. Since the thesis should look uniform, MiKTeX-users shouldn't change the font (e.g. to \usepacke{lmodern}, which is often called the "solution"), differently to anyone else.

4) Many people work on Linux/Mac, mostly using TeX-Live, which has cm-super installed by default. Since most Uni-professors in my field nowadays work on Mac (with TeX-Live) it works on there system but not on the system of the Student running it on there private PC (i.e. MiKTeX on Windows) it looks different. That is imho inacceptable

> , and can always (implicitly) force the usage of `cm-super`.

How can someone force the use of `cm-super`, if you are not aware of the problem (e.g. TeX-Live users), or think (as most of my colleges thought) it is there OS missing some Windows-fonts.

I may not be as experienced as you are, but I don't think MiKTeX should stay (differently to TeX-Live) with the Knuth's original old rasterized-fonts, even it will improve font-rendering of old documents.

**Comment by JoKalliauer** [comment]
TeX is a system that is designed to be compatible across systems, but currently it is not:

Let's compare the rendering of MiKTeX-compiled PDF on Windows (without cm-super) and a TeXLive-compiled PDF on Mac:


50%
![grafik](https://user-images.githubusercontent.com/15687581/176918445-e13fb1fb-eec7-4fc1-a694-8c23a4f33ddc.png)

----
100%
![grafik](https://user-images.githubusercontent.com/15687581/176918336-0f3cd50d-eb76-4a6e-81ff-074a805064c4.png)

----
200%
![grafik](https://user-images.githubusercontent.com/15687581/176918202-4238a1ff-7d2a-4b9a-ad45-65dcdc7d1d73.png)

---

The rasterized fonts are more difficult to read, that discriminates dyslexic people like me. (Actually serif fonts in general are not at all dyslexic friendly.)

I understand that there are technical limits that you cannot include everyone, but about 9% of the world suffers from being dyslexic, some more some less. I would like to live in an inclusive environment. :-D

@edocevoli I would like to hear you opinion on that. Is there an information missing you need to know?
