### ISSUE TITLE
Experimental patterns for ngerman and german don't work

### ISSUE THREAD

**Issue by wagnerdk** [MiKTeX/miktex-packaging#286]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

I have the same problem as described in [issue 238](https://github.com/MiKTeX/miktex-packaging/issues/238) and I think the problem is not solved, even if the original issue is closed. I get the same error in the MVE. 
Also, the console shows that the ngerman language is not installed.
![ngerman](https://user-images.githubusercontent.com/18245675/175792622-0aa84754-e7e8-4959-920e-5372c3fe8277.png)

The dehyph-exptl package has an install tutorial which is not part of the readme but inside the package. This tutorial recommends adding new language for ngerman-x-latest but there is no "new" button in the language tab as described by this tutorial.

Can I debug this any further?

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
