### ISSUE TITLE
Cannot get MikTeX/TexnicCenter working on new computer

### ISSUE THREAD

**Issue by elfsoft2000** [MiKTeX/miktex-packaging#288]
When I install MikTeX for multiusers I get a setupwiz options error (no details).  The single user install works fine, but TexnicCemter does not accept C:\Users\John\AppData\Local\Programs\MiKTeX (or any other MikTeX folder I have found in APPData) as valid.  I would prefer the multiuser version so I can keep the good packages separate for the POS packages I pick up from the LaTeX Stacl Exchange.

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
