### ISSUE TITLE
Problem installing package "wrapstuff"

### ISSUE THREAD

**Issue by gjmcclure** [MiKTeX/miktex-packaging#289]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)
Package "wrapstuff" fails to install with "Unknown archive file size."
Additional info from installer:
starting package maintenance...
installation directory: "C:\Program Files\MiKTeX 2.9"
package repository: https://mirror.koddos.net/CTAN/systems/win32/miktex/tm/packages/
package repository digest: bc943f98d9c298fb3672b55bb3e2b927

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
