### ISSUE TITLE
geometry.sty missing from geometry package

### ISSUE THREAD

**Issue by moewew** [MiKTeX/miktex-packaging#29]
The 2018-05-11 version of the `geometry` package seems to be missing all runtime files: https://miktex.org/Package/Browse/geometry

**Comment by u-fischer** [comment]
and for some reason my system contains a rather old geometry.sty version in tex/latex/geometry-de which is now found instead.

**Comment by moewew** [comment]
Thank you for the quick fix. The 2018-05-12 fixes both issues.
