### ISSUE TITLE
Package bundle 'graphics' is incomplete: File 'mathcolor.ltx' is missing

### ISSUE THREAD

**Issue by user227621** [MiKTeX/miktex-packaging#296]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The file `mathcolor.ltx` from the LaTeX `graphics` bundle ([link to CTAN](https://ctan.org/pkg/latex-graphics)) is missing in MiKTeX ([link to MiKTeX file list](https://miktex.org/packages/graphics/files)).

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
