### ISSUE TITLE
Problem with package urw

### ISSUE THREAD

**Issue by petiard** [MiKTeX/miktex-packaging#298]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)
Hello
In MiKTeX console, the package urw is indicated (with a size of 0 byte and the date 1970-01-01 and there is no package urw in CTAN/MiKTeX.. Of course, the installation of that package failed.

Best regards

François

**Comment by edocevoli** [comment]
Thank you, this will be fixed with the next update. The package name is now `urw-base35`.
