### ISSUE TITLE
Misplaced files in pgf-PeriodicTable MiKTeX Package

### ISSUE THREAD

**Issue by HugoPGomes** [MiKTeX/miktex-packaging#299]
<p>In current MiKTeX Packages:</p>
<table style="border-collapse: collapse; width: 100%; height: 66px;" border="1">
<tbody>
<tr style="height: 22px;">
<td style="width: 32.3622%; height: 22px;">pgf-periodictable</td>
<td style="width: 32.3622%; height: 22px;">Create custom periodic tables of elements&nbsp;</td>
<td style="width: 32.3639%; height: 22px;">10/15/2022 &nbsp; &nbsp;1.0.0 &nbsp; &nbsp;lppl1.3</td>
</tr>
<tr style="height: 22px;">
<td style="width: 32.3622%; height: 22px;">pgf-periodictable__doc</td>
<td style="width: 32.3622%; height: 22px;">Create custom periodic tables of elements</td>
<td style="width: 32.3639%; height: 22px;">10/15/2022 &nbsp; &nbsp;1.0.0 &nbsp; &nbsp;lppl1.3</td>
</tr>
<tr style="height: 22px;">
<td style="width: 32.3622%; height: 22px;">pgf-periodictable__source</td>
<td style="width: 32.3622%; height: 22px;">Create custom periodic tables of elements</td>
<td style="width: 32.3639%; height: 22px;">10/15/2022 &nbsp; &nbsp;1.0.0 &nbsp; &nbsp;lppl1.3</td>
</tr>
</tbody>
</table>
<p>some files are misplaced:</p>
<table style="border-collapse: collapse; width: 100%;" border="1">
<tbody>
<tr>
<td style="width: 32.3622%;"><span style="text-decoration: underline;">filename</span></td>
<td style="width: 32.3622%;"><span style="text-decoration: underline;">current directory</span></td>
<td style="width: 32.3639%;"><span style="text-decoration: underline;">should be in the directory</span></td>
</tr>
<tr>
<td style="width: 32.3622%;">pgfPT.backcolors.keys.tex</td>
<td style="width: 32.3622%;">texmf\source\pgf-periodictable</td>
<td style="width: 32.3639%;">texmf\tex\latex\pgf-periodictable</td>
</tr>
<tr>
<td style="width: 32.3622%;">pgfPT.buildcell.tex</td>
<td style="width: 32.3622%;">texmf\source\pgf-periodictable</td>
<td style="width: 32.3639%;">texmf\tex\latex\pgf-periodictable</td>
</tr>
<tr>
<td style="width: 32.3622%;">pgfPT.colorSchemes.info.tex</td>
<td style="width: 32.3622%;">texmf\source\pgf-periodictable</td>
<td style="width: 32.3639%;">texmf\tex\latex\pgf-periodictable</td>
</tr>
<tr>
<td style="width: 32.3622%;">pgfPT.coordinates.tex</td>
<td style="width: 32.3622%;">texmf\source\pgf-periodictable</td>
<td style="width: 32.3639%;">texmf\tex\latex\pgf-periodictable</td>
</tr>
<tr>
<td style="width: 32.3622%;">pgfPT.data.tex</td>
<td style="width: 32.3622%;">texmf\source\pgf-periodictable</td>
<td style="width: 32.3639%;">texmf\tex\latex\pgf-periodictable</td>
</tr>
<tr>
<td style="width: 32.3622%;">pgfPT.drawing.keys.tex</td>
<td style="width: 32.3622%;">texmf\source\pgf-periodictable</td>
<td style="width: 32.3639%;">texmf\tex\latex\pgf-periodictable</td>
</tr>
<tr>
<td style="width: 32.3622%;">pgfPT.formatNumbers.tex</td>
<td style="width: 32.3622%;">texmf\source\pgf-periodictable</td>
<td style="width: 32.3639%;">texmf\tex\latex\pgf-periodictable</td>
</tr>
<tr>
<td style="width: 32.3622%;">pgfPT.labels.tex</td>
<td style="width: 32.3622%;">texmf\source\pgf-periodictable</td>
<td style="width: 32.3639%;">texmf\tex\latex\pgf-periodictable</td>
</tr>
<tr>
<td style="width: 32.3622%;">pgfPT.names.tex</td>
<td style="width: 32.3622%;">texmf\source\pgf-periodictable</td>
<td style="width: 32.3639%;">texmf\tex\latex\pgf-periodictable</td>
</tr>
<tr>
<td style="width: 32.3622%;">pgfPT.process.language.tex</td>
<td style="width: 32.3622%;">texmf\source\pgf-periodictable</td>
<td style="width: 32.3639%;">texmf\tex\latex\pgf-periodictable</td>
</tr>
<tr>
<td style="width: 32.3622%;">pgfPT_radio_symbol.pdf</td>
<td style="width: 32.3622%;">texmf\doc\latex\pgf-periodictable</td>
<td style="width: 32.3639%;">texmf\tex\latex\pgf-periodictable</td>
</tr>
</tbody>
</table>
<p>The file pgf-PeriodicTable.sty input all this files.</p>
<p>Thanks,</p>
<p>Hugo Gomes</p>
<p>&nbsp;</p>

**Comment by edocevoli** [comment]
Thank you, this will be fixed with the next update.
