### ISSUE TITLE
latexdiff

### ISSUE THREAD

**Issue by mit50** [MiKTeX/miktex-packaging#3]
Hi, guys -

It seems latexdiff does not work under the most recent version of MiKTeX 2.9. When I try to run it, I get the following error message:

Command Line: cmd.exe /C latexdiff.exe "C:\Users\MT\Desktop\test\pub.2.tex" "pub.1.tex" > "pub.1_diff.tex"
Startup Folder: C:\Users\MT\Desktop\test

utf8 "\xBD" does not map to Unicode at C:\Program Files\MiKTeX 2.9\scripts\latexdiff\latexdiff line 1107, chunk 1.
utf8 "\xBD" does not map to Unicode at C:\Program Files\MiKTeX 2.9\scripts\latexdiff\latexdiff line 1107, chunk 1.
Malformed UTF-8 character: \xbd (unexpected continuation byte 0xbd, with no preceding start byte) in pattern match (m//) at C:\Program Files\MiKTeX 2.9\scripts\latexdiff\latexdiff line 1383.
Malformed UTF-8 character (fatal) at C:\Program Files\MiKTeX 2.9\scripts\latexdiff\latexdiff line 1383.

Please fix.
Thanks

**Comment by edocevoli** [comment]
I don't think that this is a MiKTeX-specific bug.
