### ISSUE TITLE
The huaz package is missing

### ISSUE THREAD

**Issue by hair-splitter** [MiKTeX/miktex-packaging#302]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The `huaz` package should be added to the MiKTeX package repository:
[https://ctan.org/pkg/huaz](https://ctan.org/pkg/huaz)

Thank you!

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
