### ISSUE TITLE
pixelart is missing its lua file

### ISSUE THREAD

**Issue by paternal** [MiKTeX/miktex-packaging#306]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Hello. I am the maintainer of pixelart ([ctan](https://ctan.org/tex-archive/graphics/pgf/contrib/pixelart), [miktex](https://miktex.org/packages/pixelart/files)). The file pixelart.lua is missing in miktex, and should be included (in the same directory as pixelart.sty).

Should I have packaged pixelart differently, so that pixelart.lua would have been automatically included?

Thanks for your work,
Louis

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
