### ISSUE TITLE
source2e outdated

### ISSUE THREAD

**Issue by moewew** [MiKTeX/miktex-packaging#308]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Calling `texdoc --view source2e` on my fully updated MikTeX machine opens `source2e` for 2022-06-01 Patch level 5. CTAN has 2022-11-01 (http://mirrors.ctan.org/macros/latex/base/source2e.pdf). Since the kernel package `ltxbase` is at 2022-11-01 in MikTeX this mismatch between documentation and actually installed software can lead to confusion.

Please update `source2e` in `ltxbase__doc`.

**Comment by edocevoli** [comment]
Should be ok now. My `texdoc` invocation opens the latest PDF.
