### ISSUE TITLE
How to create my_own_package.tar.lzma ?

### ISSUE THREAD

**Issue by ChristianeHofer** [MiKTeX/miktex-packaging#31]
Dear all, 
For our institution it is not possible to install packages from the www, therefore we have a package repository on an internal drive. The colleagues using MiKTeX have this drive in their settings to install the General Packages from this drive. There I stored all packages with a complete download ( a lot of packages and the miktex-zzdb1-2.9.tar.lzma, miktex-zzdb2-2.9.tar.lzma). This works. In addition to that we have own "packages" (not compressed) for presentations that fits our styles. How can I create a my_own_package.tar.lzma and how can I integrate it in (or update) miktex-zzdb1-2.9.tar.lzma und miktex-zzdb2-2.9.tar.lzma. Which tools should I use, do you have any documentation? 
Regards Christiane

**Comment by edocevoli** [comment]
You can create packages with `mpc` (MiKTeX Pacakage Composer) which is not a part of the MiKTeX distribution (also see this issue: MiKTeX/miktex#55).
