### ISSUE TITLE
cjk-fonts package puts map files in the wrong place

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#310]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The cjk-fonts package puts `wadalab.map` into `texmf/dvips/wadalab`, and `wansong.map` into `texmf/dvips/wansong`. That was the correct location some years ago, but the map files are now no longer found there.

See e.g. https://tex.stackexchange.com/questions/667466/unable-to-get-the-japanese-character-hiragana-yo-in-pdflatex-using-texstudio for an error message.

After moving the map files into  `texmf/fonts/map/dvips/wadalab` and ``texmf/fonts/map/dvips/wansong`, refreshing the file name database and the font map files the document compiled as expected.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.
