### ISSUE TITLE
tagpdf package is incomplete

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#312]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The newest versions (0.98 from 2022-12-22 and 0.98a from 2022-12-28) of the tagpdf package contain also two csv-files 
`tagpdf-parent-child.csv` and `tagpdf-parent-child-2-csv` (unpacked from tagpdf-data.dtx) which are needed for the compilation. Currently there are missing in the miktex package.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.
