### ISSUE TITLE
biber-windows-x86: program could not be found.

### ISSUE THREAD

**Issue by martok** [MiKTeX/miktex-packaging#315]
The script link for biber does not work anymore on windows-x86:

```
INFO  biber - this process (2664) started by powershell in directory .... with command line: "C:\Program Files (x86)\MiKTeX 2.9\miktex\bin\biber.exe"
FATAL biber.core - The program '{name}' could not be found.
FATAL biber.core - Data: engine="exe", path="executables/windows-x86/biber/biber.exe", name="biber"
FATAL biber.core - Source: Libraries\MiKTeX\Core\Session\runperl.cpp:57
```

This seems to be a platform packaging issue, the path given in `scripts.ini` is correct for [biber-windows-x64](https://miktex.org/packages/biber-windows-x64/files), [biber-linux-x86_64](https://miktex.org/packages/biber-linux-x86_64/files) and [biber-darwin-x86_64](https://miktex.org/packages/biber-darwin-x86_64/files), but ***not*** for [biber-windows-x86](https://miktex.org/packages/biber-windows-x86/files), which installs into the old(?) path `biber\bin\windows-x86\biber.exe`.

**Comment by edocevoli** [comment]
I am afraid 32-bit biber is not supported/provided anymore. See https://miktex.org/announcement/miktex-32-bit-end-of-life

**Comment by martok** [comment]
I mean, it is provided, current, downloadable, installable, it even works when invoked directly or via hardlink on the expected new location.
Shouldn't the updater warn the user before updating to broken packages? Even just a general "this version is not supported, if anything breaks it's on you" would be better.

Thanks anyway, at least the error message is googleable now.
