### ISSUE TITLE
transparent package is not up-to-date

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#316]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

miktex currently ships the transparent package version 2019/11/29 v1.4. This version is outdated (and not compatible with the pdfmanagement-testphase package).  The current version is 2022-10-27 1.5.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.
