### ISSUE TITLE
packages codebox and termsim not unpacked properly

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#319]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The packages [codebox](https://ctan.org/pkg/codebox) and [termsim](https://ctan.org/pkg/termsim) (both by the same author) seem not to have had their dtx properly unpacked. All three folders `.../MikTeX/tex/latex/codebox`, `.../Miktex/doc/latex/codebox`, and `.../Miktex/source/codebox` are present, however `.../MikTeX/tex/latex/codebox` contains just the file `ctxdoc-en.cls` which is only needed to build the documentation. Same for termsim. The files `codebox.sty` and `termsim.sty` are not present at all. Note that running `tex codebox.dtx` and `tex termsim.dtx` produce the .sty files as expected.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
