### ISSUE TITLE
Stale filed in packaged version of caption package 2018/04/16

### ISSUE THREAD

**Issue by JohannesPfeifer** [MiKTeX/miktex-packaging#32]
The `source`-subfolder at e.g. https://ftp.rrze.uni-erlangen.de/ctan/systems/win32/miktex/tm/packages/caption.tar.lzma contains the updated files while e.g. the `tex`-subfolder contains files from 2016. I experience this problem with every mirror I choose and thus cannot update the package. Instead, the Miktex console tells me that the package was correctly updated. I was referred here from https://github.com/axelsommerfeldt/caption/issues/7

**Comment by edocevoli** [comment]
Thank you, I think this has been fixed.
