### ISSUE TITLE
misplaces lua files for luamesh package

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#321]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

MiKTeX places the files `luamesh-polygon.lua` and `luamesh-tex.lua` of the [luamesh](https://www.ctan.org/pkg/luamesh) package in `.../MiKTeX/source/luamesh/scripts` rather than in `.../MiKTeX/scripts/luamesh` where I believe they belong. The file `luamesh.lua` is already correctly placed.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
