### ISSUE TITLE
latex-tools package is outdated

### ISSUE THREAD

**Issue by lvjr** [MiKTeX/miktex-packaging#323]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

TeXLive has `array.sty` of version  `2022/09/04 v2.5g`, but MiKTeX still has `array.sty` of version  `2022/03/10 v2.5f`.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
