### ISSUE TITLE
Two copies of nextpage.sty and verbasef.sty

### ISSUE THREAD

**Issue by lvjr** [MiKTeX/miktex-packaging#324]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

In miktex, `nextpage.sty` is included in both `ltxmisc` and `nextpage` packages, and `verbasef.sty` is included in both `ltxmisc` and `verbasef` packages:
```
texmf/tex/latex/ltxmisc/nextpage.sty
texmf/tex/latex/ltxmisc/verbasef.sty
texmf/tex/latex/nextpage/nextpage.sty
texmf/tex/latex/verbasef/verbasef.sty
```

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
