### ISSUE TITLE
two conflicting versions of mathdots package

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#327]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The [mathdots](https://www.ctan.org/pkg/mathdots) package has its own directory `.../tex/generic/mathdots` containing mathdots.sty, version 0.9, dated 2014/06/11. However there is also a mathdots.sty in `.../tex/generic/genmisc` with version 0.6, dated 2004/07/02. On my system the older version is called with `\usepackage{mathdots}`.

Shouldn't the older mathdots.sty be removed from genmisc?

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
