### ISSUE TITLE
directory path has wrong / and \

### ISSUE THREAD

**Issue by syanshk** [MiKTeX/miktex-packaging#33]
In MikTex console, in Setting, Directories, how do I change  Bin Directory?
It is  set up wrong, wit a  mix of Windows and Mac path separators:
 C:\Program Files\MikTex 2.9\miktex/bin/x64

**Comment by edocevoli** [comment]
It is not possible to change the location of the `bin` directory. The path looks okay. '\' and '/' are valid directory delimiters (on Windows).
