### ISSUE TITLE
package chextras not unpacked properly

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#330]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The package [chextras](https://www.ctan.org/pkg/chextras) is listed in MiKTeX but only contains the files `README` and `chextras.pdf`, not `chextras.sty` (or even the dtx and ins files, it seems).

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
