### ISSUE TITLE
digestif is incorrectly packaged

### ISSUE THREAD

**Issue by astoff** [MiKTeX/miktex-packaging#331]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

- A symlink or copy (with executable permissions) of `texmf\scripts\digestif\digestif.texlua` should be placed in the PATH, with the name `digestif`.
- The file `texmf\scripts\digestif\digestif` is not relevant in a TeX distribution (it's used to run the program with `lua` instead of `texlua`). It would be best to not include this file in MikTeX.

**Comment by edocevoli** [comment]
This has been implemented. On Windows, `digestif.exe` is a stub which runs texlua digestif.texlua

**Comment by astoff** [comment]
Okay, thanks! I assume you mean the executable already existed before I opened the ticket. In this case, I should mention that the docker image is still missing the necessary symlink.
