### ISSUE TITLE
stex package files in wrong location

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#332]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Several files for the [stex](https://www.ctan.org/pkg/stex) package are located in `.../source/...` rather than `.../tex/...` where they should be, for example `stex.sty` and `stex.cls`.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
