### ISSUE TITLE
latexmk is (very) outdated

### ISSUE THREAD

**Issue by Enivex** [MiKTeX/miktex-packaging#334]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

MiKTeX is on version 4.78, released 2022/11/24
https://miktex.org/packages/latexmk

Version 4.79 was released 2023/01/07
https://ctan.org/pkg/latexmk

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
