### ISSUE TITLE
Misplaced files in pgf-PeriodicTable (v2.0.0) MiKTeX Package

### ISSUE THREAD

**Issue by HugoPGomes** [MiKTeX/miktex-packaging#335]
<p dir="auto">In current MiKTeX Packages:</p>
<table role="table" border="1">
<tbody>
<tr>
<td>pgf-periodictable</td>
<td>Create custom periodic tables of elements&nbsp;</td>
<td>02/23/2023 &nbsp; &nbsp;2.0.0 &nbsp; &nbsp;lppl1.3</td>
</tr>
<tr>
<td>pgf-periodictable__doc</td>
<td>Create custom periodic tables of elements</td>
<td>02/23/2023 &nbsp; &nbsp;2.0.0 &nbsp; &nbsp;lppl1.3</td>
</tr>
<tr>
<td>pgf-periodictable__source</td>
<td>Create custom periodic tables of elements</td>
<td>02/23/2023 &nbsp; &nbsp;2.0.0 &nbsp; &nbsp;lppl1.3</td>
</tr>
</tbody>
</table>
<p dir="auto">some files are misplaced:</p>
<table role="table" border="1">
<tbody>
<tr>
<td>filename</td>
<td>current directory</td>
<td>should be in the directory</td>
</tr>
<tr>
<td>pgfPT.input.library.tex</td>
<td>texmf\source\pgf-periodictable</td>
<td>texmf\tex\latex\pgf-periodictable</td>
</tr>
<tr>
<td>pgfPTlibrary.colorschemes.tex</td>
<td>texmf\source\pgf-periodictable</td>
<td>texmf\tex\latex\pgf-periodictable</td>
</tr>
</tbody>
</table>
<p dir="auto">The file pgf-PeriodicTable.sty input this two files.</p>
<p dir="auto">Thanks,</p>
<p dir="auto">Hugo Gomes</p>

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
