### ISSUE TITLE
missing albatross executable

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#338]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

According the [albatross documentation](https://ctan.org/pkg/albatross), `albatross` should be available on the command line, however MiKTeX only provides the files `albatross.jar` and `albatross.sh`. Calling `albatross` on Windows 10 with an updated MiKTeX leads to 
```
albatross : The term 'albatross' is not recognized as the name of a cmdlet, function, script file, or operable
program.
```
I'm no expert regarding these things, but shouldn't MiKTeX also provide an executable file with the package?

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
