### ISSUE TITLE
glyphtounicode-cmex.tex in wrong location

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#339]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The file `glyphtounicode-cmex.tex` is in `.../MiKTeX/source/latex-lab-dev` when it should be in `.../MiKTeX/tex/latex/latex-lab-dev`. Here's an example showing the issue with the location (the file is called by `latex-lab-kernel-changes.sty`):
```latex
\DocumentMetadata{testphase=phase-III}
\documentclass{article}
\begin{document}
text
\end{document}
```

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
