### ISSUE TITLE
cellprops.tpm won't parse

### ISSUE THREAD

**Issue by caitlin91** [MiKTeX/miktex-packaging#34]
When trying to check for updates on MiKTeX I get the error message "The package definition file could not be parsed." I believe there is a syntax error in the cellprops.tpm file but I don't know how to open it to check. The full error info is below:

MiKTeX Problem Report
Message: The package definition file could not be parsed.
Data: path="C:\Users\Caitlin\AppData\Local\Temp\mik60486\cellprops.tpm", column="1124", line="2"
Source: Libraries\MiKTeX\PackageManager\TpmParser.cpp
Line: 330
MiKTeX: 2.9
OS: Windows 10 Home, 64-bit, build 17134
Invokers: non-existing
SystemAdmin: yes
PowerUser: no
Root0: C:\Users\Caitlin\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\Caitlin\AppData\Local\MiKTeX\2.9
Root2: C:\Users\Caitlin\AppData\Local\Programs\MiKTeX 2.9
Root3: C:\ProgramData\MiKTeX\2.9
Root4: C:\Program Files\MiKTeX 2.9
UserInstall: C:\Users\Caitlin\AppData\Local\Programs\MiKTeX 2.9
UserConfig: C:\Users\Caitlin\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\Caitlin\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

**Comment by edocevoli** [comment]
Thank you, this will be fixed with one of the next updates.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.

**Comment by amalouf** [comment]
Thank you
