### ISSUE TITLE
tikz-trackschematic.sty in wrong location

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#340]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The file `tikz-trackschematic.sty` from the [tikz-trackschematic](https://www.ctan.org/pkg/tikz-trackschematic) package is in `.../MiKTeX/source/tikz-trackschematic` when it should be in `.../MiKTeX/tex/latex/tikz-trackschematic`.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
