### ISSUE TITLE
pst-bar.sty duplicated, old version in tex tree

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#341]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

`pst-bar.sty` from the [pst-bar](https://www.ctan.org/pkg/pst-bar) package appears in both `.../MiKTeX/source/pst-bar/latex` and `.../MiKTeX/tex/latex/pst-bar`. The former (misplaced) one is from 2022, the latter from 2004.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
