### ISSUE TITLE
nahuatl package files in wrong location

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#342]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The file `nahuatl.sty` from the [nahuatl](https://www.ctan.org/pkg/nahuatl) package is in `.../MiKTeX/source/nahuatl/latex` while it should be in `.../MiKTeX/tex/latex/nahuatl`. Note that no such directory `.../MiKTeX/tex/latex/nahuatl` currently exists.

Also, the file `nahuatl.pk` is in `.../MiKTeX/source/nahuatl/font/pk` when I believe it should be in some subdirectory of `.../MiKTeX/fonts/pk`.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

The PK file is not in the runtime tree because it will be created on-the-fly, if needed.
