### ISSUE TITLE
vpe.sty duplicated, in wrong location

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#343]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The file `vpe.sty` from the [vpe](https://www.ctan.org/pkg/vpe) package is in both `.../MiKTeX/doc/latex/vpe` and `.../MiKTeX/tex/latex/vpe`. The newer version 0.2 is in the wrong location, the doc folder, while version 0.1 is in the main tex tree.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
