### ISSUE TITLE
bxeepic.sty duplicated

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#344]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The file `bxeepic.sty` from the [bxeepic](https://www.ctan.org/pkg/bxeepic) package appears in both `.../MiKTeX/tex/latex/bxeepic` (version 0.2) and `.../MiKTeX/tex/latex/bxpict2e` (version 0.1). I think the package may have changed names from bxpict2e to bxeepic so the bxpict2e directory can be removed.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
