### ISSUE TITLE
l3packages out of date

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#345]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The [l3packages](https://www.ctan.org/pkg/l3packages) bundle in MiKTeX is out of date. MiKTeX's version is 2023-01-16, while CTAN has 2023-02-02.

This is relevant because the command `\DeclareInstanceCopy` was added to the `xtemplate` package with that update, and the new tagging code requires this command.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
