### ISSUE TITLE
neo-euler package deprecated

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#346]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The `neo-euler` package was renamed [`euler-math`](https://www.ctan.org/pkg/euler-math) and the new package comes with a compatibility file `neo-euler.sty` (v0.23) that just inputs `euler-math.sty`, however MiKTeX still has the old `neo-euler` package (in addition to euler-math) with the deprecated .sty file (v0.21). This leaves two different versions of `neo-euler.sty` in the tex tree.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
