### ISSUE TITLE
soulutf8 package deprecated

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#347]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The package `soulutf8` was merged with the [`soul`](https://www.ctan.org/pkg/soul) package, however MiKTeX still has `soulutf8` as a separate package containing the outdated `soulutf8.sty` (v1.2). The copy of `soulutf8.sty` in the `soul` package is v3.0.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
