### ISSUE TITLE
MiKTeX2009-pdftex.dll was not found

### ISSUE THREAD

**Issue by hwmway** [MiKTeX/miktex-packaging#35]
Hello,

 I attempted to upgrade LyX to version 2.2.3. However, it does not allow me to
 typeset since it says there is a system error "pdflatex.exe". LyX popped
 up a box which says"

 "The code execution cannot proceed because
 MiKTeX2009-pdftex.dll was not found. Reinstalling the program may fix this
 problem."

 I tried to uninstall both LyX and MikTex, and installed them again. I am
 still having the same problem.

 My Windows Version is 10 Home:

 OS Name Microsoft Windows 10 Home
 Version 10.0.17134 Build 17134

 Thank you so much for your help.

**Comment by edocevoli** [comment]
This is the wrong GitHub repository.
Besides that, your report does not contain enough info to reproduce/fix the issue.
