### ISSUE TITLE
Is there a problem with downloading MikTeX?

### ISSUE THREAD

**Issue by AndreC75** [MiKTeX/miktex-packaging#350]
I can not download the windows versions, it appears this error:
[https://polish-mirror.evolution-host.com/ctan/systems/win32/miktex/setup/windows-x64/setup-5.6.0+1763023-x64.exe](https://polish-mirror.evolution-host.com/ctan/systems/win32/miktex/setup/windows-x64/setup-5.6.0+1763023-x64.exe)

Not Found
The requested URL was not found on this server.

Apache/2.4.29 (Ubuntu) Server at polish-mirror.evolution-host.com Port 443

What is the problem ?

**Comment by jzsfvss** [comment]
Canadian mirrors not working either.

**Comment by jferrer2017** [comment]
Same problem, can't download

**Comment by jjolidon** [comment]
Those issues seem to be resolved now.
