### ISSUE TITLE
git-latexdiff: missing executables

### ISSUE THREAD

**Issue by ben-no** [MiKTeX/miktex-packaging#352]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The git-latexdiff package does not install corresponding executables in MiKTeX\miktex\bin\x64.

**Comment by edocevoli** [comment]
Cannot reproduce this:

```
$ which git-latexdiff
/home/xxx/bin/git-latexdiff

$ git-latexdiff
fatal: not a git repository (or any of the parent directories): .git
```

Please note that `git-latexdiff` requires Bash.
