### ISSUE TITLE
PSTricks not working under latest MikTeX version

### ISSUE THREAD

**Issue by AlgebraKati** [MiKTeX/miktex-packaging#353]
- [x] I have read and acknowledged this HOWTO article:  
  [](https://miktex.org/howto/bug-report)
Having installed the latest version of MikTeX, my files with pstricks (that run perfectly before) stop with the error message: undefined \ifPSTlualatex. Even when removing the line causing the error from the appropriate file (pstricks.con), errors/warnings keep on coming. In pstricks.sty \pst@cntm is undefined (I inserted a def), then after finishing loading tex/context/base/mkii\supp-pdf.mkii, it runs into another error: undefined \@@drv (it apperas to be in xcolor). I keep chasing the errors/warnings, but I do not seem to get to the end of it.
With every package I include (like pstricks-add, auto-pst-pdf, etc.), the errors/warnings keep on coming.
I made my code as simple as possible
\documentclass[12pt]{standalone}
\usepackage[pdf]{pstricks}
\begin{document}
\begin{pspicture}(-5,-5)(5,5)
\psline(-5,-5)(5,5)
\end{pspicture}
\end{document}

I use PDFLaTeX, write18 is enabled.
I attach the log file
[miktexbugreport.log](https://github.com/MiKTeX/miktex/files/11295853/miktexbugreport.log)

**Comment by AlgebraKati** [comment]
No matter where I can the pstricks.sty, you did not answer my first question.
Having installed the latest version of MikTeX, my files with pstricks (that run perfectly before) stop with the error message: undefined \ifPSTlualatex.

**Comment by u-fischer** [comment]
Your log file didn't show that error. But it shows that you are using a local pstricks.sty, and a very old pstricks.tex: 

~~~
C:\MiKTeX5\tex/latex/pstricks\pstricks.tex`PSTricks' v0.93a  <93/03/12> (tvz)
~~~ 

You also wrote that you manually changed various pstricks files. So basically your system is now in an unknown state. Uninstall pstricks, remove all local files and then reinstall it. If you still get errors send a bug report to the pstricks mailing list as they are the only one who can repair a pstricks error. Miktex only distributes the files.
