### ISSUE TITLE
pas-tableur packaging issue with recent update

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#354]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

With the recent update (2023/04/28), the package `pas-tableur` was updated but the new .sty file was placed in `.../source/pas-tableur/latex`, not `.../tex/latex/pas-tableur` as it should be. The old .sty file is still contained in `.../tex/latex/pas-tableur`.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
