### ISSUE TITLE
gpg key expired 

### ISSUE THREAD

**Issue by OriolLopezMassaguer** [MiKTeX/miktex-packaging#355]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The gpg key has expired in 2023-04-29
/etc/apt/trusted.gpg.d/miktex.gpg
---------------------------------
pub   rsa2048 2017-06-23 [SC] [expired: 2023-04-29]
      D6BC 2435 65B2 087B C3F8  97C9 277A 7293 F59E 4889
uid           [ expired] MiKTeX Packager <packager@miktex.org>

Tested in Ubuntu

**Comment by jjolidon** [comment]
Confirmed.

**Comment by edocevoli** [comment]
Thank you for the report. I will refresh the key asap (hopefully this week).

**Comment by autumn-traveller** [comment]
Hi, I am experiencing the same issue on fedora - any updates on when the the key will be refreshed?
