### ISSUE TITLE
TeXFindPkg not yet included in MiKTeX

### ISSUE THREAD

**Issue by lvjr** [MiKTeX/miktex-packaging#357]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

[TeXFindPkg](https://ctan.org/pkg/texfindpkg) tool supports both TeXLive and MiKTeX and was first uploaded to CTAN on April 5th. But it is not yet included in MiKTeX.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
