### ISSUE TITLE
deprecated japanese-otf-uptex directory should be removed

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#359]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

According to CTAN, the package [`japanese-otf-uptex`](https://www.ctan.org/pkg/japanese-otf-uptex) "... has been merged into [japanese-otf](https://www.ctan.org/pkg/japanese-otf)". It currently contains outdated versions of the files in `japanese-otf`.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
