### ISSUE TITLE
ltxtable.sty missing from carlisle bundle

### ISSUE THREAD

**Issue by moewew** [MiKTeX/miktex-packaging#36]
Via https://tex.stackexchange.com/q/437619/35864

The file `ltxtable.sty` that is produced from `ltxtable.tex` (https://ctan.org/pkg/ltxtable) by running the `.tex` file once with LaTeX, is not present in the `2018-05-31T23:11:16` version of the `carlisle` bundle in MikTeX. It should be included in `texmf\tex\latex\carlisle`

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by moewew** [comment]
Thank you very much.

**Comment by quaatz** [comment]
Could it be, that the problem showed up again with the latest Miktex Version?
