### ISSUE TITLE
kpsewhich could not find texfindpkg.json.gz file

### ISSUE THREAD

**Issue by lvjr** [MiKTeX/miktex-packaging#360]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

TeXFindPkg tool contains two files in `scripts` folder:
```
AppData\Local\Programs\MiKTeX\scripts\texfindpkg\texfindpkg.lua
AppData\Local\Programs\MiKTeX\scripts\texfindpkg\texfindpkg.json.gz
```

I could find `texfindpkg.lua` file with
```
kpsewhich texfindpkg.lua
```
but I can not find `texfindpkg.json.gz` file with
```
kpsewhich texfindpkg.json.gz
```

This causes error in running TeXFindPkg (see https://github.com/lvjr/texfindpkg/issues/6).

By the way, TeXLive puts `texfindpkg.json.gz` in `latex` folder:
```
texlive/2023/texmf-dist/tex/latex/texfindpkg/texfindpkg.json.gz
```
And I can find it with `kpsewhich texfindpkg.json.gz`. So I am not totally sure what is the correct location to put `.json.gz` files.

**Comment by lvjr** [comment]
After moving `texfindpkg.json.gz` to `C:\Users\<user>\AppData\Local\Programs\MiKTeX\tex\latex\texfindpkg` folder and refreshing filename database, TeXFindPkg runs well.

**Comment by edocevoli** [comment]
In Readme.md:

| Package file       | Where to install it |
| :------            | :------ |
| texfindpkg.1       | TEXMF/doc/man/man1/texfindpkg.1 |
| README.md          | TEXMF/doc/support/texfindpkg/README.md |
| texfindpkg.lua     | TEXMF/scripts/texfindpkg/texfindpkg.lua |
| texfindpkg.json.gz | TEXMF/scripts/texfindpkg/texfindpkg.json.gz |
| tfpbuild.lua       | TEXMF/source/texfindpkg/tfpbuild.lua |

So...

**Comment by lvjr** [comment]
Yes, maybe it is my fault. I didn't know that `kpsewhich` could not find gz files in `scripts` folder but could find them in `latex` folder. This seems strange...

**Comment by mbertucci47** [comment]
I believe this has been fixed and can be closed.
