### ISSUE TITLE
Portable MiKTeX doesn't create texfindpkg.exe when installing the package

### ISSUE THREAD

**Issue by lvjr** [MiKTeX/miktex-packaging#361]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

When installing `texfindpkg` package in normal MiKTeX, `texfindpkg.exe` is created inside folder
```
C:\Users\<user>\AppData\Local\Programs\MiKTeX\miktex\bin\x64
```
But when installing `texfindpkg` package in portable MiKTeX, `texfindpkg.exe` is NOT created inside folder
```
texmfs\install\miktex\bin\x64
```

**Comment by edocevoli** [comment]
Not sure how you installed the package. If you did it somewho manually, then you should run

```sh
miktex links install
```

**Comment by lvjr** [comment]
Actually I tried two ways: (1) use MiKTeX Console GUI to install the package; (2) use `miktex packages install texfindpkg` command to install it. But neither of them created `texfindpkg.exe` in the binary folder of my portable MiKTeX.
