### ISSUE TITLE
obsolete lgrx package

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#363]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The [`lgrx`](https://www.ctan.org/pkg/lgrx) package is obsolete and currently contains duplicate outdated copies of the .sty files `alphabeta.sty` and `textalpha.sty`, whose up-to-date files are in the [`greek-fontenc`](https://www.ctan.org/pkg/greek-fontenc) package.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
