### ISSUE TITLE
obsolete fixocgx package

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#365]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The [`fixocgx`](https://www.ctan.org/pkg/fixocgx) package is obsolete and should be removed. It contains the file `fixocgx.sty` which conflicts with the correct `fixocgx.sty` in package [`ocgx2`](https://www.ctan.org/pkg/ocgx2), which is just a stub warning the user the package is obsolete.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
