### ISSUE TITLE
odsfile package seems incomplete

### ISSUE THREAD

**Issue by fvollmer** [MiKTeX/miktex-packaging#366]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

It seems like `odsfile` isn't correctly packaged. `odsfile.lua` is missing from the file list:
![grafik](https://github.com/MiKTeX/miktex-packaging/assets/16699443/84d16524-c37f-4a16-9981-fe414c3a3da1)

**Comment by fvollmer** [comment]
Ups, yes I mean odsfile.lua

Sorry for the confusion.

mbertucci47 ***@***.***> schrieb am Di., 23. Mai 2023, 02:09:

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
