### ISSUE TITLE
luapstricks package files in wrong location

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#369]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The files `luapstricks-plugin-pstcie.lua`, `luapstricks-plugin-pstmarble.lua`, and `luapstricks-pstsolides3d.lua` of the [`luapstricks`](https://www.ctan.org/pkg/luapstricks) package should be in the same directory as `luapstricks.lua`; instead they are in `.../source/luapstricks`.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.

**Comment by mbertucci47** [comment]
Thanks. The files are still duplicated in `.../source/luapstricks`, though
