### ISSUE TITLE
map-files of tex-gyre are faulty

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#37]
Some of the map-files of the tex-gyre fonts are faulty (qag.map and qpl.map). They contain references to fonts with double extension `.pfb.pfb`, e.g. qag.map:

~~~~
cs-qagr TeXGyreAdventor-Regular "encqcs ReEncodeFont" <q-cs.enc <qagr.pfb.pfb
~~~~

This means that some documents fails

~~~~
\documentclass{article}
\usepackage{tgadventor}
\begin{document}
\sffamily a
\end{document}
~~~~

The problem has already been reported for texlive three days ago 
http://tug.org/pipermail/tex-live/2018-June/041934.html
and has been corrected there but is still present in miktex.

**Comment by edocevoli** [comment]
This will be fixed once CTAN has the corrected sources.

**Comment by u-fischer** [comment]
I wrote to the ctan team.

**Comment by u-fischer** [comment]
The two faulty map-files have been exchanged on CTAN and now wander to the mirrors.
