### ISSUE TITLE
obsolete polyglossia files

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#374]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

MikTeX contains the packages `polyglossia-kannada` and `gloss-occitan` with relevant files `gloss-kannada` and `gloss-occitan`, respectively, however more up-to-date versions of these files are currently packaged with `polyglossia`. So I think those obsolete packages should be removed.

**Comment by edocevoli** [comment]
Thank you, the two packages have been removed. Please check for updates tomorrow.
