### ISSUE TITLE
obsolete files in thailatex package

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#376]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

[`thailatex`](https://www.ctan.org/pkg/thailatex) is packaged with MiKTeX but contains obsolete versions of files correctly found in `babel-thai` and `hyph-utf8`.

**Comment by edocevoli** [comment]
Thank you, I have removed the package. Please check for updates tomorrow.
