### ISSUE TITLE
tikzpingus package files in wrong location

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#377]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The [`tikzpingus`](https://www.ctan.org/pkg/tikzpingus) package requires the library files `tikzpingus-<name>.lib.tex` to be where tex can find them, but currently they are in `.../source/tikzpingus`. That entire folder, except for `tikzpingus-doc.tex`, should be moved to `.../tex/latex/tikzpingus`.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
