### ISSUE TITLE
lparse.tex in wrong location

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#378]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The file `lparse.tex` is the plaintex version of the package [`lparse`](https://ctan.org/pkg/lparse) but is currently located in `.../source/lparse`, where tex cannot find it.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
