### ISSUE TITLE
pgf-spectra package files in wrong location

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#379]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Several files for the [`pgf-spectra`](https://ctan.org/pkg/pgf-spectra) package are in `.../source/pgf-spectra` when they need to be where tex can find them:
- `pgf-spectra.data.LSE.tex`
- `pgf-spectra.data.NIST.tex`
- `pgf-spectra.input.library.tex`
- `pgf-spectra.library.data.tex`
- `pgf-spectra.library.pgfplots.tex`
- `pgf-spectra.library.rainbow.tex`
- `pgf-spectra.library.tempercolor.tex`

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
