### ISSUE TITLE
obsolete ccref package

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#381]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The `ccref` package has been renamed [`crefthe`](https://www.ctan.org/pkg/crefthe) but MiKTeX still contains the old package. It also conflicts with `ccref.sty` from the `computational-complexity` package.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
