### ISSUE TITLE
optex files in wrong location

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#382]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The optex files `emoji.opm`, `math.opm`, `minim.opm`, `minim-mp.opm`, `minim-pdf.opm`, `mte.opm`, `plain-at.opm`, `qrcode.opm`, `tikz.opm`, and `vlna.opm` are packages able to be loaded with `\load[<package>]` but are currently in `.../source/optex/pkg` where tex cannot find them.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by mbertucci47** [comment]
Thanks, the newest update added the files to `.../tex/luatex/optex/pkg`. The files are however still duplicated in `.../source/optex/pkg`.
