### ISSUE TITLE
pgf-periodictable package file in wrong location

### ISSUE THREAD

**Issue by mbertucci47** [MiKTeX/miktex-packaging#383]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Partial recurrence of #335. The file `pgfPT.library.colorschemes.tex` is in `.../source` instead of `.../tex`. I think the name was changed, with a period added after pgfPT.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
