### ISSUE TITLE
MikTex latest windows release?

### ISSUE THREAD

**Issue by trekkiechick** [MiKTeX/miktex-packaging#384]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)
Greetings, I work for a large company that has to individually package each desktop install for vulnerability management and automatic updates to every desktop in the org that impacted.  The latest version on the website has an open CVE associated with it that we are required to remediate else we will have to stop using this product.  Kindly requesting a new windows installer package for 23.5 be added to MikTex website so we can start work on remediation of the open CVE.

**Comment by edocevoli** [comment]
Thank you. A new installer will be released in the near future.
