### ISSUE TITLE
Add `lua-tinyyaml` package

### ISSUE THREAD

**Issue by zepinglee** [MiKTeX/miktex-packaging#385]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Hi! Is it OK to add the `lua-tinyyaml` (<https://ctan.org/pkg/lua-tinyyaml>) package to MiKTeX? This package is in the dependencies of [`citation-style-language`](https://ctan.org/pkg/citation-style-language) (next release), [`markdown`](https://ctan.org/pkg/markdown), and [`yamlvars`](https://ctan.org/pkg/yamlvars). We decided to make it a standalone package for  clearer dependency structure (see <https://github.com/Witiko/markdown/issues/218>).

**Comment by kalekje** [comment]
@edocevoli any update on this?

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by zepinglee** [comment]
Great! Thanks!
