### ISSUE TITLE
latest Miktex release

### ISSUE THREAD

**Issue by trekkiechick** [MiKTeX/miktex-packaging#386]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)
Greetings, previously you indicated that there would be a release "soon", however, in order to continue using this product, we require the release ASAP so we have time to upgrade all machines in our org. Due to the nature of our org, automatic updates are not an option. 
Respectfully request a new windows package on the https://miktex.org/download site for your latest release. We presently have 300+ devices impacted by the lack of a new windows package.

**Comment by edocevoli** [comment]
Thank you. I do my best to release a new installer. It should not take too long. In the meantime, I would recommend that you simply update the luatex binary package in order to get the security fix.
