### ISSUE TITLE
The MiKTeX version is more than a month behind CTAN.

### ISSUE THREAD

**Issue by MarkHoo** [MiKTeX/miktex-packaging#387]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The MiKTeX version is more than a month behind CTAN.

[dvisvgm current version 3.1](https://www.ctan.org/pkg/dvisvgm)

**Comment by edocevoli** [comment]
Binaries are not packaged on a regular basis. It can take a few month, until new versions will be made available.
