### ISSUE TITLE
Package typeoutfileinfo is missing

### ISSUE THREAD

**Issue by petiard** [MiKTeX/miktex-packaging#389]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)
Hello
Le package typeoutfileinfo is not in the MiKTeX distribution but it's in the list of the packages...

Best regards

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
