### ISSUE TITLE
Documentation for Biber

### ISSUE THREAD

**Issue by moewew** [MiKTeX/miktex-packaging#39]
Would it be possible to include `biber.pdf` (http://mirrors.ctan.org/biblio/biber/documentation/biber.pdf) into the Biber package so that `texdoc --view biber` gives the Biber docs?

**Comment by moewew** [comment]
Biber 2.12 has just been uploaded to CTAN. It would be great if the MikTeX package would include the documentation when it is added updated in the next few days.

**Comment by edocevoli** [comment]
Thank you, since `miktex-biber-bin` is a binary (platform-dependent) package, I am planning to add documentation as a separate package (e.g., `biber-doc`), provided that `texdoc --view biber` then works as expected.

**Comment by moewew** [comment]
Great! I'm looking forward to it. Thank you very much.

**Comment by moewew** [comment]
With `biber-doc` installed `texdoc biber` works brilliantly. Thank you very much.
