### ISSUE TITLE
BIBTEX absent

### ISSUE THREAD

**Issue by ttmarco-47** [MiKTeX/miktex-packaging#390]
- [bibtex, installation] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)
my installation of Miktex to new computer does not have provision to run Bibtex (from menu where it is present) and does not recognizes .bib  .bst etc files.
what should I do (or have done?)

**Comment by edocevoli** [comment]
Please follow the [contribution guidelines](https://github.com/MiKTeX/miktex/blob/master/CONTRIBUTING.md) when submitting an issue ticket.
