### ISSUE TITLE
penlightplus - missing penlightplus.lua file

### ISSUE THREAD

**Issue by kalekje** [MiKTeX/miktex-packaging#393]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The critical `penlightplus.lua` file is missing after the `penlightplus` package is installed. https://ctan.org/pkg/penlightplus

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
