### ISSUE TITLE
Include addtoluatexpath package in MiKTeX

### ISSUE THREAD

**Issue by kalekje** [MiKTeX/miktex-packaging#394]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Please include the `addtoluatexpath` package (https://ctan.org/pkg/addtoluatexpath) in MiKTeX.

**Comment by edocevoli** [comment]
It may take a few weeks until new packages are added.
