### ISSUE TITLE
Luacolor package missing file on update

### ISSUE THREAD

**Issue by RealChefSalad** [MiKTeX/miktex-packaging#397]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)
The luacolor package for MiKTeX is missing luacolor.lua, which is a necessary file for the package to work. The previous version had this file, as does the upstream source.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.
