### ISSUE TITLE
Update texlogsieve to 1.3.1

### ISSUE THREAD

**Issue by koppor** [MiKTeX/miktex-packaging#399]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The [texlogsieve](https://ctan.org/pkg/texlogsieve) from MiKTeX is 1.3.0. Meanwhile, 1.3.1 is released: https://gitlab.com/lago/texlogsieve/-/blob/main/CHANGELOG.md?ref_type=heads

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
