### ISSUE TITLE
INSTALL NEW PACKAGE IN MIKTEX

### ISSUE THREAD

**Issue by rasoulpanahi** [MiKTeX/miktex-packaging#4]
How can I install a new package in Miktex?

**Comment by edocevoli** [comment]
You install packages with the help of the MiKTeX package manager. If the package is not yet in the MiKTeX package repository, you can can request its inclusion by creating a new issue.

**Comment by rasoulpanahi** [comment]
Tnx. I used Miktex package manager. It did not work. That was the message: "Could not connect to server". But I know that I have access to Internet. and also when I change depository (To install manually) It does not work.
