### ISSUE TITLE
addtolualatexpath package location change

### ISSUE THREAD

**Issue by kalekje** [MiKTeX/miktex-packaging#400]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Currently, `addtoluatexpath.sty` is located in `texmf/luatex/generic/addtoluatexpath`. Can you please revise this to: `texmf/tex/lualatex/addtoluatexpath`

Thank you

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
