### ISSUE TITLE
missing .fd files from the culmus package

### ISSUE THREAD

**Issue by Udi-Fogiel** [MiKTeX/miktex-packaging#401]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)
The font definition files from the culmus package are missing. They are generated from the .fdd (using an .ins file) that is located in the source directory of the package. I don't know if miktex should also distribute all the source files (.sfd for example) as well.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
