### ISSUE TITLE
penlight package update not appearing

### ISSUE THREAD

**Issue by kalekje** [MiKTeX/miktex-packaging#403]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

This issue was supposedly resolved in https://github.com/MiKTeX/miktex-packaging/issues/392, however, I still see no update appear for penlight https://ctan.org/pkg/penlight

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
