### ISSUE TITLE
tipauni installation is missing files

### ISSUE THREAD

**Issue by mawilson1234** [MiKTeX/miktex-packaging#406]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

The installation of `tipauni` in MikTeX appears to be missing two required fontspec files:

- `tipauni-newcm-regular.fontspec`
- `tipauni-newcm-book.fontspec`

This means that any document loading the `tipauni` package won't compile with the default options, even something as simple as:
```
\documentclass{article}
\usepackage{tipauni}
\begin{document}
\end{document}
```
I'm using XeLaTeX version 4.10 on Windows 10. I've installed the `newcomputermodern` package and run `fc-cache`.

There is a workaround: it's possible to switch back to the old default by loading the package with the `documentfont=CharisSIL` option (or other font of choice). This loads correctly since it doesn't try to access the missing files.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
