### ISSUE TITLE
Auto installation does not work for "currfile"

### ISSUE THREAD

**Issue by koppor** [MiKTeX/miktex-packaging#407]
- [x] I have read and acknowledged this HOWTO article:  
  [Submitting a MiKTeX problem report](https://miktex.org/howto/bug-report)

I compile following file on a new MiKTeX installation:

```latex
\documentclass{article}
\usepackage{currfile}
\begin{document}
text
\end{document}
```

I get

```
(C:\Users\WDAGUtilityAccount\AppData\Local\Programs\MiKTeX\tex/latex/base\size1
0.clo))

! LaTeX Error: File `currfile.sty' not found.
```

Steps to reproduce:

1. Setup new MiKTeX on a new Windows installation. Detailed steps are described at https://github.com/MiKTeX/miktex/issues/1364.
2. Ensure that MiKTeX is up to date.
3. Double check that packages can be installed on the fly\
    ![image](https://github.com/MiKTeX/miktex/assets/1366654/9fd8641e-aefd-4080-b757-63a03e4b1ae4)
4. Execute `pdflatex example-currfile.tex` on the command line.

[miktex-report.txt](https://github.com/MiKTeX/miktex/files/12438547/miktex-report.txt)

The package itself is located at <https://ctan.org/pkg/currfile>.

**Comment by koppor** [comment]
I tried today - and it happens again - https://github.com/koppor/mwe-miktex/actions/runs/7322263405/job/19943580782. CI workflow is available at https://github.com/koppor/mwe-miktex/blob/3618036ff0a321073289d180f83869a1705face1/.github/workflows/miktex.yml#L70 (in case one does not want to start a separate Windows system)

**Comment by LyonsDo** [comment]
Same here Miktex console shows a 0 bytes file.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.
