### ISSUE TITLE
Incorrect GPG keys

### ISSUE THREAD

**Issue by 1point602e-19C** [MiKTeX/miktex-packaging#408]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)
Verifying a signature using certificate D6BC243565B2087BC3F897C9277A7293F59E4889 (MiKTeX Packager <packager@miktex.org>):
Received the folloing message while attempting to upgrade miktex 23.9.24-1.fc37 on fedora 38. Is there a workaround?
  1. Certificiate 277A7293F59E4889 invalid: certificate is not alive
      because: The primary key is not live
      because: Expired on 2023-04-29T15:12:04Z
  2. Key 277A7293F59E4889 invalid: key is not alive
      because: The primary key is not live
      because: Expired on 2023-04-29T15:12:04Z
error: Verifying a signature using certificate D6BC243565B2087BC3F897C9277A7293F59E4889 (MiKTeX Packager <packager@miktex.org>):
  1. Certificiate 277A7293F59E4889 invalid: certificate is not alive
      because: The primary key is not live
      because: Expired on 2023-04-29T15:12:04Z
  2. Key 277A7293F59E4889 invalid: key is not alive
      because: The primary key is not live
      because: Expired on 2023-04-29T15:12:04Z

**Comment by edocevoli** [comment]
you have to install the renewed key in order to fix the issue

**Comment by edocevoli** [comment]
please visit https://miktex.org/download to learn how to register the GPG key

**Comment by 1point602e-19C** [comment]
Thank you, but...
i.) The link you sent me to was for windows; I use Fedora37.
ii.) Clicked on the Linux/Fedora tabs and found
     a. Register GPG key
           sudo rpm --import "https://miktex.org/download/key"  (Done)
      b. Register installation source 
            Fedora 37: sudo curl -L -o /etc/yum.repos.d/miktex.repo https://miktex.org/download/fedora/37/miktex.repo (Done. Received
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   109  100   109    0     0    201      0 --:--:-- --:--:-- --:--:--   201)
        c. Install MiKTeX   (Already installed)
         d. sudo dnf update  (Update fails yielding the error message posted above in the original message pf this thread)
         e. Finish the setup -Start MiKTeX Console to finish the setup (Done: 1048 items updated.)
Miktex still shows up in every new list of updates for Fedora 38, yielding the error message above and preventing an automatic update through Discover Software Center. This causes the (admittedly minor) problem of forcing a dnf upgrade --exclude miktex to complete the update.

Thank you for your patience.
