### ISSUE TITLE
Adding sn-article-template to MikTex packages 

### ISSUE THREAD

**Issue by santiago-schnell** [MiKTeX/miktex-packaging#409]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

I would like to suggest to include the new Springer-Nature LaTeX template, sn-article-template, to MikTex:

https://www.springernature.com/gp/authors/campaigns/latex-author-support

[Download+the+journal+article+template+package.zip](https://github.com/MiKTeX/miktex-packaging/files/12775560/Download%2Bthe%2Bjournal%2Barticle%2Btemplate%2Bpackage.zip)

**Comment by edocevoli** [comment]
impeded - it's not on CTAN yet
