### ISSUE TITLE
New fontspec-Package 2.6i is needed

### ISSUE THREAD

**Issue by Matthiasss** [MiKTeX/miktex-packaging#41]
Now hopefully at the right place:

The bug in Fontspec 2.6h is known and Will have fixed it in 2.6i available on CTAN. But I cant it use for MikTeX, the special MikTeX-package is needed. I would quite grateful for this because it is little bit urgent. 

Thank you and regards,
Matthias

**Comment by edocevoli** [comment]
Thank you, this has been fixed: tomorrows MiKTeX updates installs the latest fontspec version.

**Comment by Matthiasss** [comment]
Thank you very much for fast help: its saved my deadline ...
