### ISSUE TITLE
Expired key

### ISSUE THREAD

**Issue by 1point602e-19C** [MiKTeX/miktex-packaging#410]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)
Certificiate 277A7293F59E4889 invalid: certificate is not alive
      because: The primary key is not live
      because: Expired on 2023-04-29T15:12:04Z
How do I find the current key?
How do I install it?

**Comment by edocevoli** [comment]
see #408
