### ISSUE TITLE
Update via MikTeX Console does not work

### ISSUE THREAD

**Issue by nmm71** [MiKTeX/miktex-packaging#413]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)
        (tldr)

- [x] after install MikTeX 23.10 (on a Windoes 10 system, install for one user only), i started the Console and pressed "search fopr updates".
- [x] it found a lot of updates pending
- [x] i choosed "start update"
- [x] update started, but stopped at about 10 %: the console was "suspendet" by Windows
- [x] i restat Windows
- [x]  if I now start the console again, it crashes with an error-Message, that sone DLL was not found.
- [x] reinstall V23.10 does nor work: also missing DLLs-Error
- [x] i deleted the whole MikTex-directory (in apdata\local\Programms) and reinstalled it from scratch
- [x] now MikTex wokrs again, but one can not use "update any more

What can I do?

(the same Problem appeared in Version 21.x).

**Comment by edocevoli** [comment]
Sorry, but I can't fix this issue.
