### ISSUE TITLE
fancytooltips files in wrong place

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#415]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

In the fancytooltips package some files are installed in the wrong folder:
the files fancytipmark.pdf,  fancytipmark1.pdf, fancytipmark2.pdf, fancytipmark3.pdf, fancytipmark4.pdf, fancytipmark.eps and (probably) fancytipmark.svg are needed for the compilation and should be in tex/latex/fancytooltips and not in the doc folder. 

(texlive doesn't do it right either, there only fancytipmark.pdf/eps/svg is in texlive but the PDF's with numbers are missing. I will make a report there too).

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
