### ISSUE TITLE
Fehlendes "icuuc74.dll"

### ISSUE THREAD

**Issue by Confluentius** [MiKTeX/miktex-packaging#417]
Nach dem aktuellen Update meldet xelatex, dass "icuuc74.dll" nicht gefunden wurde und bricht ab.
In "miktex\bin\x64" ist nur die bisherige Version "icuuc72.dll" zu finden.

**Comment by edocevoli** [comment]
this is a known: https://github.com/MiKTeX/miktex/issues/1421
