### ISSUE TITLE
Missing all `.pfb` files from the `arabi` package

### ISSUE THREAD

**Issue by younesaassila** [MiKTeX/miktex-packaging#420]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Hello,
All `.pfb` files from the `arabi` package (https://ctan.org/pkg/arabi) are missing. Could this be fixed?
Let me know if you need additional information. Thanks

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
