### ISSUE TITLE
issue after updating

### ISSUE THREAD

**Issue by alairoua** [MiKTeX/miktex-packaging#421]
Afer updating  miktex on 01/07/2024, I cannot compile files. I received the message
Loading 'l3backend-pdftex.def' aborted!
(LaTeX)        
(LaTeX)        The L3 programming layer in the LaTeX format
(LaTeX)        is dated 2023-06-30, but in your TeX tree the files require
(LaTeX)        at least 2023-10-10.
Please tell me how to fix this issue.

Thanks,

Alain Rouault

**Comment by edocevoli** [comment]
I was not able to reproduce this with the given info.
