### ISSUE TITLE
portable installation fails

### ISSUE THREAD

**Issue by Pfiffikus** [MiKTeX/miktex-packaging#423]
Running miktex-portable.exe ends with following error messages:

`:
26 [0x00009088] INFO initexmf null - this is MiKTeX Configuration Utility 5.4 (MiKTeX 23.10) 27 [0x00009088] INFO initexmf null - this process (44224) started by miktex-portable in directory C:\Users\lau\Downloads with command line: initexmf --principal=setup --portable=I:\a403\PortableApps\miktex-portable\texmfs/install --disable-installer --verbose 27 [0x00009088] INFO initexmf null - Operating on the private (per-user) MiKTeX setup 27 [0x00009088] INFO initexmf null - Creating portable setup... Creating portable setup...
60 [0x00009088] INFO initexmf null - this process (44224) finishes with exit code 0 Removing I:\a403\PortableApps\miktex-portable\texmfs\config\miktex\data\le\texmf.fndb-5...

Sorry, but: Windows API error 3: Das System kann den angegebenen Pfad nicht finden. 
Warning: Windows API error 3: Das System kann den angegebenen Pfad nicht finden.
Operating on the private (per-user) MiKTeX setup
Creating FNDB for common root directory (I:\a403\PortableApps\miktex-portable\texmfs\config)...
Creating FNDB for common root directory (I:\a403\PortableApps\miktex-portable\texmfs\data)...
Creating FNDB for common root directory (I:\a403\PortableApps\miktex-portable\texmfs\install)...
Refreshing FNDB for MPM...

Sorry, but: Windows API error 995: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen. 
Warning: Windows API error 995: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen.

Sorry, but: Windows API error 995: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen. 
Warning: Windows API error 995: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen.

Sorry, but: Windows API error 995: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen. 
Warning: Windows API error 995: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen.

Sorry, but: Windows API error 995: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen. 
Warning: Windows API error 995: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen.
Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen. 
Function: ReadDirectoryChangesW
Result: 995
Data: path="I:\a403\PortableApps\miktex-portable\texmfs/config\miktex/data/le\"
Source: Libraries\MiKTeX\Core\FileSystemWatcher\win\winFileSystemWatcher.cpp:150
Windows API error 995: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen. 
Info: path="I:\a403\PortableApps\miktex-portable\texmfs/config\miktex/data/le\"
Source: Libraries\MiKTeX\Core\FileSystemWatcher\win\winFileSystemWatcher.cpp
Line: 150

Sorry, but "MiKTeX Configuration Utility" did not succeed.
log4cxx: No appender could be found for logger (initexmf).
log4cxx: Please initialize the log4cxx system properly.
Warning: Windows API error 995: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen.
Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen. 
Function: ReadDirectoryChangesW
Result: 995
Data: path="I:\a403\PortableApps\miktex-portable\texmfs/config\miktex/data/le\"
Source: Libraries\MiKTeX\Core\FileSystemWatcher\win\winFileSystemWatcher.cpp:150
Windows API error 995: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen. 
Info: path="I:\a403\PortableApps\miktex-portable\texmfs/config\miktex/data/le\"
Source: Libraries\MiKTeX\Core\FileSystemWatcher\win\winFileSystemWatcher.cpp
Line: 150

Sorry, but "MiKTeX Configuration Utility" did not succeed.
log4cxx: No appender could be found for logger (initexmf).
log4cxx: Please initialize the log4cxx system properly.
Warning: Windows API error 995: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen.

Sorry, but: Windows API error 995: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen. 
Warning: Windows API error 995: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen.
Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen. 
Function: ReadDirectoryChangesW
Result: 995
Data: path="I:\a403\PortableApps\miktex-portable\texmfs/config\miktex/data/le\"
Source: Libraries\MiKTeX\Core\FileSystemWatcher\win\winFileSystemWatcher.cpp:150
Windows API error 995: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen. 
Info: path="I:\a403\PortableApps\miktex-portable\texmfs/config\miktex/data/le\"
Source: Libraries\MiKTeX\Core\FileSystemWatcher\win\winFileSystemWatcher.cpp
Line: 150

Sorry, but "MiKTeX Configuration Utility" did not succeed.
log4cxx: No appender could be found for logger (initexmf).
log4cxx: Please initialize the log4cxx system properly.
Warning: Windows API error 995: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen.
`
How to fix this?

**Comment by edocevoli** [comment]
Thank you for the report. Because I cannot reproduce the defect I cannot work on this effectively.
