### ISSUE TITLE
latex-lab-dev installation is wrong

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#425]
The files from the latex-lab-dev package have been installed in `tex/latex/latex-lab-dev` instead of the correct `tex/latex-dev/latex-lab`.
That means that they are now beside the normal `latex-lab` and it is undefined which files are used from the two bundle if you run latex(-dev).

![image](https://github.com/MiKTeX/miktex-packaging/assets/4047173/8c0c1361-9385-4f17-94a8-96571181eb5d)

![image](https://github.com/MiKTeX/miktex-packaging/assets/4047173/d5da8869-cdc1-4320-b158-760763c204e6)

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
