### ISSUE TITLE
font catalog heuristic font installing files in wrong location in miktex

### ISSUE THREAD

**Issue by leogsmat** [MiKTeX/miktex-packaging#427]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

I used the heuristic source in my work, but I had to format my PC and when I reinstalled miktex and textstuidio (in that order inclusive) my file that was running normally presented this error.

!pdfTeX error: pdflatex.exe (zut_5b7xz5.enc file): cannot open encoding file for reading

I've updated miktex several times and the error persisted, I created an MWE and the error persists, but the code changed:

!pdfTeX error: pdflatex.exe (zut_geqeyh.enc file): Unable to open encoding file for reading.

In the TEX group they told me that for some reason miktex is installing these files in the wrong location and asked me to talk to you.

Do I have to manually install files from this source? How can I do this? Where are they located? I need to use sudo.

Can someone help me!

**Comment by leogsmat** [comment]
Será que tenho que instalar manualmente os arquivos dessa fonte? Como posso fazer isso? Em que local elas ficam? Preciso usar o sudo. 

Alguém pode me ajudar!

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
