### ISSUE TITLE
Misplaced files in pgf-PeriodicTable (v2.1.0) MiKTeX Package

### ISSUE THREAD

**Issue by HugoPGomes** [MiKTeX/miktex-packaging#428]
<p dir="auto">In current MiKTeX Packages:</p>
<table role="table" border="1">
<tbody>
<tr>
<td>pgf-periodictable</td>
<td>Create custom periodic tables of elements&nbsp;</td>
<td>02/16/2024 2.1.0 lppl1.3</td>
</tr>
<tr>
<td>pgf-periodictable__doc</td>
<td>Create custom periodic tables of elements</td>
<td>02/16/2024 2.1.0 lppl1.3</td>
</tr>
<tr>
<td>pgf-periodictable__source</td>
<td>Create custom periodic tables of elements</td>
<td>02/16/2024 2.1.0 lppl1.3</td>
</tr>
</tbody>
</table>
<p dir="auto">some files are misplaced:</p>
<table role="table" border="1">
<tbody>
<tr>
<td>filename</td>
<td>current directory</td>
<td>should be in the directory</td>
</tr>
<tr>
<td>lang.nl.tex</td>
<td>texmf\source\pgf-periodictable\translations</td>
<td>texmf\tex\latex\pgf-periodictable\translations</td>
</tr>
<tr>
<td>lang.undefined.tex</td>
<td>texmf\source\pgf-periodictable\translations</td>
<td>texmf\tex\latex\pgf-periodictable\translations</td>
</tr>
</tbody>
</table>
<p dir="auto">The file pgf-PeriodicTable.sty input this files.</p>
<p dir="auto">Thanks,</p>
<p dir="auto">Hugo Gomes</p>```

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by HugoPGomes** [comment]
Hi Christian,

I checked for the files 'pgfPT.lang.nl.tex' and 'pgfPT.lang.undefined.tex'
and they are still in 'texmf\source\pgf-periodictable\translations' instead
of 'texmf\tex\latex\pgf-periodictable\translations'.
Thanks in advance,
Best regards,
Hugo Gomes

Christian Schenk ***@***.***> escreveu (sábado, 18/05/2024
à(s) 11:54):
