### ISSUE TITLE
Font maps for manfnt missing

### ISSUE THREAD

**Issue by moewew** [MiKTeX/miktex-packaging#43]
It seems to me as though the font maps files for `manfnt` are missing.

When I compile
```latex
\documentclass{article}
\usepackage{manfnt}
\begin{document}
\dbend
\end{document}
```
I obtain the rasterised bitmap font output instead of vector type 1 fonts.

This seems to be similar to https://tex.stackexchange.com/q/209691/35864 and indeed in the file list https://miktex.org/Package/Browse/manfnt no map files are listed.

**Comment by edocevoli** [comment]
I have added package `manfnt-type1` which contains the missing files. It will be available with the next update.

**Comment by moewew** [comment]
Thank you. Things work fine when `manfnt-type1` is installed.

Is there any reason why the font files are not included directly in `manfnt`?

**Comment by edocevoli** [comment]
`manfnt` originates from CTAN and this package only contains the LaTeX support files.

**Comment by moewew** [comment]
Ah yes, that makes sense. I thought when I originally wrote this report I looked up that `manfnt` on CTAN also contained the font maps, but that is evidently wrong. Sorry for the confusion.
