### ISSUE TITLE
issue with the current update on Windows 10

### ISSUE THREAD

**Issue by JeromeSavoie** [MiKTeX/miktex-packaging#431]
Hello,
I regularly update MiKTeX on my PC (OS Windows 10).
The current update makes MiKTeX impossible to run and even impossible to uninstall !
The error message is the following : 
<img width="305" alt="miktex" src="https://github.com/MiKTeX/miktex-packaging/assets/168889575/74a31273-436c-4d30-b23a-cca93e9cd9f5">
I will have to use Revo uninstaller and reinstall an older version of MiKTeX.
Is there another solution ?

**Comment by edocevoli** [comment]
This is a known issue. Please check the MiKTeX issue tracker.
