### ISSUE TITLE
Repository Change error

### ISSUE THREAD

**Issue by NicholasJ81** [MiKTeX/miktex-packaging#433]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)
After a long time, I tried to update my MIkTex from the console. Then it says 
**GENERAL MIKTEX INFORMATION
ReportDate: 2024-05-15 08:34:44
CurrentVersion: 22.3
SetupDate: 2022-05-09 04:16:00
SetupVersion: 2.9
Configuration: Regular
GitInfo: 5bfe728 / 2022-03-29 11:22:26
OS: Windows 8.1 Enterprise, 64-bit, build 9600
SharedSetup: no
.......
PathOkay: yes
LastUpdateCheck: 2022-05-20 03:32:13
LastUpdate: 2022-05-20 03:27:15
LastUpdateDb: 2022-05-20 03:32:09
SystemAdmin: yes
RootPrivileges: yes
AdminMode: no
........

The following issues were detected:
  1: minor issue: It has been a long time since you have checked for MiKTeX updates.

ERROR DETAILS
Program: miktex-console
Source: Libraries\MiKTeX\PackageManager\CurlWebSession.cpp:247
Error: SSL connect error
Details: 
  code: 35
  url: https://api2.miktex.org/hello**

So I tried the option of changing the package repository hosts. But the console is not displaying any list of hosts.
PLease help me to update my MIkTex. Thank you.

**Comment by edocevoli** [comment]
I am afraid, updating such an old version is not possible. You can try the command line tool `miktex packages ...` to upgrade packages. Maybe this works.

**Comment by NicholasJ81** [comment]
please give me the complete command line code to update the packages. Thank you
