### ISSUE TITLE
Babel Scottish Gaelic problem continues.

### ISSUE THREAD

**Issue by hsmyers** [MiKTeX/miktex-packaging#434]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

ReportDate: 2024-05-18 13:52:59
CurrentVersion: 24.4
SetupDate: 2024-05-18 13:41:00
SetupVersion: 24.1
Configuration: Regular
GitInfo: e3580c6 / 2024-04-27 18:01:25
OS: Windows 10.0.26120
SharedSetup: no
LinkTargetDirectory: C:\Users\hsmye\AppData\Local\Programs\MiKTeX\miktex\bin\x64
PathOkay: yes
LastUpdateCheck: 2024-05-18 13:41:47
LastUpdate: 2024-05-18 13:42:52
LastUpdateDb: 2024-05-18 13:41:45
SystemAdmin: yes
RootPrivileges: no
AdminMode: no
Root0: C:\Users\hsmye\AppData\Roaming\MiKTeX
Root1: C:\Users\hsmye\AppData\Local\MiKTeX
Root2: C:\Users\hsmye\AppData\Local\Programs\MiKTeX
UserInstall: C:\Users\hsmye\AppData\Local\Programs\MiKTeX
UserConfig: C:\Users\hsmye\AppData\Roaming\MiKTeX
UserData: C:\Users\hsmye\AppData\Local\MiKTeX

You may think this is fixed, but a fresh copy of MiKTeX says no. Here is the badly formated message:

[{
"resource": "/C:/Users/hsmye/AppData/Local/Programs/MiKTeX/tex/latex/babel-scottish/scottishgaelic.ldf",
"owner": "LaTeX",
"severity": 4,
"message": "Package babel: No hyphenation patterns were preloaded for\n(babel)\tthe language 'Scottish Gaelic' into the format.\n(babel)\tPlease, configure your TeX system to add them and\n(babel)\trebuild the format. Now I will use the patterns\n(babel)\tpreloaded for \language=0 instead.",
"source": "LaTeX",
"startLineNumber": 41,
"startColumn": 1,
"endLineNumber": 41,
"endColumn": 65536
}]

If this is a poorly phrased way of saying I need to rebuild the format, then I will do so and try again, but it seems to me that when your software downloads something, you should finish the install. 

I just attempted to rebuild, except I do not know how with the console and am equally ignorant with the command line.

Hugh Shannon Myers

**Comment by hsmyers** [comment]
Another attempt to update crashed by an unrelated problem. From your log file:

2024-05-18 14:34:17,796-0600 INFO  initexmf - this is MiKTeX Configuration Utility 5.5 (MiKTeX 24.4)
2024-05-18 14:34:17,797-0600 INFO  initexmf - this process (23836) started by cmd in directory C:\Users\hsmye with command line: initexmf --dump
2024-05-18 14:34:17,797-0600 INFO  initexmf - Operating on the private (per-user) MiKTeX setup
2024-05-18 14:34:17,801-0600 INFO  initexmf - running: miktex formats build
2024-05-18 14:34:17,801-0600 INFO  initexmf.core - start process: miktex formats build
2024-05-18 14:37:55,949-0600 ERROR initexmf - sub-process error output has been saved to 'C:\Users\hsmye\AppData\Local\MiKTeX\miktex\log\miktex_2024-05-18-143755.out'
2024-05-18 14:37:55,950-0600 FATAL initexmf - Windows API error 2: The system cannot find the file specified.
2024-05-18 14:37:55,950-0600 FATAL initexmf - Info: existing="C:\Users\hsmye\AppData\Local\Temp\mik64608\hilatex-dev.fmt", path="C:\Users\hsmye\AppData\Local\MiKTeX\miktex/data/le/hitex\hilatex-dev.fmt"
2024-05-18 14:37:55,950-0600 FATAL initexmf - Source: Libraries\MiKTeX\Core\File\win\winFile.cpp
2024-05-18 14:37:55,950-0600 FATAL initexmf - Line: 376
2024-05-18 14:37:55,950-0600 INFO  initexmf - this process (23836) finishes with exit code 1

Hugh Shannon Myers

**Comment by edocevoli** [comment]
This is a dup of #430. I am closing these issues because they do not contain relevant log files.

**Comment by edocevoli** [comment]
Please attach log files and I reopen the issue.

**Comment by hsmyers** [comment]
This MWE produces the warning that follows.

\documentclass{report}
\usepackage{fontspec}
\usepackage{array}
\usepackage{geometry}
\usepackage[scottish]{datetime2}
\usepackage{booktabs}
\usepackage[table,x11names]{xcolor}
\usepackage[scottish, english]{babel}

\begin{document}
\chapter*{Prepositional Pronouns in Gàidhlig\footnote{%
This is prep-pro.pdf, generated from prep-pro.tex, Version 0.0.018, \DTMnow.%
}
}
\end{document}

[{
	"resource": "/C:/Users/hsmye/AppData/Local/Programs/MiKTeX/tex/latex/babel-scottish/scottishgaelic.ldf",
	"owner": "LaTeX",
	"severity": 4,
	"message": "Package babel: No hyphenation patterns were preloaded for\n(babel)\tthe language 'Scottish Gaelic' into the format.\n(babel)\tPlease, configure your TeX system to add them and\n(babel)\trebuild the format. Now I will use the patterns\n(babel)\tpreloaded for \\language=0 instead.",
	"source": "LaTeX",
	"startLineNumber": 41,
	"startColumn": 1,
	"endLineNumber": 41,
	"endColumn": 65536
}]

When I try and fix the problem I get the following in the log.

2024-05-18 14:34:17,796-0600 INFO initexmf - this is MiKTeX Configuration Utility 5.5 (MiKTeX 24.4)
2024-05-18 14:34:17,797-0600 INFO initexmf - this process (23836) started by cmd in directory C:\Users\hsmye with command line: initexmf --dump
2024-05-18 14:34:17,797-0600 INFO initexmf - Operating on the private (per-user) MiKTeX setup
2024-05-18 14:34:17,801-0600 INFO initexmf - running: miktex formats build
2024-05-18 14:34:17,801-0600 INFO initexmf.core - start process: miktex formats build
2024-05-18 14:37:55,949-0600 ERROR initexmf - sub-process error output has been saved to 'C:\Users\hsmye\AppData\Local\MiKTeX\miktex\log\miktex_2024-05-18-143755.out'
2024-05-18 14:37:55,950-0600 FATAL initexmf - Windows API error 2: The system cannot find the file specified.
2024-05-18 14:37:55,950-0600 FATAL initexmf - Info: existing="C:\Users\hsmye\AppData\Local\Temp\mik64608\hilatex-dev.fmt", path="C:\Users\hsmye\AppData\Local\MiKTeX\miktex/data/le/hitex\hilatex-dev.fmt"
2024-05-18 14:37:55,950-0600 FATAL initexmf - Source: Libraries\MiKTeX\Core\File\win\winFile.cpp
2024-05-18 14:37:55,950-0600 FATAL initexmf - Line: 376
2024-05-18 14:37:55,950-0600 INFO initexmf - this process (23836) finishes with exit code 1

Here is the log file from XeLaTeX.

This is XeTeX, Version 3.141592653-2.6-0.999996 (MiKTeX 24.4) (preloaded format=xelatex 2024.5.18)  19 MAY 2024 09:13
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**./mwe-1.tex
(mwe-1.tex
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2024-04-11>
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/base\report.cls
Document Class: report 2023/05/17 v1.4n Standard LaTeX document class
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/base\size10.clo
File: size10.clo 2023/05/17 v1.4n Standard LaTeX file (size option)
)
\c@part=\count185
\c@chapter=\count186
\c@section=\count187
\c@subsection=\count188
\c@subsubsection=\count189
\c@paragraph=\count190
\c@subparagraph=\count191
\c@figure=\count192
\c@table=\count193
\abovecaptionskip=\skip48
\belowcaptionskip=\skip49
\bibindent=\dimen140
)
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/fontspec\fontspec.sty
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/l3packages/xparse\xpars
e.sty
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/l3kernel\expl3.sty
Package: expl3 2024-04-11 L3 programming layer (loader) 

(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/l3backend\l3backend-xet
ex.def
File: l3backend-xetex.def 2024-04-11 L3 backend support: XeTeX
\g__graphics_track_int=\count194
\l__pdf_internal_box=\box51
\g__pdf_backend_annotation_int=\count195
\g__pdf_backend_link_int=\count196
))
Package: xparse 2024-03-14 L3 Experimental document command parser
)
Package: fontspec 2024/05/07 v2.9d Font selection for XeLaTeX and LuaLaTeX

(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/fontspec\fontspec-xetex
.sty
Package: fontspec-xetex 2024/05/07 v2.9d Font selection for XeLaTeX and LuaLaTe
X
\l__fontspec_script_int=\count197
\l__fontspec_language_int=\count198
\l__fontspec_strnum_int=\count199
\l__fontspec_tmp_int=\count266
\l__fontspec_tmpa_int=\count267
\l__fontspec_tmpb_int=\count268
\l__fontspec_tmpc_int=\count269
\l__fontspec_em_int=\count270
\l__fontspec_emdef_int=\count271
\l__fontspec_strong_int=\count272
\l__fontspec_strongdef_int=\count273
\l__fontspec_tmpa_dim=\dimen141
\l__fontspec_tmpb_dim=\dimen142
\l__fontspec_tmpc_dim=\dimen143
 (C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/base\fontenc.sty
Package: fontenc 2021/04/29 v2.0v Standard LaTeX package
)
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/fontspec\fontspec.cfg))
) (C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/tools\array.sty
Package: array 2023/10/16 v2.5g Tabular extension package (FMi)
\col@sep=\dimen144
\ar@mcellbox=\box52
\extrarowheight=\dimen145
\NC@list=\toks17
\extratabsurround=\skip50
\backup@length=\skip51
\ar@cellbox=\box53
)
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/geometry\geometry.sty
Package: geometry 2020/01/02 v5.9 Page Geometry

(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/graphics\keyval.sty
Package: keyval 2022/05/29 v1.15 key=value parser (DPC)
\KV@toks@=\toks18
)
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/generic/iftex\ifvtex.sty
Package: ifvtex 2019/10/25 v1.7 ifvtex legacy package. Use iftex instead.

(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/generic/iftex\iftex.sty
Package: iftex 2022/02/03 v1.0f TeX engine tests
))
\Gm@cnth=\count274
\Gm@cntv=\count275
\c@Gm@tempcnt=\count276
\Gm@bindingoffset=\dimen146
\Gm@wd@mp=\dimen147
\Gm@odd@mp=\dimen148
\Gm@even@mp=\dimen149
\Gm@layoutwidth=\dimen150
\Gm@layoutheight=\dimen151
\Gm@layouthoffset=\dimen152
\Gm@layoutvoffset=\dimen153
\Gm@dimlist=\toks19

(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/geometry\geometry.cfg))

(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/datetime2\datetime2.sty
Package: datetime2 2021/03/21 v1.5.7 (NLCT) date and time formats

(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/tracklang\tracklang.sty
Package: tracklang 2022/12/13 v1.6.1 (NLCT) Track Languages

(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/generic/tracklang\tracklang.t
ex))
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/etoolbox\etoolbox.sty
Package: etoolbox 2020/10/05 v2.5k e-TeX tools for LaTeX (JAW)
\etb@tempcnta=\count277
)
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/xkeyval\xkeyval.sty
Package: xkeyval 2022/06/16 v2.9 package option processing (HA)

(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/generic/xkeyval\xkeyval.tex
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/generic/xkeyval\xkvutils.tex
\XKV@toks=\toks20
\XKV@tempa@toks=\toks21
)
\XKV@depth=\count278
File: xkeyval.tex 2014/12/03 v2.7a key=value parser (HA)
))
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/datetime2-scottish\date
time2-scottish.ldf
File: datetime2-scottish.ldf 2019/09/14 v1.0

(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/generic/iftex\ifxetex.sty
Package: ifxetex 2019/10/25 v0.7 ifxetex legacy package. Use iftex instead.
)
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/generic/iftex\ifluatex.sty
Package: ifluatex 2019/10/25 v1.5 ifluatex legacy package. Use iftex instead.
)
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/datetime2-scottish\date
time2-scottish-utf8.ldf
File: datetime2-scottish-utf8.ldf 2019/09/14 v1.0
)))
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/booktabs\booktabs.sty
Package: booktabs 2020/01/12 v1.61803398 Publication quality tables
\heavyrulewidth=\dimen154
\lightrulewidth=\dimen155
\cmidrulewidth=\dimen156
\belowrulesep=\dimen157
\belowbottomsep=\dimen158
\aboverulesep=\dimen159
\abovetopsep=\dimen160
\cmidrulesep=\dimen161
\cmidrulekern=\dimen162
\defaultaddspace=\dimen163
\@cmidla=\count279
\@cmidlb=\count280
\@aboverulesep=\dimen164
\@belowrulesep=\dimen165
\@thisruleclass=\count281
\@lastruleclass=\count282
\@thisrulewidth=\dimen166
)
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/xcolor\xcolor.sty
Package: xcolor 2023/11/15 v3.01 LaTeX color extensions (UK)

(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/graphics-cfg\color.cfg
File: color.cfg 2016/01/02 v1.6 sample color configuration
)
Package xcolor Info: Driver file: xetex.def on input line 274.
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/graphics-def\xetex.def
File: xetex.def 2022/09/22 v5.0n Graphics/color driver for xetex
) (C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/graphics\mathcolor.lt
x)
Package xcolor Info: Model `cmy' substituted by `cmy0' on input line 1350.
Package xcolor Info: Model `RGB' extended on input line 1366.
Package xcolor Info: Model `HTML' substituted by `rgb' on input line 1368.
Package xcolor Info: Model `Hsb' substituted by `hsb' on input line 1369.
Package xcolor Info: Model `tHsb' substituted by `hsb' on input line 1370.
Package xcolor Info: Model `HSB' substituted by `hsb' on input line 1371.
Package xcolor Info: Model `Gray' substituted by `gray' on input line 1372.
Package xcolor Info: Model `wave' substituted by `hsb' on input line 1373.
)
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/colortbl\colortbl.sty
Package: colortbl 2024/02/20 v1.0g Color table columns (DPC)
\everycr=\toks22
\minrowclearance=\skip52
\rownum=\count283
)
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/xcolor\x11nam.def
File: x11nam.def 2023/11/15 v3.01 Predefined colors according to Unix/X11 (UK)
)
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/generic/babel\babel.sty
Package: babel 2024/04/20 v24.4 The Babel package
\babel@savecnt=\count284
\U@D=\dimen167
\l@unhyphenated=\language79

(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/generic/babel\xebabel.def)
\bbl@readstream=\read2
\bbl@dirlevel=\count285

*************************************
* Local config file bblopts.cfg used
*
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/arabi\bblopts.cfg
File: bblopts.cfg 2005/09/08 v0.1 add Arabic and Farsi to "declared" options of
 babel
)
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/babel-scottish\scottish
.ldf
Language: scottish 2024/01/27 v1.0h Scottish support from the babel system

(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/babel-scottish\scottish
gaelic.ldf
Language: scottishgaelic 2024/01/27 v1.0h Scottish support from the babel syste
m


Package babel Warning: No hyphenation patterns were preloaded for
(babel)                the language 'Scottish Gaelic' into the format.
(babel)                Please, configure your TeX system to add them and
(babel)                rebuild the format. Now I will use the patterns
(babel)                preloaded for \language=0 instead on input line 41.

Package babel Info: Hyphen rules for 'scottishgaelic' set to \l@english
(babel)             (\language0). Reported on input line 42.
))
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/babel-english\english.l
df
Language: english 2017/06/06 v3.3r English support from the babel system
Package babel Info: Hyphen rules for 'canadian' set to \l@english
(babel)             (\language0). Reported on input line 102.
Package babel Info: Hyphen rules for 'australian' set to \l@ukenglish
(babel)             (\language73). Reported on input line 105.
Package babel Info: Hyphen rules for 'newzealand' set to \l@ukenglish
(babel)             (\language73). Reported on input line 108.
))
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/generic/babel/locale/en\babel
-english.tex
Package babel Info: Importing font and identification data for english
(babel)             from babel-en.ini. Reported on input line 11.
)
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/generic/babel/locale/gd\babel
-scottish.tex
Package babel Info: Importing font and identification data for scottish
(babel)             from babel-gd.ini. Reported on input line 11.
)
No file mwe-1.aux.
\openout1 = `mwe-1.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 10.
LaTeX Font Info:    ... okay on input line 10.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 10.
LaTeX Font Info:    ... okay on input line 10.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 10.
LaTeX Font Info:    ... okay on input line 10.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 10.
LaTeX Font Info:    ... okay on input line 10.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 10.
LaTeX Font Info:    Trying to load font information for TS1+cmr on input line 1
0.
(C:\Users\hsmye\AppData\Local\Programs\MiKTeX\tex/latex/base\ts1cmr.fd
File: ts1cmr.fd 2023/04/13 v2.5m Standard LaTeX font definitions
)
LaTeX Font Info:    ... okay on input line 10.
LaTeX Font Info:    Checking defaults for TU/lmr/m/n on input line 10.
LaTeX Font Info:    ... okay on input line 10.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 10.
LaTeX Font Info:    ... okay on input line 10.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 10.
LaTeX Font Info:    ... okay on input line 10.

Package fontspec Info: 
(fontspec)             Adjusting the maths setup (use [no-math] to avoid
(fontspec)             this).

\symlegacymaths=\mathgroup4
LaTeX Font Info:    Overwriting symbol font `legacymaths' in version `bold'
(Font)                  OT1/cmr/m/n --> OT1/cmr/bx/n on input line 10.
LaTeX Font Info:    Redeclaring math accent \acute on input line 10.
LaTeX Font Info:    Redeclaring math accent \grave on input line 10.
LaTeX Font Info:    Redeclaring math accent \ddot on input line 10.
LaTeX Font Info:    Redeclaring math accent \tilde on input line 10.
LaTeX Font Info:    Redeclaring math accent \bar on input line 10.
LaTeX Font Info:    Redeclaring math accent \breve on input line 10.
LaTeX Font Info:    Redeclaring math accent \check on input line 10.
LaTeX Font Info:    Redeclaring math accent \hat on input line 10.
LaTeX Font Info:    Redeclaring math accent \dot on input line 10.
LaTeX Font Info:    Redeclaring math accent \mathring on input line 10.
LaTeX Font Info:    Redeclaring math symbol \colon on input line 10.
LaTeX Font Info:    Redeclaring math symbol \Gamma on input line 10.
LaTeX Font Info:    Redeclaring math symbol \Delta on input line 10.
LaTeX Font Info:    Redeclaring math symbol \Theta on input line 10.
LaTeX Font Info:    Redeclaring math symbol \Lambda on input line 10.
LaTeX Font Info:    Redeclaring math symbol \Xi on input line 10.
LaTeX Font Info:    Redeclaring math symbol \Pi on input line 10.
LaTeX Font Info:    Redeclaring math symbol \Sigma on input line 10.
LaTeX Font Info:    Redeclaring math symbol \Upsilon on input line 10.
LaTeX Font Info:    Redeclaring math symbol \Phi on input line 10.
LaTeX Font Info:    Redeclaring math symbol \Psi on input line 10.
LaTeX Font Info:    Redeclaring math symbol \Omega on input line 10.
LaTeX Font Info:    Redeclaring math symbol \mathdollar on input line 10.
LaTeX Font Info:    Redeclaring symbol font `operators' on input line 10.
LaTeX Font Info:    Encoding `OT1' has changed to `TU' for symbol font
(Font)              `operators' in the math version `normal' on input line 10.
LaTeX Font Info:    Overwriting symbol font `operators' in version `normal'
(Font)                  OT1/cmr/m/n --> TU/lmr/m/n on input line 10.
LaTeX Font Info:    Encoding `OT1' has changed to `TU' for symbol font
(Font)              `operators' in the math version `bold' on input line 10.
LaTeX Font Info:    Overwriting symbol font `operators' in version `bold'
(Font)                  OT1/cmr/bx/n --> TU/lmr/m/n on input line 10.
LaTeX Font Info:    Overwriting symbol font `operators' in version `normal'
(Font)                  TU/lmr/m/n --> TU/lmr/m/n on input line 10.
LaTeX Font Info:    Overwriting math alphabet `\mathit' in version `normal'
(Font)                  OT1/cmr/m/it --> TU/lmr/m/it on input line 10.
LaTeX Font Info:    Overwriting math alphabet `\mathbf' in version `normal'
(Font)                  OT1/cmr/bx/n --> TU/lmr/b/n on input line 10.
LaTeX Font Info:    Overwriting math alphabet `\mathsf' in version `normal'
(Font)                  OT1/cmss/m/n --> TU/lmss/m/n on input line 10.
LaTeX Font Info:    Overwriting math alphabet `\mathtt' in version `normal'
(Font)                  OT1/cmtt/m/n --> TU/lmtt/m/n on input line 10.
LaTeX Font Info:    Overwriting symbol font `operators' in version `bold'
(Font)                  TU/lmr/m/n --> TU/lmr/b/n on input line 10.
LaTeX Font Info:    Overwriting math alphabet `\mathit' in version `bold'
(Font)                  OT1/cmr/bx/it --> TU/lmr/b/it on input line 10.
LaTeX Font Info:    Overwriting math alphabet `\mathsf' in version `bold'
(Font)                  OT1/cmss/bx/n --> TU/lmss/b/n on input line 10.
LaTeX Font Info:    Overwriting math alphabet `\mathtt' in version `bold'
(Font)                  OT1/cmtt/m/n --> TU/lmtt/b/n on input line 10.

*geometry* driver: auto-detecting
*geometry* detected driver: xetex
*geometry* verbose mode - [ preamble ] result:
* driver: xetex
* paper: <default>
* layout: <same size as paper>
* layoutoffset:(h,v)=(0.0pt,0.0pt)
* modes: 
* h-part:(L,W,R)=(92.14519pt, 430.00462pt, 92.14519pt)
* v-part:(T,H,B)=(95.39737pt, 556.47656pt, 143.09605pt)
* \paperwidth=614.295pt
* \paperheight=794.96999pt
* \textwidth=430.00462pt
* \textheight=556.47656pt
* \oddsidemargin=19.8752pt
* \evensidemargin=19.8752pt
* \topmargin=-13.87262pt
* \headheight=12.0pt
* \headsep=25.0pt
* \topskip=10.0pt
* \footskip=30.0pt
* \marginparwidth=65.0pt
* \marginparsep=11.0pt
* \columnsep=10.0pt
* \skip\footins=9.0pt plus 4.0pt minus 2.0pt
* \hoffset=0.0pt
* \voffset=0.0pt
* \mag=1000
* \@twocolumnfalse
* \@twosidefalse
* \@mparswitchfalse
* \@reversemarginfalse
* (1in=72.27pt=25.4mm, 1cm=28.453pt)

LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <24.88> on input line 14.
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <20.74> on input line 14.
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <17.28> on input line 14.
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <8> on input line 14.
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <6> on input line 14.
LaTeX Font Info:    External font `cmex10' loaded for size
(Font)              <5> on input line 14.
[1


] (mwe-1.aux)
 ***********
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2024-04-11>
 ***********
 ) 
Here is how much of TeX's memory you used:
 8912 strings out of 409500
 212413 string characters out of 5770776
 1919406 words of memory out of 5000000
 31060 multiletter control sequences out of 15000+600000
 562706 words of font info for 60 fonts, out of 8000000 for 9000
 1348 hyphenation exceptions out of 8191
 79i,8n,93p,411b,242s stack positions out of 10000i,1000n,20000p,200000b,200000s

Output written on mwe-1.pdf (1 page).

I hope that this is enough as I would very much like to use babel with option scottish, english!

Hugh Shannon Myers
