### ISSUE TITLE
git-latexdiff is not added to the executable path

### ISSUE THREAD

**Issue by pdedecker** [MiKTeX/miktex-packaging#436]
I added git-latexdiff using the Miktex package manager, but no executable file is added to the path.

Example from the Windows commandline, contrasting latexdiff with git-latexdiff:

```
C:\Users\pdedecker>latexdiff
2 and only 2 non-option arguments required.  Write latexdiff -h to get help

C:\Users\pdedecker>git-latexdiff
'git-latexdiff' is not recognized as an internal or external command,
operable program or batch file.
```

It seems that git-latexdiff should be callable from the commandline, similar to latexdiff. The date for the git-latexdiff package is listed as Fri Apr 3 22:11:10 2020.

[miktex-report.txt](https://github.com/MiKTeX/miktex-packaging/files/15414864/miktex-report.txt)

**Comment by edocevoli** [comment]
`git-latexdiff` is Unix shell script which is not usable on Windows.
