### ISSUE TITLE
moderncv package not fully installed

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#439]
The newest version of moderncv 2024-07-18 v2.4.1 contains a moderncvcolors.tex. In texlive this is installed in 
c:/texlive/2024/texmf-dist/tex/latex/moderncv/moderncvcolors.tex

In miktex the file is missing and so

~~~~
\documentclass{moderncv}
\moderncvcolor{red}
\begin{document}
xxxx
\end{document}
~~~~

errors with 

~~~~
! LaTeX Error: File `moderncvcolors.tex' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: tex)
~~~~

**Comment by HellishShark** [comment]
Since the latest update I'm even missing the whole moderncv folder in the Miktex installation dir.
I'm getting the same error.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by reneardila1** [comment]
Thank you
