### ISSUE TITLE
/tex/latex/mff/test.tex should be renamed

### ISSUE THREAD

**Issue by koppor** [MiKTeX/miktex-packaging#440]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

`lualatex test` always works on MiKTeX, but not on TeXLive. The reason is that on MiKTeX, there is a file `/tex/latex/mff/test.tex`.

This can cause issues for LaTeX newbies which are testing around. If they created a `test.tex` in a folder and executed `lualatex` in a different folder, they get a different result. (In my case I created `text.tex` and executed `lualatex test`)

Proposal: Rename the file `test.tex` to `test-mff.tex`.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
