### ISSUE TITLE
files missing from MikTeX font packages following upstream switch to docstrip

### ISSUE THREAD

**Issue by cfr42** [MiKTeX/miktex-packaging#444]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Refs.:
- https://tex.stackexchange.com/questions/729476/missing-adforn-sty-in-miktex-installation-manual-download-lacks-sty-file
- https://tex.stackexchange.com/questions/729476/missing-adforn-sty-in-miktex-installation-manual-download-lacks-sty-file#comment1816429_729476
- https://chat.stackexchange.com/transcript/message/66514261#66514261

I switched various font packages to `docstrip` this summer and I think this has led to some confusion in MikTeX packaging. I should admit that I am not at all familiar with MikTeX, so I'm partly going by reports on TeX SE and partly by guesses about how the `.ini` recipe files work.

`adforn` appears to be missing several files, including the `.sty`, `.enc` and `.fd` files. Looking at the recipes, I assume the same is likely to be true for `adfsymbols`, which should have two sets of LaTeX package files (`adfarrows` and `adfbullets`).

The following packages also switched to `docstrip`, but I'm not sure if they are affected or not:
- `baskervaldadf`
- `berenisadf`
- `cfr-lm`
- `electrumadf`
- `librisadf `
- `nfssext-cfr`
- `romandeadf`
- `venturisadf`

In all cases, a working package requires files generated by processing the `.ins` file, although which files are generated varies a bit.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please get the latest updates.
