### ISSUE TITLE
CURL error for source build

### ISSUE THREAD

**Issue by VITTHANI** [MiKTeX/miktex-packaging#445]
Installing on arch Linux from source, encountered an error--running make(after successful `cmake`).

running `make` produces following:
[0 %] Generating xxxxx.tar.lzma
curl: (22) The requested URL returned error: 404

and some more error following not able download the packages.

I assume that link is broken or relocated. can someone fix this?

**Comment by edocevoli** [comment]
`xxxxx` is an unknown package that explains the 404. Other than that, I cannot help you with this, sorry.

**Comment by VITTHANI** [comment]
> `xxxxx` is an unknown package that explains the 404. Other than that, I cannot help you with this, sorry.

"xxxxx" is not actual package, I mean that every package that is needed for successful completion of `make` command.
for example "miktex-zzdb1-2.9.tar.lzma", "miktex-zzdb2-2.9.tar.lzma" and so on.
