### ISSUE TITLE
pathsuris.sty doesn't exist?

### ISSUE THREAD

**Issue by LaTeX1729** [MiKTeX/miktex-packaging#45]
I renamed one of my packages (really just a .sty file) due to a naming conflict with MiKTeX and whenever I forget to change the name in the preamble of a old document and compile it I get the error message about not finding pathsuris.sty. After some searching it seems the .sty file is supposed to be in the stex package but apparently doesn't actually exist. I created a pathsuris.sty wth only \endinput and now the error message is gone. Does pathsuris.sty actually exist?

**Comment by edocevoli** [comment]
File `pathsuris.sty` is not of the MiKTeX distribution.
