### ISSUE TITLE
files missing from MiKTeX's libertine package [2024-11-24 version]

### ISSUE THREAD

**Issue by xueyuhanlang** [MiKTeX/miktex-packaging#450]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

After updating to the latest Libertine package (version 2024-11-24), I encountered an issue where I could not compile my existing LaTeX file. Below is the minimal LaTeX code to reproduce the error:

```
\documentclass[acmtog]{acmart}
\begin{document}
\title{test}
\maketitle
\end{document}
```
The LaTeX compiler fails because the acmart package, which uses Libertine, reports: “You do not have the Libertine package installed.”

I discovered that the issue arises because the Libertine package (MiKTeX version) does not include the original .sty files. I resolved this issue by following these steps:
- Download the Libertine package from CTAN: https://mirrors.ctan.org/install/fonts/libertine.tds.zip.
- Extract the subfolder /tex/latex/libertine from the zip file to MyMiKTeXFolder/tex/latex.
- Refresh the file name database using the MiKTeX Console interface.

**Comment by rdtennent** [comment]
By mistake, I uploaded an incomplete tds archive to CTAN.  This was corrected the next day.  Presumably, MiKTeX installed the incomplete package before it was updated.  

Bob Tennent (libertine maintainer)

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by rdtennent** [comment]
thanks; sorry for the hassel.
