### ISSUE TITLE
*.hak runtime files are missing in MiKTeX package scrhack

### ISSUE THREAD

**Issue by komascript** [MiKTeX/miktex-packaging#451]
The [MiKTeX file list of `scrhack`](https://miktex.org/packages/scrhack/files) with package date 09/15/2024 10:30:12 lists only the files 

* `texmf\tex\latex\scrhack\scrhack-2023-07-07.sty`
* `texmf\tex\latex\scrhack\scrhack.sty`
* `texmf\tpm\packages\scrhack.tpm`

Note: `scrhack-2023-07-07.sty` is useless without the runtime files `float.hak`, `floatrow.hak`, `hyperref.hak`, `listings.hak`, `lscape.hak`, `nomencl.hak`, `setspace.hak`, and `standardsectioning.hak`. You should IMHO install them also into `texmf\text\latex\scrhack`.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
