### ISSUE TITLE
revtex4 package is outdated

### ISSUE THREAD

**Issue by v-koryanov** [MiKTeX/miktex-packaging#453]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

Hello.

Documents that uses revtex4 class (from the current version of revtex4 package) won't build. Example:

```
\documentclass{revtex4}
\begin{document}
test
\end{document}
```
gives error
```
! Extra \endgroup.
\document ->\endgroup 
                      \init@documenthook \set@typesize@hook \normalsize \set...
l.2 \begin{document}
```

CTAN has revtex4-0 version 4.0a in which this problem was fixed: https://ctan.org/pkg/revtex4-0

Best regards.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
