### ISSUE TITLE
Still problem with package fontscripts

### ISSUE THREAD

**Issue by petiard** [MiKTeX/miktex-packaging#454]
I open a new issue which is similar to #443 (which is closed) because the problem is not solved.

Hello

In MiKTeX Console, Packages, the list of packages contains fontscripts but there is no file fontscripts.tar.lzma in MIKTeX repositories.
There are fontscripts__doc and fontscripts__source but not fontscripts.

Best regards

François

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by cfr42** [comment]
> Thank you, this has been fixed. Please check for updates tomorrow.

Perhaps it would be worth mentioning that the problem has apparently been 'fixed' by dropping `fontscripts` altogether?
