### ISSUE TITLE
geometry.sty missing from geometry-de package

### ISSUE THREAD

**Issue by jvoigtlaender** [MiKTeX/miktex-packaging#46]
The 2018-09-04 version of the geometry-de package seems to be missing all runtime files: https://miktex.org/Package/Browse/geometry-de

The same issue apparently existed a few months back concerning the geometry package (without -de): https://github.com/MiKTeX/miktex-packaging/issues/29

That issue was fixed, but for geometry-de the files are still missing.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by jvoigtlaender** [comment]
Thanks!

**Comment by davidcarlisle** [comment]
miktex now has two copies of geometry.sty, with this one being old and unmaintained (and not working in luatex) The error is really at ctan I'll ask them to remove this, or we could make geometry-de a documentation-only package and disable the extraction of the .sty from the dtx.

**Comment by edocevoli** [comment]
I have removed `geometry-de` from the package repository.

**Comment by davidcarlisle** [comment]
thanks
