### ISSUE TITLE
Package definition could not be parsed

### ISSUE THREAD

**Issue by thatlittleboy** [MiKTeX/miktex-packaging#48]
As per #34 and (#145 on Miktex tracker),

I received similar error message when I tried to Update package database as well as Check for updates. I refreshed FNDB, font map files, and changed package repository to no avail.

`path="C:\Users\user\AppData\Local\Temp\mik55137\bxorigcapt.tpm", column="1024", line="2"`

I suppose this is a bug that needs to be fixed? Or am I doing something wrongly?

I went to that .\Temp folder. The `mik55137` folder is not present (I can see hidden files and folders.)
I'm on Windows 10, 64bit. If you need more information, let me know.

**Comment by edocevoli** [comment]
Yes, this is a bug that needs to be fixed.

**Comment by edocevoli** [comment]
I have edited the package metadata to fix the issue. The fix will be rolled out with the next update.

**Comment by kierancassel** [comment]
Anything I can do in the meantime? It's unusable because I don't have packages I need for what I'm working on.

**Comment by Friduric** [comment]
When will the fix be rolled out?

**Comment by edocevoli** [comment]
The updates will be uploaded to CTAN this evening (Europe).

**Comment by edocevoli** [comment]
The repository service will be resumed tomorrow morning (Europe time).

**Comment by DriesDeKegel** [comment]
Is a workaround possible to compile the .tex-files?
It seems that for me bibtex is not aible to compile anymore.

**Comment by hexafraction** [comment]
Is there a workaround available to install packages from the prior version of the repository (or at least to do so from another repository)? 

It's not even possible to change to a fallback repository as the list of repositories cannot be fetched, and it seems unusual that a single faulty package should make it impossible for users to download completely unrelated packages without manually fetching their entire dependency trees by hand and hand-installing.

**Comment by flabb17** [comment]
Hello, we are "tomorrow morning"  (Europe time 9 AM) and it's not working , any news ?  

Thank you.

**Comment by edocevoli** [comment]
The service is now operating again.

**Comment by micmys** [comment]
Thank you for solving the problem :-)
