### ISSUE TITLE
libertinus wrapper package

### ISSUE THREAD

**Issue by moewew** [MiKTeX/miktex-packaging#49]
The Libertinus font packages were re-organised recently.

There are now three packages on CTAN
- `libertinus-type1` https://ctan.org/pkg/libertinus-type1
- `libertinus-otf` https://ctan.org/pkg/libertinus-otf
- `libertinus` https://ctan.org/pkg/libertinus

The first two are also in MikTeX, but the last, which is only a thin wrapper to pick the type 1 or OTF fonts for the engine is not available on MikTeX yet.

Please include `libertinus` (https://ctan.org/pkg/libertinus) in MikTeX.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
