### ISSUE TITLE
.fd-files of ipaex-type1 are in the wrong places

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#5]
`ipaex-type1` installs a number of `. fd` and `.fdx` files in `fonts\tex\latex\ipaex-type1`. This is the wrong place. They shouldn't be in the `fonts` folder but directly in `tex\latex\ipaex-type1`.

Also the case of the files is wrong. There should use uppercases for the encoding: C70, T1, TS1, OT1 - on windows it shouldn't matter but it could be a problem for the linux version.

**Comment by edocevoli** [comment]
The case of the file name seems to be unchanged (compared to CTAN file names). I will fix the location issue.

**Comment by u-fischer** [comment]
Sorry I mixed up the case question. They are correct.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. You can run the updater now.
