### ISSUE TITLE
ducksay  package is not correctly installed.

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#52]
The dtx contains three tex-files which should go into tex/latex/ducksay too:

`ducksay.code.v1.tex`, `ducksay.code.v2.tex`, `ducksay.animals.tex`

~~~~
\documentclass{book}
\usepackage{ducksay}
\begin{document}
\ducksay{hello}
\end{document}
~~~~

fails currently with 

~~~~
File 'ducksay.code.v2.tex' not found.
~~~~

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
