### ISSUE TITLE
Package pst-eucl

### ISSUE THREAD

**Issue by Alfonsib** [MiKTeX/miktex-packaging#54]
The last update of pst-eucl (v. 2.60) has only  3files: Changes, Readme and pst-eucl.tpm:

![pb-pst-eucl](https://user-images.githubusercontent.com/2809302/46672726-77516e80-cbd8-11e8-88a8-fc102b30f84f.png)

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
