### ISSUE TITLE
Error installing "Just me"

### ISSUE THREAD

**Issue by ericwertz** [MiKTeX/miktex-packaging#55]
However, the same installer specifying All Users works fine.

-------------------------------

updating package definition directory ("C:\Users\Eric\AppData\Local\Programs\MiKTeX 2.9\tpm\packages")...
installed 3377 package definition files
visiting repository C:\Users\Eric\AppData\Local\Temp\mik83063...
repository type: local package repository
loading lightweight database...
67 [0x000008d8] INFO initexmf null - starting: MiKTeX Configuration Utility 2.9.6811 (MiKTeX 2.9.6800 64-bit)
 68 [0x000008d8] INFO initexmf null - Operating on the private (per-user) MiKTeX setup
 68 [0x000008d8] INFO initexmf null - starting with command line: initexmf "--user-install=C:\Users\Eric\AppData\Local\Programs\MiKTeX 2.9" "--common-install=C:\Program Files\MiKTeX 2.9" --set-config-value=[Core]SharedSetup=0 "--log-file=C:\Users\Eric\AppData\Local\Programs\MiKTeX 2.9\miktex/config\uninst.log" --disable-installer --verbose
 68 [0x000008d8] FATAL initexmf null - --user-install=C:\Users\Eric\AppData\Local\Programs\MiKTeX 2.9: unknown option
  Sorry, but "MiKTeX Configuration Utility" did not succeed for the following reason:    --user-install=C:\Users\Eric\AppData\Local\Programs\MiKTeX 2.9: unknown option

Error: The executed process did not succeed.

**Comment by edocevoli** [comment]
This is not the right issue tracker for these kinds of problems. Please visit https://miktex.org/help, for details.
