### ISSUE TITLE
UK Download Site Down - anorien.csc.warwick.ac.uk

### ISSUE THREAD

**Issue by alexanderweeks** [MiKTeX/miktex-packaging#57]
The `https://anorien.csc.warwick.ac.uk/mirrors/CTAN/` site appears to be down (refused to connect error).

Using the alternative CTAN site `http://mirror.ox.ac.uk/sites/ctan.org/` fixes this but there is no option to select this from the download page.

**Comment by alexanderweeks** [comment]
Also apologies if this is under the wrong issue tracker.

**Comment by edocevoli** [comment]
Thank you, this is a temporary issue.
