### ISSUE TITLE
Update l3kernel

### ISSUE THREAD

**Issue by moewew** [MiKTeX/miktex-packaging#58]
`l3kernel` version `2018-10-17` that MikTeX currently ships has a nasty bug (https://github.com/latex3/latex3/issues/491) that causes confusing low-level error messages.

The bug was swiftly resolved in the `2018-10-19` version. That update has not made it to MikTeX as of this morning (UTC), causing some confusion for users, see https://tex.stackexchange.com/q/456326/35864, https://tex.stackexchange.com/q/456257/35864, https://tex.stackexchange.com/q/456134/35864.

It would be great if the update could be included in the next batch of package updates (I assume for tonight/tomorrow morning)

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by moewew** [comment]
Thank you very much.
