### ISSUE TITLE
pdfcrop: The script could not be found.

### ISSUE THREAD

**Issue by MaxKuh** [MiKTeX/miktex-packaging#6]
Same issue as "#2080 pdfcrop: The Perl script could not be found. " since last update of Miktex.

When calling pdfcrop.exe one get's the following error:
pdfcrop: The script could not be found.
pdfcrop: Data: ScriptEngine="perl", name="pdfcrop", path="scripts/pdfcrop/pdfcrop.pl"

Actually pdfcrop.pl is located in
scripts/pdfcrop/perl
whereas it is assumed to be in
scripts/pdfcrop/
.

Everything worked fine before the last update.

**Comment by edocevoli** [comment]
The script path `scripts/pdfcrop/pdfcrop.pl` and the actual file location match. Seems that you are testing against an outdated MiKTeX version. Please update your setup.

**Comment by MaxKuh** [comment]
Issue started after (!) the last update. If I click on Update the message "There are currently no updates available." pops up. (Admin and normal mode). PDFcrop worked fine until I started the last update.

MiKTeX 2.9\scripts\pdfcrop\perl
and
MiKTeX 2.9\scripts\pdfcrop
are not the same path. 

So the update destroyed pdfcrop for me and I am looking for a workaround. If you have a hint for me, please let me know.

**Comment by edocevoli** [comment]
Sorry, I should have read it more carefully. So you are up-to-date and suddenly the script path is wrong.

I don't have access to your setup so I can't show you a work-around. What I have checked: the distributed `scripts.ini` contains the correct script path and the distributed `pdfcrop` package installs the script in the correct location.

**Comment by MaxKuh** [comment]
I just found the solution:
- Uninstall pdfcrop package with Package Manager (Admin)
- In Settings "Refresh FNDB" and "Update Formats" (don't know if this is really necessary)
- Back in the Package Manager (Admin) synchronize repository (just to be sure to have the latest data)
- Install pdfcrop again from Package Manager
- In Settings "Refresh FNDB" and "Update Formats" (don't know if this is really necessary)

At least that solved the problem for me.
