### ISSUE TITLE
The requested package is unknown.  name="ltxbase"

### ISSUE THREAD

**Issue by sgechert** [MiKTeX/miktex-packaging#60]
Dear all,

I am new to this site, so I hope I play by the rules.

I just found that my miktex root directories are not shown in the Miktex Console. And running a tex file via WinEdt does not find the files inside the root either.  If I try to re-enter the roots the error above appears. The same with random new folders. The roots seem to be available according to the log file still. Is there any advice from your side? 

Here is my log file:
MiKTeX: 2.9
OS: Windows 7 Enterprise, 64-bit, Service Pack 1, build 7601
SharedSetup: no
PathOkay: yes
SystemAdmin: no
RootPrivileges: no
Root0: C:\Users\sebastian-gechert\AppData\Roaming\MiKTeX\2.9
Root1: C:\Users\sebastian-gechert\AppData\Local\MiKTeX\2.9
Root2: D:\Daten\texmf
Root3: D:\Daten\texmf\tex
Root4: D:\download
Root5: D:\MikTeX2.9
Root6: C:\ProgramData\MiKTeX\2.9
Root7: C:\Program Files\MiKTeX 2.9
UserInstall: D:\MikTeX2.9
UserConfig: C:\Users\sebastian-gechert\AppData\Roaming\MiKTeX\2.9
UserData: C:\Users\sebastian-gechert\AppData\Local\MiKTeX\2.9
CommonInstall: C:\Program Files\MiKTeX 2.9
CommonConfig: C:\ProgramData\MiKTeX\2.9
CommonData: C:\ProgramData\MiKTeX\2.9

**Comment by edocevoli** [comment]
This is not the right issue tracker for these kinds of problems. Please visit https://miktex.org/help, for details.
