### ISSUE TITLE
remove the rotating package

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#61]
rotating.sty is now maintained by the latex team and is distribuated in the graphics package. The standalone rotating package should be removed. 

~~~~
..../MiKTeX/tex/latex/graphics/rotating.sty
..../MiKTeX/tex/latex/rotating/rotating.sty
~~~~

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
