### ISSUE TITLE
A problem with Yap

### ISSUE THREAD

**Issue by Michael1812** [MiKTeX/miktex-packaging#62]
There may be a possibility that in the latest version of MiKTeX there are problems with the file mgs.exe

This is a short description of the problem:
________________________________________________
Having installed MiKTeX, I found that Yap -- which is a part of the package -- completely fails to show text when the rendering method is chosen as "Dvips". 
The text appears, if the rendering method is chosen as "Pk". However, in this case no figures are rendered, and the system shows 

Windows API error 5 "Access is denied" 
fileName="C:\Program Files\MiKTeX 2.9\miktex\bin\x64\mgs.exe"
commandLine="mgs --version"

Can someone please advise what to do?
Many thanks!

**Comment by edocevoli** [comment]
This is not the right issue tracker for these kinds of problems. Please visit https://miktex.org/help, for details.
