### ISSUE TITLE
Cannot download MiKTeX due to verification failed.

### ISSUE THREAD

**Issue by GauSyu** [MiKTeX/miktex-packaging#63]
My OS is Windows 10. 
I try to use net installer to download MiKTeX today, but it keeps occuring the following error 
(always the same file)

> An error occurred:
>   source file: Libraries\MiKTeX\PackageManager\PackageInstallerImpl.cpp
>   source line: 1434
>   message: The operation could not be completed because a required file failed verification.
>   info: package="miktex-hunspell-bin-2.9", arhiveFile="D:\MATH-SOFTWARE\MiKTeX\miktex-hunspell-bin-2.9.tar.lzma", expectedMD5="e9b4628db4699fe7996526b13b76ffa0", actualMD5="a070f34e94b5c842ebf05d2238a1464b"

It seems the MD5 are not matched. I don' know if this is a bug or not.

**Comment by ilyavichev** [comment]
I have the same problem!

**Comment by jeroenbrussich** [comment]
for what it is worth, I got an md5 checksum error on zzdb1

**Comment by edocevoli** [comment]
Thank you. It seems that the mirrors didn't get the whole update set. Probably because some updated archive files haven't changed in size (only in content).

**Comment by edocevoli** [comment]
@jeroenbrussich: the zzdb1 file is not md5-checked so I doubt your statement.

**Comment by Jcj1610** [comment]
Can anyone give us a status update on this? Thx

**Comment by Saftbernd** [comment]
> Can anyone give us a status update on this? Thx

Would recommend that.

**Comment by Saftbernd** [comment]
It seems that this is a much bigger issue than expected, because the miktex.org delivers now a 502 server error. Could be a bad coinsitance but i don't think so. Just hope they can fix the problem asap, because i'am in trouble with me thesis now. Anyone who could help or at least add an workaround would be a huge support. The biggest problem for me is an corrupt bibtex package which cant be implemented beccause of the failed validation process.

**Comment by Jcj1610** [comment]
I too have noticed the 502 error, although I'm not sure they're related. If you have literally zero time to wait, then I guess you'll just have to switch to [TexLive](http://tug.org/texlive/) for now. I can wait it out a little bit longer, but I would still appreciate that status update ...

**Comment by mohitpandey92** [comment]
I am having the same problem. If someone has a deadline (like me), then I would suggest to try [overleaf](https://www.overleaf.com/).

**Comment by brunoezhVet** [comment]
Thanks @mohitpandey92 - this post really is helpful. I need urgently to email my CV to a head hunter and can't compile it while the repos is down.

**Comment by Jcj1610** [comment]
@edocevoli Are you working on this? Can you give a status update?

**Comment by edocevoli** [comment]
There is nothing I can do at the moment. Just wait and see if the mirrors fetch the updated archives.

**Comment by jeroenbrussich** [comment]
> There is nothing I can do at the moment. Just wait and see if the mirrors fetch the updated archives.

@edocevoli - not even a ETA? I understand this is a stressfull period for you and that you distribute the software 'as is' but without any concrete information, we are in the dark... I (also) need to finish a paper and a meeting report by yesterday...

Did you find the cause and a fix or are we just all waiting to see what happens? Is there something we can do? Give you more (and in my case: better) error-reports? Something?

**Comment by parthi2929** [comment]
can we manually install or have any other workaround in the mean time?

**Comment by edocevoli** [comment]
The mirroring succeeded. I have reopened the package repository.
