### ISSUE TITLE
lipsum package does not include lipsum.sty

### ISSUE THREAD

**Issue by benedictleejh** [MiKTeX/miktex-packaging#67]
The `lipsum` package on MiKTeX does not actually include the files required for it to work. Attempting to use the package as is causes a `lipsum.sty not found` error.

**Comment by edocevoli** [comment]
The `lipsum` package is currently broken, i.e., running `latex lipsum.dtx` does not work. This is nothing I can fix at my end.

**Comment by moewew** [comment]
Following https://github.com/patta42/lipsum/issues/11 version 2.1a that's up on CTAN now (https://ctan.org/pkg/lipsum) has an `.ins` file that can be used to produce the `.sty` from `lipsum.dtx`.
