### ISSUE TITLE
biblatex-ext: blxextdoiapi.lua missing

### ISSUE THREAD

**Issue by moewew** [MiKTeX/miktex-packaging#69]
The package for `biblatex-ext` v0.6 updated tonight (2018-11-25) does not include the file `blxextdoiapi.lua`. That file should live alongside `biblatex-ext-oa-doiapi.sty` in `texmf/tex/latex/biblatex-ext`.

The following LuaLaTeX-MWE therefore fails
```
% run with LuaLaTeX
\documentclass[british]{article}
\usepackage{babel}
\usepackage{csquotes}

\usepackage[backend=biber, style=ext-numeric]{biblatex}
\usepackage[doiapi=true, tikzsymbol=plos]{biblatex-ext-oa}

\ExecuteBibliographyOptions{openaccess=doiapi}

\SetDOIAPIMail{<your email here>}% <- this MUST be set for doiapi

\usepackage[colorlinks]{hyperref}

\addbibresource{biblatex-examples.bib}
\begin{document}
\cite{sigfridsson}
\printbibliography
\end{document}
```

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by moewew** [comment]
Thank you very much. The module is found now and works as expected.
