### ISSUE TITLE
Incorrectly installed files in thesis-ekf (v2.3)

### ISSUE THREAD

**Issue by hair-splitter** [MiKTeX/miktex-packaging#70]
In the latest version (2.3) of the thesis-ekf class, the following files are incorrectly installed in the 
texmf\doc\latex\thesis-ekf directory:

eszterhazy-logo-en.eps
eszterhazy-logo-en.pdf
eszterhazy-logo-hu.eps
eszterhazy-logo-hu.pdf

These should be moved to the texmf\tex\latex\thesis-ekf directory (see README file). 
These files are used by thesis-ekf.cls.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.
