### ISSUE TITLE
colorprofiles package is incomplete

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#76]
The colorprofiles package contains four files which must found during a compilation, two .icc, one sty and one tex:

~~~~
FOGRA39L_coated.icc
colorprofiles.sty 
colorprofiles.tex
sRGB.icc 
~~~~

The miktex package has only the sty, and so e.g. a document using the pdfx package fails. 

(In texlive all four files are in tex/generic/colorprofiles).

**Comment by edocevoli** [comment]
Thanks, I have added the three missing files and the new location is `tex/generic/colorprofiles`. The fix will be available with one of the next updates.
