### ISSUE TITLE
lipsum package not finding runtime lipsum.ltd.tex and cicero.ltd.tex

### ISSUE THREAD

**Issue by moewew** [MiKTeX/miktex-packaging#79]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The files `cicero.ltd.tex` and `lipsum.ltd.tex` of the recent version 2.2 of `lipsum` should live in the runtime directory as they need to be accessed by the package directly. This morning's update did not install those files in runtime and they are not listed in https://miktex.org/Package/Browse/lipsum.

Hence the following MWE
```
\documentclass{article}
\usepackage{lipsum}

\begin{document}
\lipsum
\end{document}
```
produces the error
```
Package: lipsum 2019/01/02 v2.2 150 paragraphs of Lorem Ipsum dummy text


! LaTeX3 Error: File 'lipsum.ltd' not found.

For immediate help type H <return>.
 ...                                              
                                                  
l.642 \SetLipsumText{lipsum}
                            
? 
)
```

Please move `cicero.ltd.tex` and `lipsum.ltd.tex` to `texmf\tex\latex\lipsum` next to `lipsum.sty`.

This was also an issue for TeX live a few days ago: https://tug.org/pipermail/tex-live/2019-January/043043.html, https://tug.org/pipermail/tex-live/2019-January/043047.html and https://tug.org/pipermail/tex-live-commits/2019-January/008334.html

Cf. also https://github.com/patta42/lipsum/issues/14

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by moewew** [comment]
Thank you very much. The MWE works just as expected again.
