### ISSUE TITLE
Error when using pgf/tikz

### ISSUE THREAD

**Issue by LukasMD** [MiKTeX/miktex-packaging#81]
Hi, it seems like the miktex package pgf is broken, it doesn't contain any files.

Just the simple \usepackage{tikz} command causes a "File 'tikz.sty' not found" error.

**Comment by AlanGillespie** [comment]
The absence of 'pgfcore.sty' also breaks beamer

**Comment by LukasMD** [comment]
just saw, that this issue has already been taken care of https://github.com/MiKTeX/miktex-packaging/issues/80

**Comment by edocevoli** [comment]
Duplicate of #80
