### ISSUE TITLE
asana-math package is missing the file ASANA.TTC

### ISSUE THREAD

**Issue by u-fischer** [MiKTeX/miktex-packaging#83]
Asana-math on ctan contains also a font ASANA.TTC which is missing in the miktex package. (texlive installs it in /texmf-dist/fonts/truetype/public/Asana-Math/ASANA.TTC).

**Comment by edocevoli** [comment]
The `*.TTC` file should not be included in a standard TeX installation:

From the `README`:

> NOTE: Ideally, the font should be installed systemwide. However,
> the .TTC file should be installed only in Windows systems and it
> is provided for people using FireFox, Word, etc. In addition, the
> .TTC file should not be included in a standard TeX installation.
> On Unix or Unix-like system, an administrtor can install either 
> the .otf or the .TTC file in her system.
