### ISSUE TITLE
tufte.bst in wrong location

### ISSUE THREAD

**Issue by moewew** [MiKTeX/miktex-packaging#87]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The `tufte-latex` package currently installs the bibliography style `tufte.bst` into `texmf/tex/latex/tufte-latex`. As
```
\documentclass{tufte-book}

\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{appleby,
  author    = {Humphrey Appleby},
  title     = {On the Importance of the Civil Service},
  year      = {1980},
  publisher = {Pub},
  address   = {Place},
}
\end{filecontents}

\begin{document}
Lorem\cite{appleby}

\bibliography{\jobname}  
\bibliographystyle{tufte} 
\end{document} 
```
and in particular BibTeX's complaint
```
I couldn't open style file tufte.bst
---line 22 of file euttzetzete.aux
 : \bibstyle{tufte
 :                }
I'm skipping whatever remains of this command
```
demonstrate,  the file is not found there by BibTeX.

Please move  `tufte.bst` to `texmf/bibtex/bst/tufte-latex` so that it can be found by BibTeX.

**Comment by edocevoli** [comment]
By the author's request the `.bst` file is not installed in `bibtex/bst/tufte-latex`.

Reference: https://ctan.org/tex-archive/install/macros/latex/contrib/tufte-latex.tds.zip

**Comment by moewew** [comment]
Mhhh, fair enough. But I believe this is a genuine mistake by the author of the `tds.zip`. The `.bst` file is not found in the `tex` subtree and hence useless. TeX live installs the `.bst` into `bibtex/bst`: https://www.tug.org/svn/texlive/trunk/Master/texmf-dist/bibtex/bst/tufte-latex/ and https://www.tug.org/svn/texlive?view=revision&revision=37649

I opened an issue at the `tufte-latex` bugtracker: https://github.com/Tufte-LaTeX/tufte-latex/issues/142
