### ISSUE TITLE
File 'leipzig.tex' not found

### ISSUE THREAD

**Issue by bradrn** [MiKTeX/miktex-packaging#89]
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

From [the original StackOverflow question](https://tex.stackexchange.com/questions/476279/file-leipzig-tex-not-found):

> Whenever I try to use the `leipzig` package, I get the following error:
> 
>     ! LaTeX Error: File `leipzig.tex' not found.
> 
> I don't recall getting this error for any other package (although I may have simply forgotten).
> 
> Here's a minimal non-working example:
> 
>     \documentclass{article}
>     
>     \usepackage{leipzig}
>     
>     \begin{document}
>     \end{document}
> 
> **EDIT:** The `leipzig` package is definitely installed on my machine. I can find `leipzig.sty` in the `C:\Program Files\MiKTeX 2.9\tex\latex\leipzig` folder, but I cannot find any `leipzig.tex` file.
> 
> **EDIT2:** As requested by @Johannes_B, here's the log file:
> 
> <details><summary>Click for log file</summary>
> <p>
>
>     This is pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6930 64-bit) (preloaded format=pdflatex 2019.2.1)  23 FEB 2019 17:27
>     entering extended mode
>     **./lzg.tex
>     (lzg.tex
>     LaTeX2e <2018-12-01>
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/base\article.cls"
>     Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/base\size10.clo"
>     File: size10.clo 2018/09/03 v1.4i Standard LaTeX file (size option)
>     )
>     \c@part=\count80
>     \c@section=\count81
>     \c@subsection=\count82
>     \c@subsubsection=\count83
>     \c@paragraph=\count84
>     \c@subparagraph=\count85
>     \c@figure=\count86
>     \c@table=\count87
>     \abovecaptionskip=\skip41
>     \belowcaptionskip=\skip42
>     \bibindent=\dimen102
>     )
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/leipzig\leipzig.sty"
>     Package: leipzig 2017/06/16 v2.0 Leipzig package for linguistic abbreviations
>     
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/glossaries/base\glossaries.sty"
>     Package: glossaries 2019/01/06 v4.42 (NLCT)
>     
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/base\ifthen.sty"
>     Package: ifthen 2014/09/29 v1.1c Standard LaTeX ifthen package (DPC)
>     )
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/xkeyval\xkeyval.sty"
>     Package: xkeyval 2014/12/03 v2.7a package option processing (HA)
>     
>     ("C:\Program Files\MiKTeX 2.9\tex/generic/xkeyval\xkeyval.tex"
>     ("C:\Program Files\MiKTeX 2.9\tex/generic/xkeyval\xkvutils.tex"
>     \XKV@toks=\toks14
>     \XKV@tempa@toks=\toks15
>     
>     ("C:\Program Files\MiKTeX 2.9\tex/generic/xkeyval\keyval.tex"))
>     \XKV@depth=\count88
>     File: xkeyval.tex 2014/12/03 v2.7a key=value parser (HA)
>     ))
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/mfirstuc\mfirstuc.sty"
>     Package: mfirstuc 2017/11/14 v2.06 (NLCT)
>     
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/etoolbox\etoolbox.sty"
>     Package: etoolbox 2018/08/19 v2.5f e-TeX tools for LaTeX (JAW)
>     \etb@tempcnta=\count89
>     )
>     \@glsmfirst=\toks16
>     \@glsmrest=\toks17
>     )
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/textcase\textcase.sty"
>     Package: textcase 2004/10/07 v0.07 Text only upper/lower case changing (DPC)
>     )
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/xfor\xfor.sty"
>     Package: xfor 2009/02/05 v1.05 (NLCT)
>     )
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/datatool\datatool-base.sty"
>     Package: datatool-base 2018/12/07 v2.31 (NLCT)
>     
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/amsmath\amsmath.sty"
>     Package: amsmath 2018/12/01 v2.17b AMS math features
>     \@mathmargin=\skip43
>     
>     For additional information on amsmath, use the `?' option.
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/amsmath\amstext.sty"
>     Package: amstext 2000/06/29 v2.01 AMS text
>     
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/amsmath\amsgen.sty"
>     File: amsgen.sty 1999/11/30 v2.0 generic functions
>     \@emptytoks=\toks18
>     \ex@=\dimen103
>     ))
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/amsmath\amsbsy.sty"
>     Package: amsbsy 1999/11/29 v1.2d Bold Symbols
>     \pmbraise@=\dimen104
>     )
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/amsmath\amsopn.sty"
>     Package: amsopn 2016/03/08 v2.02 operator names
>     )
>     \inf@bad=\count90
>     LaTeX Info: Redefining \frac on input line 223.
>     \uproot@=\count91
>     \leftroot@=\count92
>     LaTeX Info: Redefining \overline on input line 385.
>     \classnum@=\count93
>     \DOTSCASE@=\count94
>     LaTeX Info: Redefining \ldots on input line 482.
>     LaTeX Info: Redefining \dots on input line 485.
>     LaTeX Info: Redefining \cdots on input line 606.
>     \Mathstrutbox@=\box27
>     \strutbox@=\box28
>     \big@size=\dimen105
>     LaTeX Font Info:    Redeclaring font encoding OML on input line 729.
>     LaTeX Font Info:    Redeclaring font encoding OMS on input line 730.
>     \macc@depth=\count95
>     \c@MaxMatrixCols=\count96
>     \dotsspace@=\muskip10
>     \c@parentequation=\count97
>     \dspbrk@lvl=\count98
>     \tag@help=\toks19
>     \row@=\count99
>     \column@=\count100
>     \maxfields@=\count101
>     \andhelp@=\toks20
>     \eqnshift@=\dimen106
>     \alignsep@=\dimen107
>     \tagshift@=\dimen108
>     \tagwidth@=\dimen109
>     \totwidth@=\dimen110
>     \lineht@=\dimen111
>     \@envbody=\toks21
>     \multlinegap=\skip44
>     \multlinetaggap=\skip45
>     \mathdisplay@stack=\toks22
>     LaTeX Info: Redefining \[ on input line 2844.
>     LaTeX Info: Redefining \] on input line 2845.
>     )
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/substr\substr.sty"
>     Package: substr 2009/10/20 v1.2 Handle substrings
>     \c@su@anzahl=\count102
>     )
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/datatool\datatool-fp.sty"
>     Package: datatool-fp 2018/12/07 v2.31 (NLCT)
>     
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/fp\fp.sty"
>     Package: fp 1995/04/02
>     
>     `Fixed Point Package', Version 0.8, April 2, 1995 (C) Michael Mehlich
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/fp\defpattern.sty"
>     Package: defpattern 1994/10/12
>     \actioncount=\count103
>     )
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/fp\fp-basic.sty"
>     Package: fp-basic 1996/05/13
>     \FP@xs=\count104
>     \FP@xia=\count105
>     \FP@xib=\count106
>     \FP@xfa=\count107
>     \FP@xfb=\count108
>     \FP@rega=\count109
>     \FP@regb=\count110
>     \FP@regs=\count111
>     \FP@times=\count112
>     )
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/fp\fp-addons.sty"
>     Package: fp-addons 1995/03/15
>     )
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/fp\fp-snap.sty"
>     Package: fp-snap 1995/04/05
>     )
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/fp\fp-exp.sty"
>     Package: fp-exp 1995/04/03
>     )
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/fp\fp-trigo.sty"
>     Package: fp-trigo 1995/04/14
>     )
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/fp\fp-pas.sty"
>     Package: fp-pas 1994/08/29
>     )
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/fp\fp-random.sty"
>     Package: fp-random 1995/02/23
>     \FPseed=\count113
>     )
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/fp\fp-eqn.sty"
>     Package: fp-eqn 1995/04/03
>     )
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/fp\fp-upn.sty"
>     Package: fp-upn 1996/10/21
>     )
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/fp\fp-eval.sty"
>     Package: fp-eval 1995/04/03
>     )))
>     \@dtl@toks=\toks23
>     \@dtl@tmpcount=\count114
>     \dtl@tmplength=\skip46
>     \dtl@sortresult=\count115
>     \@dtl@numgrpsepcount=\count116
>     \@dtl@datatype=\count117
>     \dtl@codeA=\count118
>     \dtl@codeB=\count119
>     \@dtl@foreach@level=\count120
>     )
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/glossaries/base\glossaries-compatible-3
>     07.sty"
>     Package: glossaries-compatible-307 2019/01/06 v4.42 (NLCT)
>     )
>     \gls@level=\count121
>     \@gls@tmpb=\toks24
>     \gls@tmplen=\skip47
>     \glskeylisttok=\toks25
>     \glslabeltok=\toks26
>     \glsshorttok=\toks27
>     \glslongtok=\toks28
>     
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/glossaries/styles\glossary-hypernav.sty
>     "
>     Package: glossary-hypernav 2019/01/06 v4.42 (NLCT)
>     ) ("C:\Program Files\MiKTeX 2.9\tex/latex/glossaries/styles\glossary-list.sty"
>     Package: glossary-list 2019/01/06 v4.42 (NLCT)
>     \glslistdottedwidth=\skip48
>     ) ("C:\Program Files\MiKTeX 2.9\tex/latex/glossaries/styles\glossary-long.sty"
>     Package: glossary-long 2019/01/06 v4.42 (NLCT)
>     
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/tools\longtable.sty"
>     Package: longtable 2014/10/28 v4.11 Multi-page Table package (DPC)+ FMi change
>     \LTleft=\skip49
>     \LTright=\skip50
>     \LTpre=\skip51
>     \LTpost=\skip52
>     \LTchunksize=\count122
>     \LTcapwidth=\dimen112
>     \LT@head=\box29
>     \LT@firsthead=\box30
>     \LT@foot=\box31
>     \LT@lastfoot=\box32
>     \LT@cols=\count123
>     \LT@rows=\count124
>     \c@LT@tables=\count125
>     \c@LT@chunks=\count126
>     \LT@p@ftn=\toks29
>     )
>     \glsdescwidth=\skip53
>     \glspagelistwidth=\skip54
>     )
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/glossaries/styles\glossary-super.sty"
>     Package: glossary-super 2019/01/06 v4.42 (NLCT)
>     
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/supertabular\supertabular.sty"
>     Package: supertabular 2004/02/20 v4.1e the supertabular environment
>     \c@tracingst=\count127
>     \ST@wd=\dimen113
>     \ST@rightskip=\skip55
>     \ST@leftskip=\skip56
>     \ST@parfillskip=\skip57
>     \ST@pageleft=\dimen114
>     \ST@headht=\dimen115
>     \ST@tailht=\dimen116
>     \ST@pagesofar=\dimen117
>     \ST@pboxht=\dimen118
>     \ST@lineht=\dimen119
>     \ST@stretchht=\dimen120
>     \ST@prevht=\dimen121
>     \ST@toadd=\dimen122
>     \ST@dimen=\dimen123
>     \ST@pbox=\box33
>     ))
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/glossaries/styles\glossary-tree.sty"
>     Package: glossary-tree 2019/01/06 v4.42 (NLCT)
>     \glstreeindent=\skip58
>     ))
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/glossaries/styles\glossary-mcols.sty"
>     Package: glossary-mcols 2019/01/06 v4.42 (NLCT)
>     
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/tools\multicol.sty"
>     Package: multicol 2018/12/27 v1.8v multicolumn formatting (FMi)
>     \c@tracingmulticols=\count128
>     \mult@box=\box34
>     \multicol@leftmargin=\dimen124
>     \c@unbalance=\count129
>     \c@collectmore=\count130
>     \doublecol@number=\count131
>     \multicoltolerance=\count132
>     \multicolpretolerance=\count133
>     \full@width=\dimen125
>     \page@free=\dimen126
>     \premulticols=\dimen127
>     \postmulticols=\dimen128
>     \multicolsep=\skip59
>     \multicolbaselineskip=\skip60
>     \partial@page=\box35
>     \last@line=\box36
>     \maxbalancingoverflow=\dimen129
>     \mult@rightbox=\box37
>     \mult@grightbox=\box38
>     \mult@gfirstbox=\box39
>     \mult@firstbox=\box40
>     \@tempa=\box41
>     \@tempa=\box42
>     \@tempa=\box43
>     \@tempa=\box44
>     \@tempa=\box45
>     \@tempa=\box46
>     \@tempa=\box47
>     \@tempa=\box48
>     \@tempa=\box49
>     \@tempa=\box50
>     \@tempa=\box51
>     \@tempa=\box52
>     \@tempa=\box53
>     \@tempa=\box54
>     \@tempa=\box55
>     \@tempa=\box56
>     \@tempa=\box57
>     \c@columnbadness=\count134
>     \c@finalcolumnbadness=\count135
>     \last@try=\dimen130
>     \multicolovershoot=\dimen131
>     \multicolundershoot=\dimen132
>     \mult@nat@firstbox=\box58
>     \colbreak@box=\box59
>     \mc@col@check@num=\count136
>     ))
>     ("C:\Program Files\MiKTeX 2.9\tex/latex/glossaries/styles\glossary-inline.sty"
>     Package: glossary-inline 2019/01/06 v4.42 (NLCT)
>     )
>     
>     ! LaTeX Error: File `leipzig.tex' not found.
>     
>     Type X to quit or <RETURN> to proceed,
>     or enter new name. (Default extension: tex)
>     
>     Enter file name: X
>     
>      ) )
>     (\end occurred when \ifx on line 492 was incomplete)
>     (\end occurred when \ifx on line 492 was incomplete) 
>     Here is how much of TeX's memory you used:
>      4968 strings out of 492946
>      73166 string characters out of 3135528
>      196606 words of memory out of 3000000
>      8816 multiletter control sequences out of 15000+200000
>      3640 words of font info for 14 fonts, out of 3000000 for 9000
>      1141 hyphenation exceptions out of 8191
>      54i,1n,30p,1980b,36s stack positions out of 5000i,500n,10000p,200000b,50000s
>     
>     No pages of output.
>     PDF statistics:
>      0 PDF objects out of 1000 (max. 8388607)
>      0 named destinations out of 1000 (max. 500000)
>      1 words of extra memory for PDF output out of 10000 (max. 10000000)
>
> </p></details>

**Comment by bradrn** [comment]
Update: As [reported by Skillmon on the Stack Exchange question](https://tex.stackexchange.com/questions/476279/file-leipzig-tex-not-found?noredirect=1#comment1202268_476279), checking https://miktex.org/Package/Browse/leipzig seems to show that `leipzig.tex` isn't even distributed in MiKTeX. However, it is part of the [`leipzig` GitHub repo](https://github.com/natalieweber/leipzig), so potentially this file has been skipped and should be added.

**Comment by edocevoli** [comment]
Thank you, this has been fixed. Please check for updates tomorrow.

**Comment by bradrn** [comment]
Thank you @edocevoli!

**Comment by bradrn** [comment]
I have just tried the update and confirmed it is indeed working. Thank you again for fixing this!
