### ISSUE TITLE
Biber/biblatex version troubles

### ISSUE THREAD

**Issue by moewew** [MiKTeX/miktex-packaging#9]
`biblatex` 3.8 has been released to CTAN, shortly after 3.8a was published with an emergency bug fix and corrected documentation. Those versions expect Biber 2.8. Currently there are problems building Biber on Linux and Mac OS (cf. https://github.com/plk/biber/issues/187, https://github.com/plk/biber/issues/188), so Biber could not yet be released (neither to CTAN, nor to TeX live).

This leaves us in the undesirable state that the `biblatex` version on CTAN is out of sync with Biber.
With the 2017-11-05 update MikTeX also ships `biblatex` 3.8, but does not update Biber resulting in the same version incompatibility.

From what I can gather from http://tug.org/pipermail/tex-live/2017-November/040777.html and http://tug.org/pipermail/tex-live/2017-November/040779.html the TeX live maintainers took the decision to downgrade `biblatex` back to 3.7 to ensure that `biblatex` and Biber work together properly.
If possible it would be good if MikTeX could do the same and go back to `biblatex` 3.7 until Biber 2.8 can finally be released.

`biblatex` 3.7 can be found at https://sourceforge.net/projects/biblatex/files/biblatex-3.7/ should that be necessary.

**Comment by edocevoli** [comment]
I will revert to biblatex 3.7.

**Comment by moewew** [comment]
Thank you, and sorry for the troubles. `biblatex-apa` probably also needs to go back to 7.4.

**Comment by edocevoli** [comment]
The repositories now contain biblatex 3.7 and biblatex-apa 7.4.

**Comment by moewew** [comment]
Thank you very much.

**Comment by moewew** [comment]
Just in case it had escaped your notice:
Biber 2.8 could finally be released to CTAN, so `biblatex` 3.8a is now safe to use (and so is `biblatex-apa` 7.5). TeX live already has the newest versions running.

**Comment by moewew** [comment]
Thank you again. The new versions have landed safely on my machine.
